// period-skin.tsx (S11/#420 W9) — hockey + icehockey, one hand-crafted layout
// generated by both from period/kernel.ts and byte-identical apart from the
// key prefix. Written BEFORE the implementation (TDD) — every assertion here
// must fail against the current stub (`() => ({header:null, groups:[]})`)
// for the RIGHT reason before a line of period-skin.tsx changes.
//
// Real engine fixtures throughout — hockey + icehockey padSpecs, real
// `cfgSpace` walks, real folded state via `foldClient` — never a hand-rolled
// PadView or a hand-abbreviated state: view-model.test.ts's own header
// explains why (a hand-abbreviated shape can crash a downstream gate/summary
// read in ways that silently discard the assertion), and this file's own
// interactive test additionally needs a REAL folded `state.squads` to prove
// the person-attribution chips (not just the side chips).
//
// Two techniques, matched to what each is actually proving:
//   - The cfg-space sweeps (coverage/header/prominence) use `fullView`, a
//     local copy of skin-coverage.test.ts's own private helper (that file is
//     DO-NOT-TOUCH and exports nothing) — panel gates stripped, exactly the
//     shared gate's own posture, because "does layout() route every action
//     the cfg can ever declare" is a structural property independent of any
//     particular runtime state.
//   - The shootout-gate and interactive tests use the REAL `buildPadView` +
//     `evalPadGate` + `ActionForm`/`renderIsland` path instead, because THOSE
//     tests are specifically about runtime gating and real user interaction,
//     which the gate-stripped sweep view cannot exercise.
import { describe, expect, it } from "vitest";
import type { ReactElement, ReactNode } from "react";
import { propsOf, renderIsland, textOf, walk } from "@/components/__tests__/_hook-harness";
import { messages, type MessageKey } from "@/lib/messages";
import { t as tRuntime } from "@/lib/i18n-runtime";
import { hockey } from "@seazn/engine/sports/hockey";
import { icehockey } from "@seazn/engine/sports/icehockey";
import { defaultLineupPair, makeEnvelope } from "@seazn/engine/testkit";
import type { AnySportModule, PadSpec } from "@seazn/engine/sport";
import { allActionViews, buildPadView, type PadView } from "../view-model";
import { foldClient } from "../module-client";
import { actionByType, createSkinDispatch, layoutActionTypes, layoutActionTypesAt, type SkinProps } from "../skins/types";
import { buildAttributionRenderer, periodSkin } from "../skins/period-skin";
import { ActionForm } from "../action-form";
import { cfgSpace, grantAllEntitlements } from "./_cfg-space";

const FULL_BAND = 3 as const;

/** `SkinDef.Component` is typed `ComponentType<SkinProps>` (types.ts) — a
 *  union that also admits a class component, which `renderIsland`'s own
 *  signature (a plain `(props: P) => ReactNode`) correctly refuses to
 *  accept without narrowing. `PeriodSkin` is, at runtime, a real function
 *  component (period-skin.tsx's own `export function PeriodSkin(...)`), so
 *  this is a type-level bridge only, not a behavioural cast. */
const PeriodSkinComponent = periodSkin.Component as (props: SkinProps) => ReactNode;

type MsgFn = (key: MessageKey, vars?: Record<string, string | number>) => string;
/** The exact fallback `useMsg()` resolves to outside a `<DictProvider>`
 *  (dict-provider.tsx:78-84) — real English lookup, not a stub, for the one
 *  test below that drives `buildAttributionRenderer` outside a rendered
 *  `PeriodSkin` (so there is no `useMsg()` call of its own to fall back). */
const msg: MsgFn = (key, vars) => tRuntime(messages, key, vars);

/** Mirrors skin-coverage.test.ts's own private `fullView` (that file exports
 *  nothing and is DO-NOT-TOUCH) — gates stripped, band/entitlement filtering
 *  only, so the cfg-space sweeps below measure the same "every action the cfg
 *  can ever declare" world the shared gate measures, never a smaller one. */
function fullView(spec: PadSpec, ctx: { band: typeof FULL_BAND; entitlements: Record<string, boolean> }): PadView {
  const resolved = allActionViews(spec, ctx);
  const byType = new Map(resolved.map((action) => [action.type, action]));
  const panels = spec.panels
    .map((panel) => ({
      labelKey: panel.labelKey,
      phase: panel.phase,
      layout: panel.layout,
      actions: panel.actions.map((action) => byType.get(action.type)).filter((a) => a !== undefined),
    }))
    .filter((panel) => panel.actions.length > 0);
  return { phase: "live", phases: ["pre", "live", "post"], panels };
}

function find(tree: ReactElement[], pred: (el: ReactElement) => boolean): ReactElement {
  const el = tree.find(pred);
  if (!el) throw new Error("element not found in rendered tree");
  return el;
}
function findAll(tree: ReactElement[], pred: (el: ReactElement) => boolean): ReactElement[] {
  return tree.filter(pred);
}
const isType = (type: unknown) => (el: ReactElement) => el.type === type;
const byPath = (tree: ReactElement[], path: string) =>
  find(tree, (el) => propsOf(el)["data-attribution-path"] === path);
const chipsOf = (group: ReactElement) => findAll(walk(propsOf(group).children as never), isType("button"));

const SPORTS = [
  { key: "hockey", module: hockey as AnySportModule },
  { key: "icehockey", module: icehockey as AnySportModule },
] as const;

describe.each(SPORTS)("period skin — $key coverage across the whole cfg space", ({ key, module }) => {
  it("places every declared action exactly once, never inventing one, for every cfg in the space", () => {
    const cfgs = cfgSpace(module);
    // Guards the sweep itself — a walk that silently stopped finding cfgs
    // would make the loop below vacuously green.
    expect(cfgs.length).toBeGreaterThan(1);

    for (const cfg of cfgs) {
      const spec = module.padSpec!(cfg);
      const entitlements = grantAllEntitlements(spec);
      const ctx = { band: FULL_BAND, entitlements };
      const view = fullView(spec, ctx);
      const expected = new Set(allActionViews(spec, ctx).map((a) => a.type));

      const layout = periodSkin.layout(view, { cfg, state: {}, summary: {}, band: FULL_BAND });
      const placed = layoutActionTypes(layout);

      expect(new Set(placed)).toEqual(expected);
      expect(placed.length).toBe(new Set(placed).size); // no duplicates
    }
  });

  // The prefix trap, proven directly: EVERY placed type for this sport's own
  // sweep must carry THIS sport's own prefix. If routing ever hardcoded the
  // other sport's string, this sport's own actions would silently vanish
  // (caught above already) but a hardcoded OTHER-sport literal slipping into
  // `placed` would not be — this assertion closes that gap specifically.
  it(`every placed action type carries the "${key}." prefix, never the other sport's`, () => {
    const cfg = cfgSpace(module)[0];
    const spec = module.padSpec!(cfg);
    const ctx = { band: FULL_BAND, entitlements: grantAllEntitlements(spec) };
    const view = fullView(spec, ctx);
    const layout = periodSkin.layout(view, { cfg, state: {}, summary: {}, band: FULL_BAND });
    const placed = layoutActionTypes(layout);
    expect(placed.length).toBeGreaterThan(0);
    for (const type of placed) expect(type.startsWith(`${key}.`)).toBe(true);
  });

  it("draws a non-empty score/period/clock header for every cfg in the space", () => {
    for (const cfg of cfgSpace(module)) {
      const spec = module.padSpec!(cfg);
      const ctx = { band: FULL_BAND, entitlements: grantAllEntitlements(spec) };
      const view = fullView(spec, ctx);
      const layout = periodSkin.layout(view, { cfg, state: {}, summary: {}, band: FULL_BAND });

      expect(layout.header).not.toBeNull();
      const fields = layout.header!.fields;
      expect(fields.length).toBeGreaterThan(0);
      const ids = fields.map((f) => f.id);
      expect(ids).toEqual(expect.arrayContaining(["score", "period", "clock"]));
      for (const field of fields) expect(field.value.length).toBeGreaterThan(0);
    }
  });

  it(`draws ${key}.goal at primary prominence and keeps period control reachable (never drawer)`, () => {
    const cfg = cfgSpace(module)[0];
    const spec = module.padSpec!(cfg);
    const ctx = { band: FULL_BAND, entitlements: grantAllEntitlements(spec) };
    const view = fullView(spec, ctx);
    const layout = periodSkin.layout(view, { cfg, state: {}, summary: {}, band: FULL_BAND });

    expect(layoutActionTypesAt(layout, "primary")).toContain(`${key}.goal`);

    const periodGroup = layout.groups.find((g) => g.actions.includes(`${key}.period.advance`));
    expect(periodGroup).toBeDefined();
    expect(periodGroup!.prominence).not.toBe("drawer");
  });

  it("groups suspension start+end together, at a reachable (non-drawer) prominence", () => {
    const cfg = cfgSpace(module)[0];
    const spec = module.padSpec!(cfg);
    const ctx = { band: FULL_BAND, entitlements: grantAllEntitlements(spec) };
    const view = fullView(spec, ctx);
    const layout = periodSkin.layout(view, { cfg, state: {}, summary: {}, band: FULL_BAND });

    const startGroup = layout.groups.find((g) => g.actions.includes(`${key}.suspension.start`));
    const endGroup = layout.groups.find((g) => g.actions.includes(`${key}.suspension.end`));
    expect(startGroup).toBeDefined();
    expect(startGroup).toBe(endGroup);
    expect(startGroup!.prominence).not.toBe("drawer");
  });
});

describe("period skin — the gated shootout panel, both directions (real buildPadView + evalPadGate)", () => {
  const PRESENT = [
    { key: "hockey", module: hockey as AnySportModule, variant: "fih-shootout" },
    { key: "icehockey", module: icehockey as AnySportModule, variant: "iihf" },
  ] as const;
  const ABSENT = [
    { key: "hockey", module: hockey as AnySportModule, variant: "fih-outdoor" },
    { key: "icehockey", module: icehockey as AnySportModule, variant: "recreational" },
  ] as const;

  it.each(PRESENT)(
    "$key ($variant): places the shootout attempt while state.phase is SHOOTOUT, and NOT while it isn't",
    ({ key, module, variant }) => {
      const variants = module.variants as Record<string, object>;
      const cfg = module.configSchema.parse({ ...variants[variant] });
      const spec = module.padSpec!(cfg);
      // cfg-level: this variant CAN reach a shootout at all.
      expect(spec.panels.some((p) => p.actions.some((a) => a.type === `${key}.shootout.attempt`))).toBe(true);
      const entitlements = grantAllEntitlements(spec);

      const liveCtx = { state: { phase: "P1" }, summary: {}, phase: "live" as const, band: FULL_BAND, entitlements };
      const liveView = buildPadView(spec, liveCtx);
      expect(liveView.panels.some((p) => p.actions.some((a) => a.type === `${key}.shootout.attempt`))).toBe(false);
      const liveLayout = periodSkin.layout(liveView, { cfg, state: liveCtx.state, summary: {}, band: FULL_BAND });
      expect(layoutActionTypes(liveLayout)).not.toContain(`${key}.shootout.attempt`);

      const soCtx = { state: { phase: "SHOOTOUT" }, summary: {}, phase: "live" as const, band: FULL_BAND, entitlements };
      const soView = buildPadView(spec, soCtx);
      expect(soView.panels.some((p) => p.actions.some((a) => a.type === `${key}.shootout.attempt`))).toBe(true);
      const soLayout = periodSkin.layout(soView, { cfg, state: soCtx.state, summary: {}, band: FULL_BAND });
      expect(layoutActionTypes(soLayout)).toContain(`${key}.shootout.attempt`);
      // Exactly once — never duplicated between direction switches.
      expect(layoutActionTypes(soLayout).filter((t) => t === `${key}.shootout.attempt`).length).toBe(1);
    },
  );

  it.each(ABSENT)(
    "$key ($variant): never places the shootout attempt — this cfg never declares the panel at all",
    ({ key, module, variant }) => {
      const variants = module.variants as Record<string, object>;
      const cfg = module.configSchema.parse({ ...variants[variant] });
      const spec = module.padSpec!(cfg);
      expect(spec.panels.some((p) => p.actions.some((a) => a.type === `${key}.shootout.attempt`))).toBe(false);
      const entitlements = grantAllEntitlements(spec);

      // Even a (nonsensical here) SHOOTOUT phase state cannot conjure a panel
      // padSpec(cfg) never declared — cfg absence, not gate falseness.
      const ctx = { state: { phase: "SHOOTOUT" }, summary: {}, phase: "live" as const, band: FULL_BAND, entitlements };
      const view = buildPadView(spec, ctx);
      const layout = periodSkin.layout(view, { cfg, state: ctx.state, summary: {}, band: FULL_BAND });
      expect(layoutActionTypes(layout)).not.toContain(`${key}.shootout.attempt`);
    },
  );
});

describe("period skin — dispatch refuses anything the current view does not declare", () => {
  it("passes a declared hockey action through, refuses an invented one, and refuses icehockey's same-shaped type", async () => {
    const cfg = hockey.configSchema.parse({});
    const spec = hockey.padSpec!(cfg);
    const entitlements = grantAllEntitlements(spec);
    const view = buildPadView(spec, { state: { phase: "P1" }, summary: {}, phase: "live", band: FULL_BAND, entitlements });

    const sent: string[] = [];
    const dispatch = createSkinDispatch(view, async (type) => void sent.push(type));

    await dispatch("hockey.goal", { by: "H", kind: "fg" });
    expect(sent).toEqual(["hockey.goal"]);

    await expect(dispatch("hockey.invented", {})).rejects.toThrow(/does not declare/);
    // The prefix trap at the dispatch boundary: a hockey-only view must
    // refuse icehockey's identically-shaped type just as loudly.
    await expect(dispatch("icehockey.goal", {})).rejects.toThrow(/does not declare/);
    expect(sent).toEqual(["hockey.goal"]);
  });
});

describe("period skin — header reflects REAL folded state, not just structural fallbacks", () => {
  it("hockey: score/period/clock read the real fold after a stamped goal", () => {
    const cfg = hockey.configSchema.parse({});
    const lineups = defaultLineupPair(hockey.positions);
    const events = [
      makeEnvelope(0, { type: "core.start", payload: {} }),
      makeEnvelope(1, {
        type: "hockey.goal",
        payload: { by: lineups.home.entrantId, kind: "fg", at: { period: "Q1", elapsed: 125 } },
      }),
    ];
    const state = foldClient(hockey, cfg, lineups, events);
    const summary = hockey.summary(state);
    const spec = hockey.padSpec!(cfg);
    const entitlements = grantAllEntitlements(spec);
    const view = buildPadView(spec, { state, summary, phase: "live", band: FULL_BAND, entitlements });
    const layout = periodSkin.layout(view, { cfg, state, summary, band: FULL_BAND });

    const byId = new Map(layout.header!.fields.map((f) => [f.id, f.value]));
    expect(byId.get("score")).not.toBe("0 – 0");
    expect(byId.get("score")).not.toBe("0 - 0");
    expect(byId.get("period")).toBe("Q1");
    expect(byId.get("clock")).toBe("2:05");
  });

  it("both sports: an unfolded state ({}) still yields non-empty fallback header text (the coverage sweep's own shape)", () => {
    for (const { module } of SPORTS) {
      const cfg = cfgSpace(module)[0];
      const spec = module.padSpec!(cfg);
      const layout = periodSkin.layout(fullView(spec, { band: FULL_BAND, entitlements: grantAllEntitlements(spec) }), {
        cfg,
        state: {},
        summary: {},
        band: FULL_BAND,
      });
      for (const field of layout.header!.fields) expect(field.value.trim().length).toBeGreaterThan(0);
    }
  });
});

describe("period skin — Component wiring (renderIsland, no DOM): every placed action reaches an ActionForm", () => {
  it.each(SPORTS)("$key: header text renders and one ActionForm exists per placed action type", ({ key, module }) => {
    const cfg = module.configSchema.parse({});
    const lineups = defaultLineupPair(module.positions);
    const events = [
      makeEnvelope(0, { type: "core.start", payload: {} }),
      makeEnvelope(1, { type: `${key}.goal`, payload: { by: lineups.home.entrantId, kind: "fg" } }),
    ];
    const state = foldClient(module, cfg, lineups, events);
    const summary = module.summary(state);
    const spec = module.padSpec!(cfg);
    const entitlements = grantAllEntitlements(spec);
    const view = buildPadView(spec, { state, summary, phase: "live", band: FULL_BAND, entitlements });
    const layout = periodSkin.layout(view, { cfg, state, summary, band: FULL_BAND });

    const island = renderIsland(PeriodSkinComponent, {
      view,
      spec,
      ctx: { cfg, state, summary, band: FULL_BAND },
      layout,
      dispatch: async () => {},
      queueDepth: 0,
      offline: false,
      submittingType: null,
    });

    const tree = island.tree();
    const forms = findAll(tree, isType(ActionForm));
    const formTypes = forms.map((el) => (propsOf(el).action as { type: string }).type).sort();
    expect(formTypes).toEqual([...layoutActionTypes(layout)].sort());

    const text = island.text();
    const scoreValue = layout.header!.fields.find((f) => f.id === "score")!.value;
    expect(text).toContain(scoreValue);
  });

  it("offline queue status is surfaced somewhere in the header chrome", () => {
    const cfg = hockey.configSchema.parse({});
    const lineups = defaultLineupPair(hockey.positions);
    const state = foldClient(hockey, cfg, lineups, [makeEnvelope(0, { type: "core.start", payload: {} })]);
    const summary = hockey.summary(state);
    const spec = hockey.padSpec!(cfg);
    const entitlements = grantAllEntitlements(spec);
    const view = buildPadView(spec, { state, summary, phase: "live", band: FULL_BAND, entitlements });
    const layout = periodSkin.layout(view, { cfg, state, summary, band: FULL_BAND });

    const island = renderIsland(PeriodSkinComponent, {
      view,
      spec,
      ctx: { cfg, state, summary, band: FULL_BAND },
      layout,
      dispatch: async () => {},
      queueDepth: 0,
      offline: true,
      submittingType: null,
    });
    expect(island.text()).toContain(msg("scorepad.queue.offline"));
  });
});

describe("period skin — the suspension flow is a real, fillable form (not a raw dump)", () => {
  it("hockey: tap -> class/reason/minutes + side/person/servedBy chips (real folded squad) -> confirm submits ONE complete payload", () => {
    const cfg = hockey.configSchema.parse({});
    const lineups = defaultLineupPair(hockey.positions);
    const H = lineups.home.entrantId;
    const OFFENDER = "H-p2";
    const events = [
      makeEnvelope(0, { type: "core.start", payload: {} }),
      // One core.lineup.* event is enough for squad-state.ts's adoption rule
      // to populate state.squads with the FULL team sheet — proven pattern,
      // attribution-picker.test.tsx's own "keeper" fixture.
      makeEnvelope(1, { type: "core.lineup.position", payload: { side: H, personId: OFFENDER, positionKey: "FW" } }),
    ];
    const state = foldClient(hockey, cfg, lineups, events);
    const summary = hockey.summary(state);
    const spec = hockey.padSpec!(cfg);
    const entitlements = grantAllEntitlements(spec);
    const view = buildPadView(spec, { state, summary, phase: "live", band: FULL_BAND, entitlements });
    const action = actionByType(view, "hockey.suspension.start");
    expect(action).not.toBeNull();

    const renderAttribution = buildAttributionRenderer({ cfg, state, summary, band: FULL_BAND }, msg);

    let submitted: Record<string, unknown> | null = null;
    const island = renderIsland(ActionForm, {
      action: action!,
      onSubmit: (payload: Record<string, unknown>) => (submitted = payload),
      renderAttribution,
    });

    // Tap -> expands (has fields, so no immediate submit).
    (propsOf(find(island.tree(), isType("button"))).onClick as () => void)();
    expect(submitted).toBeNull();

    // class (1st select), reason (2nd select), minutes (number input).
    let tree = island.tree();
    const classSelect = findAll(tree, isType("select"))[0]!;
    (propsOf(classSelect).onChange as (e: unknown) => void)({ target: { value: "minor" } });

    tree = island.tree();
    const reasonSelect = findAll(tree, isType("select"))[1]!;
    (propsOf(reasonSelect).onChange as (e: unknown) => void)({ target: { value: "tripping" } });

    tree = island.tree();
    const minutesInput = find(tree, (el) => el.type === "input" && propsOf(el).type === "number");
    (propsOf(minutesInput).onChange as (e: unknown) => void)({ target: { value: "2" } });

    // Attribution: by (side), person (offender), servedBy (someone else) —
    // three independent groups, each addressable by its own declared path.
    tree = island.tree();
    const byChip = chipsOf(byPath(tree, "by"))[0]!; // "home"
    (propsOf(byChip).onClick as () => void)();

    tree = island.tree();
    const personChips = chipsOf(byPath(tree, "person"));
    const offenderChip = find(personChips, (c) => propsOf(c)["data-value"] === OFFENDER);
    (propsOf(offenderChip).onClick as () => void)();

    tree = island.tree();
    const servedByChips = chipsOf(byPath(tree, "servedBy"));
    const serverChip = find(servedByChips, (c) => propsOf(c)["data-value"] !== OFFENDER);
    const server = propsOf(serverChip)["data-value"];
    (propsOf(serverChip).onClick as () => void)();

    tree = island.tree();
    const confirmBtn = find(tree, (el) => propsOf(el)["data-role"] === "confirm");
    expect(propsOf(confirmBtn).disabled).toBe(false);
    (propsOf(confirmBtn).onClick as () => void)();

    expect(submitted).not.toBeNull();
    expect(submitted).toMatchObject({ class: "minor", reason: "tripping", minutes: 2, by: H, person: OFFENDER, servedBy: server });
  });

  it("icehockey: without a folded squad, person attribution degrades to a captioned text input (never a silent no-op) and still submits", () => {
    const cfg = icehockey.configSchema.parse({});
    const lineups = defaultLineupPair(icehockey.positions);
    // No core.lineup.* event — state.squads stays absent (kernel's own
    // documented rule: ABSENT until it says something the team sheet does
    // not), so this exercises the DEGRADE path deliberately.
    const state = foldClient(icehockey, cfg, lineups, [makeEnvelope(0, { type: "core.start", payload: {} })]);
    const summary = icehockey.summary(state);
    const spec = icehockey.padSpec!(cfg);
    const entitlements = grantAllEntitlements(spec);
    const view = buildPadView(spec, { state, summary, phase: "live", band: FULL_BAND, entitlements });
    const action = actionByType(view, "icehockey.suspension.start");
    expect(action).not.toBeNull();

    const renderAttribution = buildAttributionRenderer({ cfg, state, summary, band: FULL_BAND }, msg);
    let submitted: Record<string, unknown> | null = null;
    const island = renderIsland(ActionForm, {
      action: action!,
      onSubmit: (payload: Record<string, unknown>) => (submitted = payload),
      renderAttribution,
    });

    (propsOf(find(island.tree(), isType("button"))).onClick as () => void)();

    let tree = island.tree();
    (propsOf(findAll(tree, isType("select"))[0]!).onChange as (e: unknown) => void)({ target: { value: "minor" } });
    tree = island.tree();
    (propsOf(findAll(tree, isType("select"))[1]!).onChange as (e: unknown) => void)({ target: { value: "tripping" } });
    tree = island.tree();
    (propsOf(find(tree, (el) => el.type === "input" && propsOf(el).type === "number")).onChange as (e: unknown) => void)({
      target: { value: "2" },
    });

    // No roster known -> "person"/"servedBy" are plain text inputs, still
    // captioned (never silently dropped from the form).
    tree = island.tree();
    const personGroup = byPath(tree, "person");
    expect(textOf(personGroup).length).toBeGreaterThan(0); // a real caption, not blank
    const personTextInput = find(walk(propsOf(personGroup).children as never), (el) => el.type === "input");
    (propsOf(personTextInput).onChange as (e: unknown) => void)({ target: { value: "12" } });

    tree = island.tree();
    const servedByGroup = byPath(tree, "servedBy");
    const servedByTextInput = find(walk(propsOf(servedByGroup).children as never), (el) => el.type === "input");
    (propsOf(servedByTextInput).onChange as (e: unknown) => void)({ target: { value: "7" } });

    // "by" (side) still works via chips — entrants are ALWAYS on PeriodState,
    // independent of whether a squad has folded.
    tree = island.tree();
    const byChip = chipsOf(byPath(tree, "by"))[0]!;
    (propsOf(byChip).onClick as () => void)();

    tree = island.tree();
    const confirmBtn = find(tree, (el) => propsOf(el)["data-role"] === "confirm");
    expect(propsOf(confirmBtn).disabled).toBe(false);
    (propsOf(confirmBtn).onClick as () => void)();

    expect(submitted).toMatchObject({ class: "minor", reason: "tripping", minutes: 2, person: "12", servedBy: "7" });
  });
});
