"""BUILD model acceptance tests.

The board under test is the production shape that motivated the whole
investigation (37 fixtures, 5 courts, 26 days x 5 courts x 64 ticks) and it is
generated by `cpsat_bench_boards.production_board()` — the SAME generator the
bench sweep drives, deliberately shared rather than copied, so the two cannot
drift apart (see the prompt's Step 2b).

These exercise the real solver end to end. Nothing here is mocked: a green run
means CP-SAT actually proved optimality on the real board inside the budget.
"""

import pytest

from cp_sat.model import DAY_MS, MIN_MS, build_model, solve


def _production_board():
    # Module name follows the file the prompt's Step 2b names
    # (bench/cpsat_bench_boards.py) and its siblings cpsat_bench.py /
    # cpsat_repair_bench.py. bench/ reaches sys.path via `pythonpath` in
    # pyproject.toml — it is a script directory, not an installed package.
    from cpsat_bench_boards import production_board

    return production_board()


def test_production_board_solves_optimal_under_budget():
    fixtures, courts, grid_slots, step_minutes, constraints, existing, deps = _production_board()
    model = build_model(fixtures, courts, grid_slots, step_minutes, constraints, existing, deps)
    outcome = solve(model, wall_seconds=8.0)
    assert outcome.status == "OPTIMAL"
    assert 35 <= len(outcome.assignments) <= 37
    assert outcome.elapsed_ms < 8000


def test_no_court_double_booking():
    fixtures, courts, grid_slots, step_minutes, constraints, existing, deps = _production_board()
    model = build_model(fixtures, courts, grid_slots, step_minutes, constraints, existing, deps)
    outcome = solve(model, wall_seconds=8.0)
    seen = {}
    for fixture_id, court, start_ms in outcome.assignments:
        key = (court, start_ms)
        assert key not in seen, f"double-booked {key}"
        seen[key] = fixture_id


def test_assignments_satisfy_every_stated_constraint():
    """Re-verify the solver's answer against each constraint family, in plain
    Python, the way `validateAssignments` does on the TS side.

    The two tests above leave most of the model untestable: deleting the
    participant-rest `AddNoOverlap`, the order-dependency inequality or the
    per-division day cap leaves both of them green (measured — the rest mutant
    survived them). A solver whose constraint families can be removed without
    a test noticing is the failure mode this repo has been bitten by before,
    so each family gets an assertion that fails without it.
    """
    fixtures, courts, grid_slots, step_minutes, constraints, existing, deps = _production_board()
    model = build_model(fixtures, courts, grid_slots, step_minutes, constraints, existing, deps)
    outcome = solve(model, wall_seconds=8.0)
    assert outcome.assignments, "nothing placed — the rest of this test would be vacuous"

    dur_ms = constraints["match_minutes"] * MIN_MS
    gap_ms = constraints["gap_minutes"] * MIN_MS
    rest_by_division = constraints["rest_by_division"]
    day_cap_by_division = constraints["day_cap_by_division"]

    entrants_of = {fid: ents for fid, ents, _div in fixtures}
    division_of = {fid: div for fid, _ents, div in fixtures}
    placed = {fid: (court, start) for fid, court, start in outcome.assignments}
    legal_court_starts = set(grid_slots)

    # every placement lands on a tick THAT COURT actually offers
    for fid, (court, start) in placed.items():
        assert court in courts, f"{fid} placed on unknown court {court}"
        assert (court, start) in legal_court_starts, f"{fid} placed at {start} on {court}, not a legal slot"

    # court turnaround (match+gap), movable vs movable AND vs immovable rows
    occupancy = [(court, start, fid) for fid, (court, start) in placed.items()]
    occupancy += [(court, start, f"existing:{eid}") for eid, court, start in existing]
    for a in range(len(occupancy)):
        for b in range(a + 1, len(occupancy)):
            court_a, start_a, name_a = occupancy[a]
            court_b, start_b, name_b = occupancy[b]
            if court_a != court_b:
                continue
            assert abs(start_a - start_b) >= dur_ms + gap_ms, (
                f"court turnaround violated on {court_a}: {name_a}@{start_a} vs {name_b}@{start_b}"
            )

    # participant rest: an entrant's two matches are separated by match+rest
    by_entrant = {}
    for fid, (_court, start) in placed.items():
        for entrant in entrants_of[fid]:
            by_entrant.setdefault(entrant, []).append((start, fid))
    for entrant, rows in by_entrant.items():
        rows.sort()
        for a in range(len(rows)):
            for b in range(a + 1, len(rows)):
                (start_a, fid_a), (start_b, fid_b) = rows[a], rows[b]
                need = dur_ms + rest_by_division[division_of[fid_a]] * MIN_MS
                assert start_b - start_a >= need, (
                    f"rest violated for {entrant}: {fid_a}@{start_a} vs {fid_b}@{start_b}, need {need}ms"
                )

    # order dependencies: `after` starts no earlier than `before` + match + its own rest
    checked_deps = 0
    for before_id, after_id in deps:
        if before_id not in placed or after_id not in placed:
            continue
        need = dur_ms + rest_by_division[division_of[after_id]] * MIN_MS
        assert placed[after_id][1] >= placed[before_id][1] + need, (
            f"dependency violated: {after_id} must start >= {before_id} + {need}ms"
        )
        checked_deps += 1
    assert checked_deps == len(deps), "a dependency pair went unplaced — that arm would be vacuous"

    # per-division day cap
    per_division_day = {}
    for fid, (_court, start) in placed.items():
        key = (division_of[fid], start // DAY_MS)
        per_division_day[key] = per_division_day.get(key, 0) + 1
    for (division, day), count in per_division_day.items():
        assert count <= day_cap_by_division[division], (
            f"day cap violated: division {division} day {day} has {count} > {day_cap_by_division[division]}"
        )


# --- degenerate constraint values must fail loudly, not solve quietly -------
#
# proto3 scalars are non-optional: an unset `max_fixtures_per_day` or
# `match_minutes` arrives as 0, indistinguishable from a deliberate 0. Both
# used to be accepted and produce a confidently WRONG board reported as
# OPTIMAL — a whole division silently dropped, or every match given zero
# length. Measured before the guards existed:
#   day_cap {"d1": 0, "d2": 1}  -> OPTIMAL, placed 18/37, zero d1 fixtures
#   match_minutes 0             -> OPTIMAL, 37 zero-length matches stacked
# These are domain-layer guards. `cp_sat.schema` (Prompt 04) still owes the
# wire-boundary validation; this is defence in depth, not a replacement.


def test_rejects_zero_day_cap():
    fixtures, courts, grid_slots, step_minutes, constraints, existing, deps = _production_board()
    constraints = {**constraints, "day_cap_by_division": {"d1": 0, "d2": 1}}
    with pytest.raises(ValueError, match="max_fixtures_per_day"):
        build_model(fixtures, courts, grid_slots, step_minutes, constraints, existing, deps)


def test_rejects_negative_day_cap():
    fixtures, courts, grid_slots, step_minutes, constraints, existing, deps = _production_board()
    constraints = {**constraints, "day_cap_by_division": {"d1": -1, "d2": 1}}
    with pytest.raises(ValueError, match="max_fixtures_per_day"):
        build_model(fixtures, courts, grid_slots, step_minutes, constraints, existing, deps)


def test_absent_day_cap_rule_means_no_cap():
    """A division simply MISSING from the dict is uncapped — that is the
    contract, and the guard above must not break it."""
    fixtures, courts, grid_slots, step_minutes, constraints, existing, deps = _production_board()
    constraints = {**constraints, "day_cap_by_division": {}}
    model = build_model(fixtures, courts, grid_slots, step_minutes, constraints, existing, deps)
    outcome = solve(model, wall_seconds=8.0)
    assert outcome.status == "OPTIMAL"
    assert len(outcome.assignments) == len(fixtures)


def test_rejects_zero_match_minutes():
    fixtures, courts, grid_slots, step_minutes, constraints, existing, deps = _production_board()
    constraints = {**constraints, "match_minutes": 0}
    with pytest.raises(ValueError, match="match_minutes"):
        build_model(fixtures, courts, grid_slots, step_minutes, constraints, existing, deps)


def test_rejects_missing_match_minutes():
    fixtures, courts, grid_slots, step_minutes, constraints, existing, deps = _production_board()
    constraints = {k: v for k, v in constraints.items() if k != "match_minutes"}
    with pytest.raises(ValueError, match="match_minutes"):
        build_model(fixtures, courts, grid_slots, step_minutes, constraints, existing, deps)
