// Spectator surface W2, Task 3 — the leaders boards.
//
// Everything here is PURE: no database, no `sql`, no network. That is a design
// choice, not a convenience — the consent fold and the ranking are where this
// task's rulings live, so they are deliberately kept out of the DB shell in
// `public-leaders.ts` (same discipline as `CareerSnapshotRow` in
// server/player-stats.ts: "a thin DB-shaped input so this file stays free of
// any postgres/sql import, pure, unit-testable with fabricated rows").
//
// Every expected stat key is DERIVED from the engine's own declarations rather
// than typed in here — a table copied from the implementation cannot witness a
// regression in the implementation. `resolveLatestModule` boots the shared
// registry itself (server/engine-db/registry.ts bootRegistry), so this file
// deliberately does NOT call `registerBuiltins` at module scope: a second
// registration throws MODULE_DUPLICATE, and a module-scope throw collects zero
// tests while the run still reads green.
import { describe, expect, it } from "vitest";
import type { PlayerStatsModel } from "@seazn/engine/stats";
import { resolveLatestModule } from "@/server/engine-db";
import { labelPlayerStats } from "@/server/player-stats";
import type { MsgFn } from "@/lib/scoring-vocab";
import uiEn from "@/dictionaries/en/ui.json";
import {
  LEADER_LIMIT,
  LEADER_SPECS,
  buildLeaderBoards,
  declaredStatKeys,
  declaredStats,
  specsFor,
  toLeaderInputRows,
  type LeaderDivision,
  type LeaderInputRow,
  type LeaderSnapshotRow,
} from "../leaders";

const en: MsgFn = (k) => (uiEn as Record<string, string>)[k] ?? k;
const modelFor = (sportKey: string) => resolveLatestModule(sportKey).playerStats;

const cricket: LeaderDivision = {
  id: "d1",
  slug: "t8",
  name: "Men's T8",
  sportKey: "cricket",
  moduleVersion: resolveLatestModule("cricket").version,
};

const row = (
  personId: string,
  stats: Record<string, number>,
  over: Partial<LeaderInputRow> = {},
): LeaderInputRow => ({
  divisionId: "d1",
  personId,
  name: personId.toUpperCase(),
  masked: false,
  publicProfile: true,
  entrantName: "Blazers",
  badgeUrl: null,
  stats,
  ...over,
});

const args = (rows: LeaderInputRow[]) => ({
  divisions: [cricket],
  rows,
  modelFor: (d: LeaderDivision) => modelFor(d.sportKey),
  label: (spec: { key: string; engineLabel: string | undefined }, d: LeaderDivision) =>
    `${d.sportKey}:${spec.key}`,
  personHref: (personId: string) => `/shared/o/c/players/${personId}`,
});

// ---------------------------------------------------------------------------
// LEADER_SPECS — pinned against the engine, never against a table typed here
// ---------------------------------------------------------------------------

describe("LEADER_SPECS is declared by the engine, not by this app", () => {
  // Stated FIRST, because every guard below is generated by looping over the
  // table: an EMPTY table runs zero of them and satisfies the whole describe
  // vacuously, which is exactly how a contains-ladder ships green while
  // asserting nothing.
  it("the table is not empty — the guards below are generated from it", () => {
    expect(Object.keys(LEADER_SPECS).length).toBeGreaterThan(0);
  });

  for (const [sportKey, keys] of Object.entries(LEADER_SPECS)) {
    it(`${sportKey}: every leader key is declared by the module's playerStats`, () => {
      const declared = declaredStatKeys(modelFor(sportKey));
      expect(keys.length).toBeGreaterThan(0);
      for (const key of keys) expect(declared.has(key), `${sportKey}.${key}`).toBe(true);
    });

    // Ruling P9 — W2 ships COUNT boards only. A ratio (strike rate, economy)
    // is a `derived[]` entry, and ranking one needs a minimum-participation
    // floor the engine declares nowhere (`PlayerStatsModel` has metrics,
    // derived, awards, folded and NO floor). This guard is what stops a ratio
    // key being added to the table above without that engine declaration.
    it(`${sportKey}: every leader key is a counted metric, never a derived ratio`, () => {
      const model = modelFor(sportKey);
      const metricKeys = new Set((model?.metrics ?? []).map((m) => m.key));
      const derivedKeys = new Set((model?.derived ?? []).map((d) => d.key));
      for (const key of keys) {
        expect(metricKeys.has(key), `${sportKey}.${key} is a metrics[] entry`).toBe(true);
        expect(derivedKeys.has(key), `${sportKey}.${key} is not a derived ratio`).toBe(false);
      }
    });
  }

  it("every sport named in the table resolves to a registered module", () => {
    for (const sportKey of Object.keys(LEADER_SPECS)) {
      expect(() => resolveLatestModule(sportKey), sportKey).not.toThrow();
    }
  });
});

describe("declaredStats walks the same declarations the shipped labeller walks", () => {
  // Drift guard: `declaredStats` here and `labelFromModel` in
  // server/player-stats.ts each walk metrics → derived → awards(_awards) →
  // folded, first declaration wins. They are separate functions (the labeller
  // also translates and drops zeros, so it cannot be reused verbatim), so one
  // gaining or losing a list must not silently diverge from the other.
  //
  // The stats blob fed to the labeller is built from an INDEPENDENT walk of
  // the model below, never from `declaredStats` itself. Deriving it from the
  // function under test made this comparison tautological: the labeller drops
  // zero-valued rows, so a key `declaredStats` had stopped emitting was also
  // absent from the blob, dropped by the labeller too, and the two lists still
  // matched. Mutants that deleted the `derived` and `folded` lines both
  // survived that version of this test.
  const everyDeclaredKey = (model: PlayerStatsModel | undefined): string[] => [
    ...(model?.metrics ?? []).map((m) => m.key),
    ...(model?.derived ?? []).map((d) => d.key),
    ...(model?.awards ?? []).map((a) => `${a.key}_awards`),
    ...(model?.folded?.keys ?? []).map((f) => f.key),
  ];

  for (const sportKey of ["cricket", "football", "hockey", "icehockey", "tennis"]) {
    it(`${sportKey}: same keys, same order, as labelPlayerStats`, () => {
      const sportModule = resolveLatestModule(sportKey);
      const stats = Object.fromEntries(
        everyDeclaredKey(sportModule.playerStats).map((k) => [k, 1]),
      );
      const theirs = labelPlayerStats(sportKey, sportModule.version, stats, en).map((s) => s.key);
      const mine = declaredStats(sportModule.playerStats).map((s) => s.key);
      expect(mine).toEqual(theirs);
      expect(mine.length).toBeGreaterThan(0);
    });
  }

  it("an unknown / retired module contributes no declared keys", () => {
    expect(declaredStats(undefined)).toEqual([]);
    expect(declaredStatKeys(undefined).size).toBe(0);
  });

  it("a key declared twice appears once, keeping its FIRST declared label", () => {
    const twice = declaredStats({
      metrics: [
        { key: "games", label: "Games", from: "x", agg: "count" },
        { key: "games", label: "Appearances", from: "y", agg: "count" },
      ],
    });
    expect(twice).toEqual([{ key: "games", label: "Games" }]);
  });

  it("awards land under the _awards suffix the snapshot actually stores", () => {
    const stats = declaredStats({
      metrics: [],
      awards: [{ key: "motm", label: "Player of the Match" }],
    });
    expect(stats).toEqual([{ key: "motm_awards", label: "Player of the Match" }]);
  });
});

describe("specsFor", () => {
  it("EMPTY: an unknown sport with no model yields no specs", () => {
    expect(specsFor("kabaddi", undefined)).toEqual([]);
  });

  it("a listed sport uses its declared table, in table order", () => {
    const keys = specsFor("cricket", modelFor("cricket")).map((s) => s.key);
    expect(keys).toEqual([...LEADER_SPECS.cricket!]);
  });

  it("carries the module's OWN English label for each key, for the caller to translate", () => {
    const model = modelFor("football");
    const goals = specsFor("football", model).find((s) => s.key === "goals");
    const declared = declaredStats(model).find((s) => s.key === "goals");
    expect(goals?.engineLabel).toBe(declared?.label);
    expect(goals?.engineLabel).toBeTruthy();
  });

  it("a sport with no table falls back to the module's first two declared metrics, in declaration order", () => {
    const model = modelFor("tennis");
    expect(LEADER_SPECS.tennis).toBeUndefined();
    const fallback = specsFor("tennis", model);
    const expected = declaredStats(model)
      .filter((s) => (model?.metrics ?? []).some((m) => m.key === s.key))
      .slice(0, 2);
    expect(fallback.map((s) => s.key)).toEqual(expected.map((s) => s.key));
    expect(fallback.map((s) => s.engineLabel)).toEqual(expected.map((s) => s.label));
  });

  it("the fallback dedupes a metric declared under several payload fields", () => {
    const specs = specsFor("unlisted", {
      metrics: [
        { key: "games", label: "Games", from: "a", field: "homePerson", agg: "count" },
        { key: "games", label: "Games", from: "a", field: "awayPerson", agg: "count" },
        { key: "wins", label: "Wins", from: "b", agg: "count" },
      ],
    });
    expect(specs.map((s) => s.key)).toEqual(["games", "wins"]);
  });
});

// ---------------------------------------------------------------------------
// buildLeaderBoards — the empty case first (R4/R9)
// ---------------------------------------------------------------------------

describe("buildLeaderBoards", () => {
  it("EMPTY: no divisions and no rows → no boards", () => {
    expect(buildLeaderBoards({ ...args([]), divisions: [] })).toEqual([]);
  });

  it("EMPTY: a division with no rows at all → no boards (no Stats tab)", () => {
    expect(buildLeaderBoards(args([]))).toEqual([]);
  });

  it("EMPTY: rows that belong to another division do not build this one's boards", () => {
    expect(buildLeaderBoards(args([row("p1", { runs: 50 }, { divisionId: "elsewhere" })]))).toEqual(
      [],
    );
  });

  it("a board whose metric nobody has scored is dropped, and a zero never makes a row", () => {
    const boards = buildLeaderBoards(args([row("p1", { runs: 12, wickets: 0 })]));
    expect(boards.map((b) => b.key)).toEqual(["runs"]);
    expect(boards[0]!.rows.map((r) => r.person.personId)).toEqual(["p1"]);
  });

  it("a missing key and an explicit zero are treated alike — neither ranks", () => {
    const boards = buildLeaderBoards(args([row("has", { runs: 3 }), row("zero", { runs: 0 })]));
    expect(boards[0]!.rows.map((r) => r.person.personId)).toEqual(["has"]);
  });

  it("ORDER-DIFFERENTIAL: value DESC then name ASC, capped at the limit", () => {
    // Every rung differs from what the wrong order would produce: "bob" (41)
    // outranks the tie, the tie breaks amy-before-zed on NAME (not insertion
    // order, which is zed first), and the cap drops the two smallest — so a
    // value-ASC, a name-DESC and an unsorted implementation each fail here.
    const boards = buildLeaderBoards({
      ...args([
        row("zed", { runs: 30 }),
        row("amy", { runs: 30 }),
        row("bob", { runs: 41 }),
        row("c", { runs: 1 }),
        row("d", { runs: 2 }),
        row("e", { runs: 3 }),
      ]),
      limit: 5,
    });
    expect(boards[0]!.rows.map((r) => r.person.personId)).toEqual(["bob", "amy", "zed", "e", "d"]);
    expect(boards[0]!.rows.map((r) => r.value)).toEqual(["41", "30", "30", "3", "2"]);
  });

  it("ties break on the DISPLAYED name, so a masked name sorts where it renders", () => {
    const boards = buildLeaderBoards(
      args([
        row("p1", { runs: 7 }, { name: "Zara Ahmed" }),
        row("p2", { runs: 7 }, { name: "Arun K.", masked: true }),
      ]),
    );
    expect(boards[0]!.rows.map((r) => r.person.name)).toEqual(["Arun K.", "Zara Ahmed"]);
  });

  it("defaults to LEADER_LIMIT when the caller names no limit", () => {
    const many = Array.from({ length: LEADER_LIMIT + 3 }, (_, i) =>
      row(`p${i}`, { runs: 100 - i }),
    );
    expect(buildLeaderBoards(args(many))[0]!.rows).toHaveLength(LEADER_LIMIT);
  });

  it("CONSENT: a masked person keeps the masked label and gets no player-page link", () => {
    const boards = buildLeaderBoards(
      args([
        row("p1", { runs: 9 }, { name: "A. B.", masked: true, publicProfile: false }),
        row("p2", { runs: 8 }),
      ]),
    );
    const [masked, open] = boards[0]!.rows;
    expect(masked!.person).toEqual({ personId: "p1", name: "A. B.", masked: true });
    expect(masked!.personHref).toBeNull();
    // Positive pair — the absence above is a decision, not a broken link builder.
    expect(open!.personHref).toBe("/shared/o/c/players/p2");
    expect(open!.person.masked).toBe(false);
  });

  it("CONSENT: a masked row is RANKED, never dropped", () => {
    const boards = buildLeaderBoards(
      args([
        row("top", { runs: 99 }, { name: "M. K.", masked: true, publicProfile: false }),
        row("p2", { runs: 8 }),
      ]),
    );
    expect(boards[0]!.rows).toHaveLength(2);
    expect(boards[0]!.rows[0]!.person.personId).toBe("top");
  });

  it("CONSENT: an unmasked person with no public profile gets no link either", () => {
    // The other half of the `publicProfile && !masked` pair: without this
    // case, an implementation that only checked `!masked` would link to a
    // player page that does not exist.
    const boards = buildLeaderBoards(
      args([row("p1", { runs: 5 }, { masked: false, publicProfile: false })]),
    );
    expect(boards[0]!.rows[0]!.personHref).toBeNull();
    expect(boards[0]!.rows[0]!.person.masked).toBe(false);
  });

  it("CONSENT: a person masked by DIVISION policy gets no link even with a public profile", () => {
    // A youth division masks names for safeguarding while the person may still
    // carry public_name consent (so they ARE in public_players_v). The player
    // page renders the UNMASKED name, so linking there would undo the division
    // policy — `publicProfile` alone must never be enough.
    const boards = buildLeaderBoards(
      args([row("p1", { runs: 5 }, { name: "Sam W.", masked: true, publicProfile: true })]),
    );
    expect(boards[0]!.rows[0]!.personHref).toBeNull();
  });

  it("carries the entrant name and badge through unchanged", () => {
    const boards = buildLeaderBoards(
      args([row("p1", { runs: 5 }, { entrantName: "Blazers", badgeUrl: "https://x/b.png" })]),
    );
    expect(boards[0]!.rows[0]).toMatchObject({
      entrantName: "Blazers",
      badgeUrl: "https://x/b.png",
    });
  });

  it("a person with no entrant still ranks, with a null entrant name", () => {
    const boards = buildLeaderBoards(args([row("p1", { runs: 5 }, { entrantName: null })]));
    expect(boards[0]!.rows[0]!.entrantName).toBeNull();
  });

  it("boards are emitted per division in DIVISION order, spec order within a division", () => {
    const second: LeaderDivision = { ...cricket, id: "d2", slug: "w8", name: "Women's T8" };
    const boards = buildLeaderBoards({
      ...args([row("p1", { runs: 5, wickets: 2 }), row("p9", { runs: 7 }, { divisionId: "d2" })]),
      divisions: [cricket, second],
    });
    expect(boards.map((b) => `${b.divisionId}:${b.key}`)).toEqual([
      "d1:runs",
      "d1:wickets",
      "d2:runs",
    ]);
    // Reversing the divisions reverses the boards — the emission really does
    // follow the caller's order rather than the rows' own.
    const flipped = buildLeaderBoards({
      ...args([row("p1", { runs: 5 }), row("p9", { runs: 7 }, { divisionId: "d2" })]),
      divisions: [second, cricket],
    });
    expect(flipped.map((b) => b.divisionId)).toEqual(["d2", "d1"]);
  });

  it("each board carries its division's identity and the caller's label", () => {
    const boards = buildLeaderBoards(args([row("p1", { runs: 5 })]));
    expect(boards[0]).toMatchObject({
      divisionId: "d1",
      divisionSlug: "t8",
      divisionName: "Men's T8",
      sportKey: "cricket",
      key: "runs",
      label: "cricket:runs",
    });
  });

  it("the label callback receives the spec's engine label, so the caller can fall back to it", () => {
    const seen: (string | undefined)[] = [];
    buildLeaderBoards({
      ...args([row("p1", { runs: 5 })]),
      label: (spec) => {
        seen.push(spec.engineLabel);
        return spec.key;
      },
    });
    const declared = declaredStats(modelFor("cricket")).find((s) => s.key === "runs");
    expect(seen).toEqual([declared?.label]);
  });
});

// ---------------------------------------------------------------------------
// toLeaderInputRows — the pure consent fold the DB shell delegates to
// ---------------------------------------------------------------------------

const snapshot = (over: Partial<LeaderSnapshotRow> = {}): LeaderSnapshotRow => ({
  division_id: "d1",
  person_id: "p1",
  full_name: "Arun Kumar",
  consent: { public_name: true },
  stats: { runs: 34 },
  entrant_id: "e1",
  entrant_name: "Blazers",
  badge_url: null,
  team_logo_path: null,
  public_profile: true,
  ...over,
});

const OPEN_DIVISION = [{ id: "d1", youth: false, player_name_display: null }];

describe("toLeaderInputRows", () => {
  it("EMPTY: no snapshot rows → no leader rows", () => {
    expect(toLeaderInputRows([], OPEN_DIVISION, new Map())).toEqual([]);
  });

  it("EMPTY: a row for a division the caller did not ask about is dropped", () => {
    const out = toLeaderInputRows([snapshot({ division_id: "other" })], OPEN_DIVISION, new Map());
    expect(out).toEqual([]);
  });

  it("an unmasked person keeps their full name and is not flagged masked", () => {
    const [out] = toLeaderInputRows([snapshot()], OPEN_DIVISION, new Map([["e1", "Blazers"]]));
    expect(out).toMatchObject({
      divisionId: "d1",
      personId: "p1",
      name: "Arun Kumar",
      masked: false,
      publicProfile: true,
      entrantName: "Blazers",
      stats: { runs: 34 },
    });
  });

  it("CONSENT: an explicit public_name:false masks the name — never blanks it", () => {
    const [out] = toLeaderInputRows(
      [snapshot({ consent: { public_name: false } })],
      OPEN_DIVISION,
      new Map(),
    );
    expect(out!.masked).toBe(true);
    expect(out!.name).not.toBe("");
    expect(out!.name).not.toBe("Arun Kumar");
    expect(out!.name).toBe("Arun K.");
  });

  it("CONSENT: absent consent is NOT an opt-out — an unrecorded person stays unmasked", () => {
    // RS007 owner ruling 5: registering is consent to a public name. Treating
    // null as an opt-out would mask every not-yet-claimed roster row.
    for (const consent of [null, {}]) {
      const [out] = toLeaderInputRows([snapshot({ consent })], OPEN_DIVISION, new Map());
      expect(out!.masked, JSON.stringify(consent)).toBe(false);
      expect(out!.name).toBe("Arun Kumar");
    }
  });

  it("CONSENT: the division's own youth policy masks independently of consent", () => {
    const [out] = toLeaderInputRows(
      [snapshot()],
      [{ id: "d1", youth: true, player_name_display: null }],
      new Map(),
    );
    expect(out!.masked).toBe(true);
    expect(out!.name).toBe("Arun K.");
  });

  it("CONSENT: a division set to first_initial masks a person who never opted out", () => {
    // The division axis on its own, with youth false and consent granted —
    // the only case that fails if `player_name_display` is dropped on the way
    // into the resolver.
    const [out] = toLeaderInputRows(
      [snapshot()],
      [{ id: "d1", youth: false, player_name_display: "first_initial" }],
      new Map(),
    );
    expect(out!.masked).toBe(true);
    expect(out!.name).toBe("Arun K.");
  });

  it("CONSENT: an explicit division setting of 'full' does not override a person's opt-out", () => {
    const [out] = toLeaderInputRows(
      [snapshot({ consent: { public_name: false } })],
      [{ id: "d1", youth: false, player_name_display: "full" }],
      new Map(),
    );
    expect(out!.masked).toBe(true);
  });

  it("publicProfile mirrors the public_players_v membership the query read", () => {
    const [priv] = toLeaderInputRows([snapshot({ public_profile: false })], OPEN_DIVISION, new Map());
    expect(priv!.publicProfile).toBe(false);
    // …and the row itself survives: no profile is not no row.
    expect(priv!.name).toBe("Arun Kumar");
  });

  it("the entrant name comes from the MASKED map, never the raw column", () => {
    const [out] = toLeaderInputRows(
      [snapshot({ entrant_name: "Arun Kumar" })],
      OPEN_DIVISION,
      new Map([["e1", "Arun K."]]),
    );
    expect(out!.entrantName).toBe("Arun K.");
  });

  it("an entrant missing from the masked map yields NO entrant name, never the raw one", () => {
    // Falling back to `entrant_name` here would publish a display name that
    // never went through the consent pass — the row degrades instead.
    const [out] = toLeaderInputRows(
      [snapshot({ entrant_name: "Arun Kumar" })],
      OPEN_DIVISION,
      new Map(),
    );
    expect(out!.entrantName).toBeNull();
  });

  it("a person with no entrant at all keeps a null entrant name and badge", () => {
    const [out] = toLeaderInputRows(
      [snapshot({ entrant_id: null, entrant_name: null })],
      OPEN_DIVISION,
      new Map(),
    );
    expect(out!.entrantName).toBeNull();
    expect(out!.badgeUrl).toBeNull();
  });

  it("the badge resolves through the shared resolver: an http badge wins over a team logo", () => {
    const [out] = toLeaderInputRows(
      [snapshot({ badge_url: "https://cdn/b.png", team_logo_path: "teams/x.png" })],
      OPEN_DIVISION,
      new Map([["e1", "Blazers"]]),
    );
    expect(out!.badgeUrl).toBe("https://cdn/b.png");
  });

  it("the badge falls back to the linked team's logo, as a resolved public URL", () => {
    const [out] = toLeaderInputRows(
      [snapshot({ badge_url: null, team_logo_path: "teams/x.png" })],
      OPEN_DIVISION,
      new Map([["e1", "Blazers"]]),
    );
    expect(out!.badgeUrl).not.toBeNull();
    expect(out!.badgeUrl).toContain("teams/x.png");
  });

  it("each row is folded against ITS OWN division's policy, not the first one", () => {
    // Two divisions, opposite youth settings, in one call — a fold that read a
    // single shared policy would mask both or neither.
    const out = toLeaderInputRows(
      [snapshot({ person_id: "open" }), snapshot({ division_id: "d2", person_id: "young" })],
      [
        { id: "d1", youth: false, player_name_display: null },
        { id: "d2", youth: true, player_name_display: null },
      ],
      new Map(),
    );
    expect(out.map((r) => [r.personId, r.masked])).toEqual([
      ["open", false],
      ["young", true],
    ]);
  });
});
