// Pool label i18n (2026-10-06) — against real Postgres, through the REAL
// producer and the real readers.
//
// The defect: `pools.name` is only ever written by the generator as the
// English "Pool " + key (`usecases/stages.ts`), and the public surfaces printed
// that stored name, so a Spanish, French or Dutch spectator read "Pool A". The
// unit suites beside the surfaces hand-build their pools; only a database can
// show that the pools the GENERATOR writes reach each read model with the key
// the label is built from, and that the stored name stays exactly as written
// (the fix is display-only — no migration, no rename).
//
// Swept over all four locales: one org per locale, each with one group stage
// of two pools generated by `generateStageFixtures`. Expected words are read
// out of the dictionary FILES, never through the code under test. Single sport
// (`generic`) on purpose: a pool label does not depend on the sport, and the
// pools are the generator's whatever the sport is.
//
// Real Postgres required; skipped without DATABASE_URL (the DB-free CI gate).
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";

// `unstable_cache` has no incrementalCache outside a real request —
// passthrough, never a memoising double (each read must hit the database).
vi.mock("next/cache", () => ({
  unstable_cache: (fn: (...args: unknown[]) => unknown) => fn,
  revalidateTag: vi.fn(),
}));

import { sql } from "@/lib/db";
import enPublic from "@/dictionaries/en/public.json";
import esPublic from "@/dictionaries/es/public.json";
import frPublic from "@/dictionaries/fr/public.json";
import nlPublic from "@/dictionaries/nl/public.json";
import type { AuthCtx } from "@/server/api-v1/auth";
import { GENERIC_CONFIG, seedOrg } from "@/server/usecases/__tests__/_seed";
import { createCompetition } from "@/server/usecases/competitions";
import { createDivision } from "@/server/usecases/divisions";
import { createEntrants } from "@/server/usecases/entrants";
import { createStages, generateStageFixtures } from "@/server/usecases/stages";
import { buildDivisionSlides, buildPublicDivisionSlides } from "@/server/slideshow-data";
import { embedDivisionData } from "@/server/embed-data";
import { loadCompetitionHub } from "../competition-hub";
import { getPublicDivision } from "../data";

const HAS_DB = !!process.env.DATABASE_URL;

const FILES = { en: enPublic, es: esPublic, fr: frPublic, nl: nlPublic } as const;
type L = keyof typeof FILES;
const LOCALES = Object.keys(FILES) as L[];
const STAGE_NAME = "Groups";
const POOLS = 2;

/** The caption a pooled standings table owes, out of the dictionary file. */
const caption = (locale: L, key: string) => `${STAGE_NAME} — ${FILES[locale]["table.poolLabel"].replace("{key}", key)}`;

interface Scene {
  locale: L;
  auth: AuthCtx;
  orgSlug: string;
  compSlug: string;
  divisionId: string;
  stageId: string;
  /** The pools as the generator stored them, in key order. */
  pools: { id: string; key: string; name: string }[];
}

const scenes: Scene[] = [];

async function seed(locale: L): Promise<Scene> {
  const { auth } = await seedOrg();
  await sql`update organizations set default_locale = ${locale} where id = ${auth.orgId}`;
  // Lift the active-competition quota so a capped plan never downgrades the
  // public competition to private (which would make every read come back null).
  await sql`
    insert into org_entitlement_overrides (org_id, feature_key, int_value, reason)
    values (${auth.orgId}, 'competitions.max_active', null, 'test')
    on conflict do nothing`;
  const [{ slug: orgSlug }] = await sql<{ slug: string }[]>`select slug from organizations where id = ${auth.orgId}`;
  const comp = await createCompetition(auth, {
    ends_on: "2030-12-31",
    name: `Pool Label Cup ${locale}`,
    visibility: "public",
    branding: {},
  });
  const division = await createDivision(auth, comp.id, {
    name: "Open",
    slug: "open",
    sport_key: "generic",
    variant_key: "score",
    config: GENERIC_CONFIG,
  });
  await createEntrants(
    auth,
    division.id,
    ["Ash", "Birch", "Cedar", "Damson", "Elm", "Fir"].map((name, i) => ({
      kind: "team" as const,
      display_name: name,
      seed: i + 1,
      members: [],
    })),
  );
  const [stage] = await createStages(auth, division.id, {
    seq: 1,
    kind: "group",
    name: STAGE_NAME,
    config: { pools: { count: POOLS } },
  });
  const { fixtures } = await generateStageFixtures(auth, stage!.id);

  const pools = await sql<{ id: string; key: string; name: string }[]>`
    select id, key, name from pools where stage_id = ${stage!.id} order by key`;

  // One standings snapshot per pool, over the members the generator put in
  // it (read off its fixtures). `org_id` comes from the stages trigger.
  for (const pool of pools) {
    const members = [
      ...new Set(
        fixtures
          .filter((f) => f.pool_id === pool.id)
          .flatMap((f) => [f.home_entrant_id, f.away_entrant_id])
          .filter((id): id is string => typeof id === "string"),
      ),
    ];
    await sql`
      insert into standings_snapshots (stage_id, pool_id, rows, computed_through_seq)
      values (${stage!.id}, ${pool.id}, ${sql.json(
        members.map((entrantId, i) => ({
          entrantId,
          played: 0,
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
          metrics: {},
          rank: i + 1,
        })),
      )}, 0)`;
  }

  return {
    locale,
    auth,
    orgSlug,
    compSlug: comp.slug,
    divisionId: division.id,
    stageId: stage!.id,
    pools: [...pools],
  };
}

beforeAll(async () => {
  if (!HAS_DB) return;
  for (const locale of LOCALES) scenes.push(await seed(locale));
}, 120_000);

afterAll(async () => {
  if (!HAS_DB) return;
  const globalForDb = globalThis as { _sql?: { end(): Promise<void> } };
  const client = globalForDb._sql;
  globalForDb._sql = undefined;
  await client?.end();
});

describe.skipIf(!HAS_DB)("pool labels against real Postgres — the generator's pools, every reader, every locale", () => {
  it("premise: the generator stores the English 'Pool ' + key, and Spanish differs from it", () => {
    expect(scenes.map((s) => s.locale)).toEqual(LOCALES);
    let checked = 0;
    for (const s of scenes) {
      expect(s.pools.map((p) => p.key), s.locale).toEqual(["A", "B"]);
      for (const p of s.pools) {
        expect(p.name, s.locale).toBe(`Pool ${p.key}`);
        checked += 1;
      }
    }
    expect(checked).toBe(LOCALES.length * POOLS);
    expect(caption("es", "A")).not.toBe(`${STAGE_NAME} — Pool A`);
  });

  it("the competition hub captions each pool's table in the org's locale, from the key", async () => {
    let checked = 0;
    for (const s of scenes) {
      const doc = (await loadCompetitionHub(s.orgSlug, s.compSlug, new Date(), { uncached: true }))!;
      expect(doc, s.locale).not.toBeNull();
      expect(doc.locale).toBe(s.locale);
      const captions = doc.tables.map((t) => t.caption);
      expect(captions, s.locale).toEqual(s.pools.map((p) => caption(s.locale, p.key)));
      checked += captions.length;
    }
    expect(checked).toBe(LOCALES.length * POOLS);
  });

  it("the public division read and the embed read carry each pool's KEY — the field the label is built from", async () => {
    let checked = 0;
    for (const s of scenes) {
      const pub = (await getPublicDivision(s.orgSlug, s.compSlug, "open"))!;
      expect(pub.pools.map((p) => p.key).sort(), s.locale).toEqual(["A", "B"]);
      const embed = await embedDivisionData(s.divisionId);
      expect(embed.ok, s.locale).toBe(true);
      if (embed.ok) expect(embed.data.pools.map((p) => p.key).sort(), s.locale).toEqual(["A", "B"]);
      checked += pub.pools.length;
    }
    expect(checked).toBe(LOCALES.length * POOLS);
  });

  it("the public /present slides name each pool in the org's locale, from the public read", async () => {
    let checked = 0;
    for (const s of scenes) {
      const pub = (await getPublicDivision(s.orgSlug, s.compSlug, "open"))!;
      const slides = await buildPublicDivisionSlides({ ...pub, orgLocale: pub.org.default_locale });
      const captions = slides.filter((x) => x.kind === "standings").map((x) => (x as { caption: string }).caption);
      expect(captions.sort(), s.locale).toEqual(s.pools.map((p) => caption(s.locale, p.key)).sort());
      checked += captions.length;
    }
    expect(checked).toBe(LOCALES.length * POOLS);
  });

  it("the organiser slideshow names each pool in the org's locale, from the tenant read", async () => {
    let checked = 0;
    for (const s of scenes) {
      const slides = await buildDivisionSlides(s.auth, s.divisionId, "Open");
      const captions = slides.filter((x) => x.kind === "standings").map((x) => (x as { caption: string }).caption);
      expect(captions, s.locale).toEqual(s.pools.map((p) => caption(s.locale, p.key)));
      checked += captions.length;
    }
    expect(checked).toBe(LOCALES.length * POOLS);
  });

  it("display-only: after every read, the stored names are exactly what the generator wrote", async () => {
    let checked = 0;
    for (const s of scenes) {
      const now = await sql<{ id: string; key: string; name: string }[]>`
        select id, key, name from pools where stage_id = ${s.stageId} order by key`;
      expect([...now], s.locale).toEqual(s.pools);
      checked += now.length;
    }
    expect(checked).toBe(LOCALES.length * POOLS);
  });
});
