"use client";
// Period skin (S11/#420 W9) — STUB, owned this session by one implementer.
// Serves hockey AND icehockey: both are generated by period/kernel.ts and are
// byte-identical apart from the key prefix, so this skin must read action ids
// from the view rather than hardcoding either sport's prefix.
// See the brief; contract in ./types.ts.
import type { SkinDef, SkinLayout, SkinProps } from "./types";

export function PeriodSkin(_props: SkinProps) {
  return null;
}

export const periodSkin: SkinDef = {
  key: "period",
  sports: ["hockey", "icehockey"],
  layout: (): SkinLayout => ({ header: null, groups: [] }),
  Component: PeriodSkin,
};
