"use client";
// Period skin (S11/#420 W9) — hockey AND icehockey, one hand-crafted layout.
// Both are generated by period/kernel.ts and are byte-identical apart from
// the key prefix (owner ruling, dispatch brief), so EVERY routing decision
// below keys off the ACTION TYPE STRING the view itself hands over — never a
// hardcoded "hockey."/"icehockey." literal. That is the one mistake this
// file cannot afford: hardcode one prefix and the skin silently drops every
// action for the other sport, passing "coverage" for whichever sport was
// tested last.
//
// Two halves, per ./types.ts's own architecture rule:
//   1. `periodLayout` is PURE data placement — no React, no DOM, no i18n
//      lookup — so skin-coverage.test.ts can hold it to "every action the
//      view declares, exactly once, never invented" with no rendering at
//      all (apps/web's vitest is `environment: "node"`, no jsdom).
//   2. `PeriodSkin` is a thin React surface that draws exactly what
//      `periodLayout` handed it, plus the interactive parts a pure function
//      cannot own (attribution chip state, i18n lookup via `useMsg()`).
//      Every rendering helper below is a PLAIN FUNCTION called directly
//      (never a JSX-instantiated `<Foo/>` component) — action-form.tsx's own
//      header explains why: this repo's node-only `_hook-harness` walks a
//      rendered tree by descending into `.props.children` only, and never
//      invokes a nested custom component function, so a genuinely separate
//      component would make everything inside it permanently invisible to
//      `walk()`/`textOf()`. `ActionForm` is the one real exception, exactly
//      as it is for panel.tsx — it owns real per-instance hook state
//      (expanded/values) a skin has no business flattening away.
//
// DESIGN (frontend-design skill, loaded before this file was written): the
// palette and component vocabulary are NOT this file's to invent — the
// brief pins them down (dark "scoreboard" strip for status chrome, ordinary
// light card/btn system below, pad-renderer.tsx's own header comment) — so
// the deliberate choices here are about INFORMATION ARCHITECTURE specific to
// this sport pair, not new colors: the header mirrors a real arena
// scoreboard's own face (a dominant score flanked by small period/clock
// readouts, tabular-nums, exactly device-score-pad.tsx's established LED
// treatment); groups are ordered by what a rinkside scorer actually reaches
// for (goal first, period control always visible beside it, discipline/set-
// piece next, shot detail tucked in a drawer); and person attribution reads
// the module's OWN live folded state first (`readSquads`, the same
// structural check attribution-picker.tsx's `isSquadState` uses), then falls
// back to `ctx.lineups` — the kickoff team sheet, populated by
// pad-renderer.tsx's own `skinCtx` (SkinLayoutCtx.lineups; PadRendererProps.
// lineups is not even optional, so every real caller has it) — via the SAME
// shared `resolveSquads` the unskinned render path already gets for free
// through `<AttributionPicker>`. An earlier version of this comment claimed
// the skin "gets no `lineups` prop at all"; that was true when this file was
// first written (S11/#420 W9) but SkinLayoutCtx grew a `lineups` field
// afterward and this skin never started reading it — every hockey/icehockey
// suspension asked a scorer to hand-type a personId, since a suspension is
// almost always the first discipline event of a match and no `core.lineup.*`
// event has folded yet (S13/#422 W11, caught by a real-browser e2e). Now the
// text-field degrade fires only when NEITHER route has a roster (the pure
// coverage sweep's `state:{}` walk, which never reaches this code, or a
// fixture with genuinely no saved lineup). Once a roster is known, by either
// route, the chip label offers a jersey NUMBER first, deliberately ahead of
// a resolved name (S12/#421 pass B): a scorer identifies a player by number
// first. Only when NO number is declared does the chip fall back to
// `ctx.personNames` (S11's SkinLayoutCtx), and only past that to a short id
// fragment — see `memberLabel`'s own comment.
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useMsg } from "@/components/i18n/dict-provider";
import { padLabel } from "@/lib/scoring-vocab";
import type { MessageKey } from "@/lib/messages";
import { formatElapsed } from "@seazn/engine/core";
import type { SquadState, SquadMember } from "@seazn/engine/core";
import type { PadAttributionItem, PadFieldValue } from "@seazn/engine/sport";
import { ActionForm, type ActionValues } from "../action-form";
import { attributionItemCaption, isSquadState, resolveSquads } from "../attribution-picker";
import type { PadActionView, PadView } from "../view-model";
import {
  actionByType,
  type SkinDef,
  type SkinGroup,
  type SkinHeader,
  type SkinHeaderField,
  type SkinLayout,
  type SkinLayoutCtx,
  type SkinProminence,
  type SkinProps,
} from "./types";
import { renderLockedTile, chipClass } from "./shared";

/** `useMsg()`'s own return shape (dict-provider.tsx:78), typed explicitly
 *  rather than `ReturnType<typeof useMsg>` — every render helper below takes
 *  it as a parameter instead of calling the hook itself, matching
 *  action-form.tsx's `renderField`/attribution-picker.tsx's
 *  `renderAttributionItem` (both plain functions, not components). */
type MsgFn = (key: MessageKey, vars?: Record<string, string | number>) => string;

function isRecord(x: unknown): x is Record<string, unknown> {
  return !!x && typeof x === "object";
}

// ---------------------------------------------------------------------------
// Pure header derivation — every read here is STRUCTURAL and defensive: the
// coverage sweep calls `layout(view, {state: {}, summary: {}, ...})`, so a
// header that could throw on an absent field would break the one test that
// most needs it never to (skin-coverage.test.ts's "no-header" check).
// ---------------------------------------------------------------------------

/** Real entrant ids, straight off `PeriodState.entrants` (period/kernel.ts —
 *  non-optional, set at `init()`, so it is reliable the instant a fixture
 *  exists). This is what lets the "side" attribution chips below carry a
 *  real `EntrantId` with no `lineups` prop at all — SkinProps hands a skin
 *  no roster (see the module header), but this ONE fact period kernels
 *  already put on their own folded state, unprompted. */
function readEntrants(state: unknown): { home: string; away: string } | null {
  if (!isRecord(state)) return null;
  const entrants = state.entrants;
  if (!isRecord(entrants)) return null;
  const { home, away } = entrants;
  return typeof home === "string" && typeof away === "string" ? { home, away } : null;
}

/** Reuses `isSquadState` (attribution-picker.tsx, exported, already proven)
 *  rather than re-deriving the same structural check — the SAME reason that
 *  file gives for checking the SHAPE rather than trusting `state.squads` by
 *  field name: football keeps a private, differently-shaped `squads` at the
 *  same key. Absent whenever no `core.lineup.*` event has folded yet
 *  (squad-state.ts's adoption rule) — the common case for a fresh fixture,
 *  which is exactly why the person-attribution renderer below has a real
 *  text-input degrade rather than assuming this is always populated. */
function readSquads(state: unknown): SquadState | null {
  if (!isRecord(state)) return null;
  const squads = state.squads;
  return isSquadState(squads) ? squads : null;
}

function readPhase(state: unknown): string | null {
  if (!isRecord(state)) return null;
  const phase = state.phase;
  return typeof phase === "string" && phase.length > 0 ? phase : null;
}

/** One entry of `PeriodState.suspensions` (period/kernel.ts's own
 *  `ActiveSuspension`, ./suspensions.ts) — read defensively and structurally,
 *  same posture as `readEntrants`/`readSquads` above, since `ctx.state` is
 *  `unknown` by contract. Only the fields the countdown hint below actually
 *  needs; `person`/`reason`/`servedBy`/`startedAt`/`expiresAt` are the
 *  engine's own scoresheet detail and stay out of scope here (S12/#421
 *  cutover: `period-pad.tsx`'s wall-clock countdown, restored on this skin —
 *  see `SuspensionCountdownList`'s own doc comment for why it is a real
 *  component rather than one more plain render helper). */
interface SuspensionView {
  side: "home" | "away";
  classKey: string;
  permanent: boolean;
  /** The duration the official actually awarded, when recorded — preferred
   *  over the class nominal (suspensions.ts's own `SuspensionDetail.minutes`
   *  doc: "Pads count down from here in preference to the class"). */
  minutes?: number;
}

function readSuspensions(state: unknown): readonly SuspensionView[] {
  if (!isRecord(state)) return [];
  const raw = state.suspensions;
  if (!Array.isArray(raw)) return [];
  const out: SuspensionView[] = [];
  for (const item of raw) {
    if (!isRecord(item)) continue;
    const side = item.side;
    const classKey = item.classKey;
    if ((side !== "home" && side !== "away") || typeof classKey !== "string") continue;
    out.push({
      side,
      classKey,
      permanent: item.permanent === true,
      minutes: typeof item.minutes === "number" ? item.minutes : undefined,
    });
  }
  return out;
}

/** The class's NOMINAL duration from cfg (`Cfg.suspensions.classes[key]
 *  .minutes` — period/kernel.ts's own `SuspensionClassCfg`), the fallback
 *  when no per-suspension `minutes` was awarded. `null` for both an unknown
 *  class and a class with no fixed duration (`minutes: null` — a permanent
 *  exclusion, e.g. hockey's `red`), which is deliberately the same return
 *  value: either way there is nothing to count down from. */
function classMinutesOf(cfg: unknown, classKey: string): number | null {
  if (!isRecord(cfg)) return null;
  const suspensions = cfg.suspensions;
  if (!isRecord(suspensions)) return null;
  const classes = suspensions.classes;
  if (!isRecord(classes)) return null;
  const cls = classes[classKey];
  if (!isRecord(cls)) return null;
  const minutes = cls.minutes;
  return typeof minutes === "number" ? minutes : null;
}

/** "pre"/"done"/"final"/"abandoned" are lifecycle tokens worth a capital
 *  letter; "Q1"/"P2"/"OT"/"SHOOTOUT" are already the exact scoreboard-ready
 *  casing the kernel means to be displayed (period/kernel.ts's own
 *  `periodLabels`/`otLabels`) and must not be touched. */
function displayPhase(phase: string): string {
  return /^[a-z]+$/.test(phase) ? phase.charAt(0).toUpperCase() + phase.slice(1) : phase;
}

function readClock(state: unknown): string | null {
  if (!isRecord(state)) return null;
  const asOf = state.asOf;
  if (!isRecord(asOf)) return null;
  const elapsed = asOf.elapsed;
  return typeof elapsed === "number" ? formatElapsed(elapsed) : null;
}

/**
 * The score line. Prefers `summary.perSide[].line` (the module's OWN
 * `summary()` — period/kernel.ts's own header: "the headline is the
 * official score... one derivation, read by both", the exact function that
 * folds in the shoot-out-winner-goal adjustment IIHF Rule 87 requires and a
 * bare `state.goals` read would silently miss) over raw `state.goals`
 * (regulation + OT only — right most of the time, wrong exactly when a
 * shoot-out has just decided an icehockey match), over the "0 – 0" a fresh
 * fixture (or the coverage sweep's `state: {}`) honestly is.
 */
function readScoreLine(summary: unknown, state: unknown): string {
  if (isRecord(summary) && Array.isArray(summary.perSide) && summary.perSide.length === 2) {
    const [a, b] = summary.perSide as unknown[];
    if (isRecord(a) && isRecord(b) && typeof a.line === "string" && typeof b.line === "string") {
      return `${a.line} – ${b.line}`;
    }
  }
  if (isRecord(state) && isRecord(state.goals)) {
    const { home, away } = state.goals;
    if (typeof home === "number" && typeof away === "number") return `${home} – ${away}`;
  }
  return "0 – 0";
}

const HEADER_SCORE_CAPTION: MessageKey = "scorepad.skin.period.header.score";
const HEADER_PERIOD_CAPTION: MessageKey = "scorepad.skin.period.header.period";
const HEADER_CLOCK_CAPTION: MessageKey = "scorepad.skin.period.header.clock";

function buildHeader(ctx: SkinLayoutCtx): SkinHeader {
  const phase = readPhase(ctx.state);
  const fields: SkinHeaderField[] = [
    { id: "score", value: readScoreLine(ctx.summary, ctx.state), captionKey: HEADER_SCORE_CAPTION, emphasis: true },
    { id: "period", value: phase ? displayPhase(phase) : "—", captionKey: HEADER_PERIOD_CAPTION, emphasis: false },
    { id: "clock", value: readClock(ctx.state) ?? "—", captionKey: HEADER_CLOCK_CAPTION, emphasis: false },
  ];
  return { fields };
}

// ---------------------------------------------------------------------------
// Pure grouping — routes each action the VIEW declares (never a hardcoded
// sport prefix) to a skin-local group, by the action-name SUFFIX every
// period-kernel sport shares (period/kernel.ts:1823-1832: `${key}.goal`,
// `${key}.period.advance`, `${key}.suspension.start/.end`,
// `${key}.shootout.attempt`, `${key}.set_piece`, `${key}.shot`). Suffix
// matching, not exact-equality against a precomputed `${sport}.goal` string,
// is what makes this routing genuinely sport-agnostic: it never reads
// `ctx.cfg`/the sport key at all, only the type strings the view itself
// handed over — the one mistake the brief warns is the likeliest way this
// file fails its gate.
// ---------------------------------------------------------------------------

interface Route {
  suffix: string;
  groupId: string;
  prominence: SkinProminence;
}

// Order matters only in that every suffix here is unambiguous against every
// other (no two ever both match one real action type) — see the header
// comment on why ".shot" cannot accidentally match ".shootout.attempt".
const ROUTES: readonly Route[] = [
  { suffix: ".goal", groupId: "goal", prominence: "primary" },
  { suffix: ".shootout.attempt", groupId: "shootout", prominence: "primary" },
  { suffix: ".period.advance", groupId: "period", prominence: "secondary" },
  { suffix: ".suspension.start", groupId: "discipline", prominence: "secondary" },
  { suffix: ".suspension.end", groupId: "discipline", prominence: "secondary" },
  { suffix: ".set_piece", groupId: "setPiece", prominence: "secondary" },
  { suffix: ".shot", groupId: "shots", prominence: "drawer" },
];

// Draw order: primary groups first, then secondary, then drawer — a "other"
// bucket closes the set defensively (never drops a future 8th action type
// silently; see the routeFor default below) without changing behaviour for
// either sport shipped today, since it is always empty for both.
const GROUP_ORDER = ["goal", "shootout", "period", "discipline", "setPiece", "shots", "other"] as const;

function routeFor(type: string): Route {
  for (const route of ROUTES) if (type.endsWith(route.suffix)) return route;
  return { suffix: "", groupId: "other", prominence: "secondary" };
}

function buildGroups(view: PadView): SkinGroup[] {
  const buckets = new Map<string, { prominence: SkinProminence; actions: string[] }>();
  for (const panel of view.panels) {
    for (const action of panel.actions) {
      const route = routeFor(action.type);
      let bucket = buckets.get(route.groupId);
      if (!bucket) {
        bucket = { prominence: route.prominence, actions: [] };
        buckets.set(route.groupId, bucket);
      }
      bucket.actions.push(action.type);
    }
  }
  const groups: SkinGroup[] = [];
  for (const id of GROUP_ORDER) {
    const bucket = buckets.get(id);
    if (bucket && bucket.actions.length > 0) groups.push({ id, prominence: bucket.prominence, actions: bucket.actions });
  }
  return groups;
}

/** The skin's PURE layout function — see the module header for why this half
 *  never touches React/DOM/i18n. */
export function periodLayout(view: PadView, ctx: SkinLayoutCtx): SkinLayout {
  return { header: buildHeader(ctx), groups: buildGroups(view) };
}

// ---------------------------------------------------------------------------
// Component-side rendering. Every function below is called DIRECTLY inside
// `PeriodSkin`'s own render (never JSX-instantiated as its own component) —
// see the module header for why that is load-bearing for this repo's
// hook-harness tests, not merely style.
// ---------------------------------------------------------------------------

const GROUP_TITLE_KEY: Record<string, MessageKey> = {
  goal: "scorepad.skin.period.group.goal",
  shootout: "scorepad.skin.period.group.shootout",
  period: "scorepad.skin.period.group.period",
  discipline: "scorepad.skin.period.group.discipline",
  setPiece: "scorepad.skin.period.group.setPiece",
  shots: "scorepad.skin.period.group.shots",
};

/** `SkinHeaderField.captionKey` is typed as a bare `string | null` in
 *  ./types.ts (not editable here) — this is the one place that trusts it
 *  really is a `MessageKey`, which it always is: `buildHeader` above is the
 *  only producer, and every value it uses is one of the three literal
 *  `HEADER_*_CAPTION` constants declared next to it. */
function capMsg(msg: MsgFn, key: string | null): string {
  return key ? msg(key as MessageKey) : "";
}

/** A scorer's own vocabulary: a squad member is a NUMBER first, never a
 *  personId — see the module header. Falls back to `personNames[personId]`
 *  (S12/#421 pass B) for the (legal, per SquadMember) case of a roster entry
 *  with no declared number, and only past that to a short id fragment — the
 *  honest last resort when no name is known either. */
function memberLabel(member: SquadMember, personNames: Readonly<Record<string, string>> | undefined): string {
  if (member.squadNumber !== undefined) return `#${member.squadNumber}`;
  return personNames?.[member.personId] ?? member.personId.slice(0, 6);
}

/**
 * One attribution item, resolved against whatever roster facts THIS skin can
 * actually read — the module's own LIVE folded state first (`readSquads`),
 * `ctx.lineups` (the kickoff team sheet) next, via `resolveSquads` — plus
 * `ctx.personNames` for the chip label. Three tiers, each an honest
 * reflection of what is actually known right now, never a fabricated one:
 *   - "side": real Home/Away chips keyed on `state.entrants` (always known
 *     once a fixture exists) — never a bare "home"/"away" literal, which the
 *     engine's own `EntrantId` schema would reject.
 *   - "person" WITH a roster, live-folded OR from the kickoff sheet: number
 *     chips, exactly the vocabulary a scorer already uses (`memberLabel`'s
 *     own comment on why number beats a resolved name here, not just
 *     id-vs-name).
 *   - "person" with NO roster known by EITHER route (`ctx.lineups` also
 *     absent — the pure coverage sweep, or a fixture with no saved lineup at
 *     all): a captioned text field. Not a picker pretending to have data it
 *     does not — but still a real, labelled control, never a bare unlabelled
 *     input.
 */
function renderAttributionItem(
  item: PadAttributionItem,
  index: number,
  actionLabel: string,
  value: PadFieldValue | undefined,
  onSelect: (v: PadFieldValue | undefined) => void,
  entrants: { home: string; away: string } | null,
  squads: SquadState | null,
  personNames: Readonly<Record<string, string>> | undefined,
  msg: MsgFn,
): ReactNode {
  const caption = attributionItemCaption(item, index, msg, actionLabel);

  if (item.kind === "side") {
    if (!entrants) {
      return (
        <div key={item.path} className="space-y-1">
          <span className="label !mb-0">{caption}</span>
          <p className="text-xs text-slate-600">{msg("scorepad.attribution.noRoster")}</p>
        </div>
      );
    }
    const options = [
      { value: entrants.home, label: msg("scorepad.attribution.home") },
      { value: entrants.away, label: msg("scorepad.attribution.away") },
    ];
    return (
      <div key={item.path} data-attribution-path={item.path} role="group" aria-label={caption} className="space-y-1">
        <span className="label !mb-0">{caption}</span>
        <div className="flex gap-2">
          {options.map((opt) => {
            const pressed = value === opt.value;
            return (
              <button
                key={opt.value}
                type="button"
                data-value={opt.value}
                aria-pressed={pressed}
                onClick={() => onSelect(pressed ? undefined : opt.value)}
                className={chipClass(pressed)}
              >
                {opt.label}
              </button>
            );
          })}
        </div>
      </div>
    );
  }

  // kind === "person"
  const candidates = squads ? [...squads.home.members, ...squads.away.members] : [];
  if (candidates.length > 0) {
    return (
      <div key={item.path} data-attribution-path={item.path} role="group" aria-label={caption} className="space-y-1">
        <span className="label !mb-0">{caption}</span>
        <div className="flex gap-2 overflow-x-auto pb-1 -mx-1 px-1">
          {candidates.map((member) => {
            const pressed = value === member.personId;
            return (
              <button
                key={member.personId}
                type="button"
                data-value={member.personId}
                aria-pressed={pressed}
                onClick={() => onSelect(pressed ? undefined : member.personId)}
                className={chipClass(pressed)}
              >
                {memberLabel(member, personNames)}
              </button>
            );
          })}
        </div>
      </div>
    );
  }

  return (
    <div key={item.path} data-attribution-path={item.path} className="space-y-1">
      <label className="block">
        <span className="label">{caption}</span>
        <input
          className="input"
          type="text"
          value={typeof value === "string" ? value : ""}
          onChange={(e) => onSelect(e.target.value === "" ? undefined : e.target.value)}
        />
      </label>
    </div>
  );
}

/**
 * Builds the `renderAttribution` callback `ActionForm` expects
 * (action-form.tsx's `ActionFormProps.renderAttribution`), closing over the
 * roster facts read once from `ctx.state` and `ctx.lineups`. Exported (not
 * just an inline closure inside `PeriodSkin`) so it is independently
 * testable against a REAL folded state without needing to drive the whole
 * component through the hook harness — the suspension flow is exactly the
 * surface criterion 5 holds this skin to, and this is the one function that
 * decides it.
 */
export function buildAttributionRenderer(
  ctx: SkinLayoutCtx,
  msg: MsgFn,
): (action: PadActionView, values: ActionValues, setValue: (path: string, value: PadFieldValue | undefined) => void) => ReactNode {
  const entrants = readEntrants(ctx.state);
  // Live folded squad wins when one has folded (readSquads); otherwise fall
  // back to the kickoff team sheet via the SAME resolveSquads the unskinned
  // render path already gets through <AttributionPicker> — see the module
  // header. `ctx.lineups` is absent only in the pure coverage sweep and one
  // of this file's own unit tests (both keep the old state-only read).
  const squads = ctx.lineups ? resolveSquads(ctx.state, ctx.lineups) : readSquads(ctx.state);
  const personNames = ctx.personNames;
  // Named, not an anonymous arrow: it returns JSX, so eslint's react/display-name
  // treats it as a component definition. It is really a render prop, but a name
  // costs nothing and keeps `apps/web`'s own lint (the one CI runs) clean.
  return function periodAttribution(action, values, setValue) {
    if (action.attribution.length === 0) return null;
    const actionLabel = padLabel(action.labelKey.key, msg, action.labelKey.label);
    return (
      <div className="space-y-3" data-role="skin-attribution">
        {action.attribution.map((item, index) =>
          renderAttributionItem(item, index, actionLabel, values[item.path], (v) => setValue(item.path, v), entrants, squads, personNames, msg),
        )}
      </div>
    );
  };
}

/**
 * Wall-clock countdown sugar for the suspensions currently running — display
 * only, restored here at the S13/#422 cutover from `period-pad.tsx` (v1,
 * deleted this session), which had it and which this skin never did. The
 * engine's own `ActiveSuspension` doc (period/suspensions.ts) names exactly
 * this split: "the fold sweeps against this LAZILY ... between an expiry and
 * the next event the pad and the fold legitimately disagree — the pad is
 * counting down, the fold is a record of facts." So this stamps each
 * suspension's remaining time the FIRST RENDER it is observed and ticks a
 * LOCAL clock once a second; release is always the scorer's own explicit
 * action through the discipline group's own `${key}.suspension.end` form
 * rendered alongside it (never this component — it is read-only).
 *
 * A REAL component, JSX-instantiated (`<SuspensionCountdownList/>` in
 * `PeriodSkin` below), not one more plain render function like its siblings
 * in this file — see the module header for why that split is deliberate:
 * this is the one other piece of the skin (besides `ActionForm`) that owns
 * real per-instance hook state (the stamps, the tick), so it must stay a
 * true component for `_hook-harness`'s `renderIsland` to see it tick at all
 * — a plain function's `useState`/`useEffect` would run inside `PeriodSkin`
 * itself and be untestable in isolation.
 *
 * Keyed on ARRAY INDEX, exactly as v1's did (period-pad.tsx, deleted) — the
 * engine gives no stable suspension id, and `state.suspensions` is a small,
 * append/remove-in-place list the fold itself owns, so index identity is the
 * same assumption the fold's own array already makes.
 */
export function SuspensionCountdownList({
  suspensions,
  cfg,
  msg,
}: {
  suspensions: readonly SuspensionView[];
  cfg: unknown;
  msg: MsgFn;
}): ReactNode {
  const [stamps, setStamps] = useState<Map<number, number>>(() => new Map());
  const [, forceTick] = useState(0);

  // Stamp newly-seen suspensions with "now"; drop stamps for indices that no
  // longer exist (released, or the innings/period moved on) — same shape as
  // v1's own effect, kept in state (not a ref) so a read during render is
  // never stale.
  useEffect(() => {
    setStamps((prev) => {
      let next: Map<number, number> | null = null;
      suspensions.forEach((_, i) => {
        if (!prev.has(i)) {
          next ??= new Map(prev);
          next.set(i, Date.now());
        }
      });
      for (const key of prev.keys()) {
        if (key >= suspensions.length) {
          next ??= new Map(prev);
          next.delete(key);
        }
      }
      return next ?? prev;
    });
  }, [suspensions]);

  // Ticks once a second only while at least one suspension is running —
  // cleaned up (clearInterval) the moment none remain, so this never leaves
  // a stray timer running against an empty list.
  useEffect(() => {
    if (suspensions.length === 0) return;
    const id = setInterval(() => forceTick((n) => n + 1), 1000);
    return () => clearInterval(id);
  }, [suspensions.length]);

  if (suspensions.length === 0) return null;

  function countdown(index: number, susp: SuspensionView): string | null {
    if (susp.permanent) return msg("pad.pp.matchCountdown");
    const total = susp.minutes ?? classMinutesOf(cfg, susp.classKey);
    if (total === null) return null;
    const started = stamps.get(index);
    if (started === undefined) return `${total}:00`;
    const left = Math.max(0, total * 60 - Math.floor((Date.now() - started) / 1000));
    const mm = Math.floor(left / 60);
    const ss = String(left % 60).padStart(2, "0");
    return `${mm}:${ss}`;
  }

  return (
    <div className="rounded-lg border border-amber-200 bg-amber-50 p-2" data-role="suspension-countdown">
      <p className="mb-1.5 text-xs font-medium text-amber-800">{msg("pad.pp.runningPenalties")}</p>
      <ul className="space-y-1">
        {suspensions.map((susp, i) => {
          const hint = countdown(i, susp);
          return (
            <li key={i} className="flex flex-wrap items-center gap-2 text-xs text-slate-700" data-role="suspension-row">
              <span className="font-medium">
                {msg(susp.side === "home" ? "scorepad.attribution.home" : "scorepad.attribution.away")}
              </span>
              <span>{susp.classKey}</span>
              {hint && (
                <span data-testid="suspension-countdown-hint" className="font-mono text-amber-700">
                  {hint}
                </span>
              )}
            </li>
          );
        })}
      </ul>
      <p className="mt-1 text-[10px] text-amber-800">{msg("pad.pp.timersHint")}</p>
    </div>
  );
}

function fieldValueClass(field: SkinHeaderField): string {
  return field.emphasis
    ? "font-mono text-[clamp(1.5rem,8.5vw,3rem)] font-bold leading-tight tabular-nums tracking-tight text-emerald-300 [text-shadow:0_0_24px_rgba(52,211,153,0.35)]"
    : "font-mono text-sm font-semibold tabular-nums text-slate-200";
}

/** The dark "scoreboard" strip (pad-renderer.tsx's own header comment; the
 *  established signature, device-score-pad.tsx's header) — an arena
 *  scoreboard's own face: period + clock as small flanking readouts over a
 *  dominant score. Queue/offline status rides the same strip, reusing the
 *  chassis's OWN pre-existing `scorepad.queue.*` keys (pad-renderer.tsx
 *  already ships these; this file only ever adds the `scorepad.skin.*` keys
 *  the dispatch actually names). */
function renderHeader(header: SkinHeader | null, queueDepth: number, offline: boolean, msg: MsgFn): ReactNode {
  if (!header) return null;
  const emphasis = header.fields.filter((f) => f.emphasis);
  const chips = header.fields.filter((f) => !f.emphasis);
  const queueLabel = offline
    ? msg("scorepad.queue.offline")
    : queueDepth > 0
      ? msg("scorepad.queue.pending", { count: queueDepth })
      : msg("scorepad.queue.synced");
  const queueAttention = offline || queueDepth > 0;

  return (
    <header
      data-role="period-skin-header"
      className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900 shadow-[0_0_40px_-12px_rgba(16,185,129,0.25)]"
    >
      <div aria-hidden className="h-0.5 bg-accent" />
      <div className="border-b border-slate-800 px-4 py-2">
        <div className="flex gap-4">
          {chips.map((field) => (
            <span key={field.id} data-role={`header-${field.id}`} className="text-left">
              {field.captionKey && (
                <span className="block text-[10px] uppercase tracking-widest text-slate-400">{capMsg(msg, field.captionKey)}</span>
              )}
              <span className={fieldValueClass(field)}>{field.value}</span>
            </span>
          ))}
        </div>
        {/* Its OWN line, never squeezed into the chips row: `scorepad.queue.
            offline` is a full sentence in every locale, not a short status
            word (device-score-pad.tsx's own top-strip label is the one that
            is), and a `shrink-0` sibling sharing a row with it clips mid-
            sentence at 320px instead of wrapping — caught by this skin's own
            screenshot pass. */}
        <p className={`mt-1 text-[11px] uppercase tracking-widest ${queueAttention ? "text-amber-400" : "text-slate-400"}`}>
          {queueLabel}
        </p>
      </div>
      {emphasis.length > 0 && (
        <div className="px-3 py-4 text-center sm:px-4 sm:py-5">
          {emphasis.map((field) => (
            <p key={field.id} data-role={`header-${field.id}`}>
              {field.captionKey && (
                <span className="block text-[10px] font-semibold uppercase tracking-widest text-slate-400">
                  {capMsg(msg, field.captionKey)}
                </span>
              )}
              <span className={fieldValueClass(field)}>{field.value}</span>
            </p>
          ))}
        </div>
      )}
    </header>
  );
}

function renderActionForms(
  types: readonly string[],
  view: PadView,
  dispatch: SkinProps["dispatch"],
  submittingType: string | null,
  renderAttribution: ReturnType<typeof buildAttributionRenderer>,
  msg: MsgFn,
): ReactNode {
  return types.map((type) => {
    const action = actionByType(view, type);
    // Defensive only: the coverage gate guarantees every placed type exists
    // on `view` — this never fires for a real spec, and never hides a type
    // silently if it somehow did (nothing here removes it from `types`).
    if (!action) return null;
    if (action.availability.kind === "locked") return renderLockedTile(action, msg);
    return (
      <ActionForm
        key={type}
        action={action}
        submitting={submittingType === type}
        onSubmit={(payload) => void dispatch(type, payload)}
        renderAttribution={renderAttribution}
      />
    );
  });
}

/** A `grid` group with exactly one action spans the full row from `sm` up —
 *  the same fix panel.tsx's own `actionsClassName` applies (S10/#419 W8 fix
 *  2), reapplied here because this skin draws its OWN group chrome rather
 *  than routing through `Panel`. */
function secondaryActionsClass(count: number): string {
  return count === 1 ? "grid grid-cols-1 gap-2" : "grid grid-cols-2 gap-2";
}

export function PeriodSkin(props: SkinProps): ReactNode {
  const msg = useMsg();
  const { view, layout, dispatch, submittingType, queueDepth, offline } = props;

  // Keyed on the fold's own state identity, matching pad-renderer.tsx's own
  // `renderAttribution` memo one level up (module-client.ts's `foldClient`
  // gives a fresh `state` identity on every fold advance).
  const renderAttribution = useMemo(() => buildAttributionRenderer(props.ctx, msg), [props.ctx, msg]);
  const suspensions = useMemo(() => readSuspensions(props.ctx.state), [props.ctx.state]);

  const primary = layout.groups.filter((g) => g.prominence === "primary");
  const secondary = layout.groups.filter((g) => g.prominence === "secondary");
  const drawer = layout.groups.filter((g) => g.prominence === "drawer");

  return (
    <div className="space-y-3" data-role="period-skin">
      {renderHeader(layout.header, queueDepth, offline, msg)}

      {primary.map((group) => (
        <section key={group.id} className="card p-3" data-role={`group-${group.id}`}>
          <h3 className="label !mb-2">{msg(GROUP_TITLE_KEY[group.id] ?? "scorepad.skin.period.group.goal")}</h3>
          <div className="flex flex-col gap-2">
            {renderActionForms(group.actions, view, dispatch, submittingType, renderAttribution, msg)}
          </div>
        </section>
      ))}

      {secondary.length > 0 && (
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2" data-role="secondary-groups">
          {secondary.map((group, i) => {
            // The odd-one-out card spans both columns from `sm` up instead
            // of leaving its row half-empty — the same "no dead space
            // beside a lone tile" rule panel.tsx's own `actionsClassName`
            // applies one level down, at the action-grid level.
            const isTrailingOdd = secondary.length % 2 === 1 && i === secondary.length - 1;
            return (
              <section
                key={group.id}
                className={`card p-3 ${isTrailingOdd ? "sm:col-span-2" : ""}`}
                data-role={`group-${group.id}`}
              >
                <h3 className="label !mb-2">{msg(GROUP_TITLE_KEY[group.id] ?? "scorepad.skin.period.group.period")}</h3>
                {group.id === "discipline" && (
                  <div className="mb-2">
                    <SuspensionCountdownList suspensions={suspensions} cfg={props.ctx.cfg} msg={msg} />
                  </div>
                )}
                <div className={secondaryActionsClass(group.actions.length)}>
                  {renderActionForms(group.actions, view, dispatch, submittingType, renderAttribution, msg)}
                </div>
              </section>
            );
          })}
        </div>
      )}

      {drawer.length > 0 && (
        <details className="card group p-3" data-role="drawer-groups">
          <summary className="btn btn-ghost w-full cursor-pointer list-none justify-between">
            <span>{msg("scorepad.skin.more")}</span>
            <span aria-hidden className="text-xs text-purple-400 group-open:rotate-180">
              ▾
            </span>
          </summary>
          <div className="mt-3 space-y-3">
            {drawer.map((group) => (
              <div key={group.id} data-role={`group-${group.id}`}>
                <h4 className="label !mb-2">{msg(GROUP_TITLE_KEY[group.id] ?? "scorepad.skin.period.group.shots")}</h4>
                <div className="flex flex-col gap-2">
                  {renderActionForms(group.actions, view, dispatch, submittingType, renderAttribution, msg)}
                </div>
              </div>
            ))}
          </div>
        </details>
      )}
    </div>
  );
}

export const periodSkin: SkinDef = {
  key: "period",
  sports: ["hockey", "icehockey"],
  layout: periodLayout,
  Component: PeriodSkin,
};
