// Skin registry (S11/#420 W9). The single place that answers "does this sport
// have a hand-crafted layout, and which one".
//
// Consulted by PadRenderer itself rather than left for S12 to wire — owner
// ruling 2026-08-13, taken because S10's attribution picker shipped REACHABLE
// ONLY IF A CALLER REMEMBERED TO PASS IT and nobody noticed until an e2e drove
// the real API (_INDEX.md, "fifth instance of this programme's signature
// defect"). A registry nothing consults is that defect's exact shape.
//
// WHICH SPORTS GET A SKIN, and why these groupings — measured, not assumed
// (probe evidence, S11 2026-08-13, recorded in _INDEX.md):
//
//   cricket           -> cricket-skin   own module; t20/odi/hundred share one
//                                       skeleton, `test` alone adds declare /
//                                       followon / match.close
//   tennis            -> tennis-skin    nested/kernel.ts — its OWN action
//                                       vocabulary (tennis.point,
//                                       tennis.game.award) and a gated
//                                       gameAward panel the setbased three
//                                       have no equivalent of
//   football          -> football-skin   hand-written module; has subs +
//                                       penalties panels the period pair
//                                       lacks, lacks their setPiece + shootout
//   hockey            -> period-skin    both generated by period/kernel.ts and
//   icehockey                           byte-identical to each other apart from
//                                       the key prefix
//
// NOT LISTED: volleyball, badminton, tabletennis. All three used to share
// ONE row here (-> racquet-skin, setbased/kernel.ts's common action family)
// until R5 (2026-08-27) converted each to its own v3 skin
// (`v3/registry.ts`'s `V3_SKINS`, unconditionally — no flag, no fallback).
// `ScorePad` (../registry.tsx) consults `v3/registry.ts`'s `resolvePad`
// FIRST and returns before this registry is ever reached for those three
// keys, so racquet-skin.tsx had zero remaining callers and was deleted as
// dead code in the same wave, not merely deprioritised — there is no row to
// restore here later. Contrast cricket/tennis/football above: also fully
// v3-owned, but their v2 skin files were NOT part of that deletion (nothing
// else in this repo shares them, so nothing forced the question), so they
// keep a real, honest row despite being equally unreachable through
// `ScorePad` today.
//
// hockey/icehockey joined cricket/tennis/football's category in R6
// (2026-08-30, `v3/skins/period-shared.ts`'s `makePeriodSkin` — one factory,
// both sports). `period-skin.tsx` below is still real, tested code — R6's own
// task D left it working rather than demolishing it, unlike racquet-skin
// above — but `V3_SKINS` owns both keys now and `ScorePad` resolves the v3
// lane FIRST, so the `hockey`/`icehockey -> period-skin` row two entries up
// is exactly as unreachable through `ScorePad` as the three names above it.
// R6 fix pass 4, finding 5 (branch review): this note was the one R5 left for
// racquet-skin that R6's own conversion never got.
//
// Everything else (generic, carrom, boardgame, …) stays on the universal
// renderer DELIBERATELY — the universal renderer guarantees coverage, and a
// sport without the match volume to earn hand-crafted ergonomics is better
// served by the layout that is proven across every module.
import type { SkinDef } from "./types";
import { cricketSkin } from "./cricket-skin";
import { tennisSkin } from "./tennis-skin";
import { footballSkin } from "./football-skin";
import { periodSkin } from "./period-skin";

export const SKINS: readonly SkinDef[] = [cricketSkin, tennisSkin, footballSkin, periodSkin];

const BY_SPORT: ReadonlyMap<string, SkinDef> = new Map(
  SKINS.flatMap((skin) => skin.sports.map((sport) => [sport, skin] as const)),
);

/** The skin for a sport, or null when the sport stays on the universal
 *  renderer. Never throws: an unknown sport key is the universal case. */
export function skinFor(sportKey: string): SkinDef | null {
  return BY_SPORT.get(sportKey) ?? null;
}
