// Skin registry (S11/#420 W9). The single place that answers "does this sport
// have a hand-crafted layout, and which one".
//
// Consulted by PadRenderer itself rather than left for S12 to wire — owner
// ruling 2026-08-13, taken because S10's attribution picker shipped REACHABLE
// ONLY IF A CALLER REMEMBERED TO PASS IT and nobody noticed until an e2e drove
// the real API (_INDEX.md, "fifth instance of this programme's signature
// defect"). A registry nothing consults is that defect's exact shape.
//
// WHICH SPORTS GET A SKIN, and why these groupings — measured, not assumed
// (probe evidence, S11 2026-08-13, recorded in _INDEX.md):
//
//   cricket           -> cricket-skin   own module; t20/odi/hundred share one
//                                       skeleton, `test` alone adds declare /
//                                       followon / match.close
//   tennis            -> tennis-skin    nested/kernel.ts — its OWN action
//                                       vocabulary (tennis.point,
//                                       tennis.game.award) and a gated
//                                       gameAward panel the setbased three
//                                       have no equivalent of
//   volleyball        -> racquet-skin   all three from setbased/kernel.ts, one
//   badminton                           action family ({key}.rally/.timeout/
//   tabletennis                         .sanction/.sub); the skin reacts to the
//                                       records flags that add or drop panels
//   football          -> football-skin   hand-written module; has subs +
//                                       penalties panels the period pair
//                                       lacks, lacks their setPiece + shootout
//   hockey            -> period-skin    both generated by period/kernel.ts and
//   icehockey                           byte-identical to each other apart from
//                                       the key prefix
//
// Everything else (generic, carrom, boardgame, …) stays on the universal
// renderer DELIBERATELY — the universal renderer guarantees coverage, and a
// sport without the match volume to earn hand-crafted ergonomics is better
// served by the layout that is proven across every module.
import type { SkinDef } from "./types";
import { cricketSkin } from "./cricket-skin";
import { racquetSkin } from "./racquet-skin";
import { tennisSkin } from "./tennis-skin";
import { footballSkin } from "./football-skin";
import { periodSkin } from "./period-skin";

export const SKINS: readonly SkinDef[] = [cricketSkin, racquetSkin, tennisSkin, footballSkin, periodSkin];

const BY_SPORT: ReadonlyMap<string, SkinDef> = new Map(
  SKINS.flatMap((skin) => skin.sports.map((sport) => [sport, skin] as const)),
);

/** The skin for a sport, or null when the sport stays on the universal
 *  renderer. Never throws: an unknown sport key is the universal case. */
export function skinFor(sportKey: string): SkinDef | null {
  return BY_SPORT.get(sportKey) ?? null;
}
