// Skin registry (S11/#420 W9). The single place that answers "does this sport
// have a hand-crafted layout, and which one".
//
// Consulted by PadRenderer itself rather than left for S12 to wire — owner
// ruling 2026-08-13, taken because S10's attribution picker shipped REACHABLE
// ONLY IF A CALLER REMEMBERED TO PASS IT and nobody noticed until an e2e drove
// the real API (_INDEX.md, "fifth instance of this programme's signature
// defect"). A registry nothing consults is that defect's exact shape.
//
// SKINS IS NOW PERMANENTLY EMPTY (2026-08-31, chore/retire-unreachable-v2-
// skins). The last four v2 skins — cricket-skin, tennis-skin, football-skin,
// period-skin (hockey + icehockey) — are deleted, closing out what R5 started
// (racquet-skin.tsx, volleyball/badminton/tabletennis) and what R6 explicitly
// deferred for period-skin.tsx ("R6 fix pass 4, finding 5", its own commit
// header). `skinFor` below now returns null unconditionally.
//
// FOR THE RECORD — which sport got a skin, and why (measured, not assumed;
// probe evidence, S11 2026-08-13, recorded in _INDEX.md), kept here because
// nothing else in this repo still has this reasoning written down:
//
//   cricket           -> cricket-skin   own module; t20/odi/hundred share one
//                                       skeleton, `test` alone adds declare /
//                                       followon / match.close
//   tennis            -> tennis-skin    nested/kernel.ts — its OWN action
//                                       vocabulary (tennis.point,
//                                       tennis.game.award) and a gated
//                                       gameAward panel the setbased three
//                                       have no equivalent of
//   football          -> football-skin  hand-written module; has subs +
//                                       penalties panels the period pair
//                                       lacks, lacks their setPiece + shootout
//   hockey/icehockey  -> period-skin    both generated by period/kernel.ts and
//                                       byte-identical apart from key prefix
//   volleyball/badminton/tabletennis -> racquet-skin, setbased/kernel.ts's
//                                       common action family (deleted R5,
//                                       2026-08-27, as its own dead-code wave —
//                                       this file's header carried the same
//                                       kind of note for it, once)
//
// Every one of those eight sports converted fully to its own v3 skin
// (`v3/registry.ts`'s `V3_SKINS`, unconditionally — no flag, no fallback)
// BEFORE its v2 file was deleted, in each one's own wave — `ScorePad`
// (../registry.tsx) has consulted `v3/registry.ts`'s `resolvePad` FIRST, and
// returned before this registry was ever reached for any of them, since that
// sport's own conversion landed. The per-sport "had a v2 skin, no longer
// does" record now lives in `../registry.tsx`'s `NO_V2_SKIN_SPORTS` — this
// file no longer carries a live per-sport table at all.
//
// Everything else (generic, carrom, boardgame, …) stays on the universal
// renderer DELIBERATELY — the universal renderer guarantees coverage, and a
// sport without the match volume to earn hand-crafted ergonomics is better
// served by the layout that is proven across every module. That is still a
// live, real decision (`../registry.tsx`'s `RESOLUTION_KIND`), unlike every
// row in the table above.
//
// THIS FILE SURVIVES the emptying: `skinFor` is still imported by
// pad-renderer.tsx (its own default-skin-resolution path) and by
// ../registry.tsx (`resolveScorePad`'s own guard) — neither dependency is
// v2-skin-specific, so neither call site goes away with the skins. Deleting
// this file as well as its skins would leave both of those with an import
// nothing provides. Same reasoning kept `./types.ts` (`SkinDef`,
// `createSkinDispatch` — also live in v3/pad-host.tsx) and dropped only
// `./shared.tsx` (`renderLockedTile`/`chipClass`), which had no importer left
// once the four skins that used it were gone.
import type { SkinDef } from "./types";

/** Empty, permanently — see this file's header. Kept as a real (empty) array
 *  rather than deleted so `skinFor` below stays the same total function it
 *  always was: an empty registry answers every lookup exactly the way a
 *  populated one would for a sport it does not claim. */
export const SKINS: readonly SkinDef[] = [];

const BY_SPORT: ReadonlyMap<string, SkinDef> = new Map(
  SKINS.flatMap((skin) => skin.sports.map((sport) => [sport, skin] as const)),
);

/** The skin for a sport, or null when the sport stays on the universal
 *  renderer. Never throws: an unknown sport key is the universal case.
 *  Always null today (`SKINS` above is empty) — left as a real function
 *  rather than inlined at its two call sites (pad-renderer.tsx,
 *  ../registry.tsx) so a v2 skin returning here later is a one-file change,
 *  not a two-file one. */
export function skinFor(sportKey: string): SkinDef | null {
  return BY_SPORT.get(sportKey) ?? null;
}
