// Generates apps/web/src/lib/i18n-keys.ts — the union of every key authored in
// the en dictionaries — so t()'s `key` argument autocompletes. Checked into git
// and regenerated by this script; CI runs it and fails on drift
// (`git diff --exit-code`, ci.yml "i18n key union drift + locale parity").
// Run after adding/removing any en key.
//
// THAT CI STEP ONLY EXISTS AS OF W8. This comment asserted it for several waves
// while no i18n step ran in CI at all — which is how W8 shipped
// `pass.entry.ended.nextBody` three commits ahead of the union with tsc,
// i18n:check and the full suite green the whole time. `t()` cannot catch it
// either: `TKey = DictionaryKey | (string & {})` accepts any string.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { flattenKeys } from "../../apps/web/src/lib/i18n-dict-utils.ts";

const here = dirname(fileURLToPath(import.meta.url));
const EN_DIR = join(here, "../../apps/web/src/dictionaries/en");
const OUT = join(here, "../../apps/web/src/lib/i18n-keys.ts");

const keys = new Set<string>();
for (const f of readdirSync(EN_DIR).filter((f) => f.endsWith(".json"))) {
  for (const k of flattenKeys(JSON.parse(readFileSync(join(EN_DIR, f), "utf8")) as Record<string, unknown>)) keys.add(k);
}

const union = [...keys].sort();
const body = union.length
  ? union.map((k) => `  | ${JSON.stringify(k)}`).join("\n")
  : "  never";

writeFileSync(
  OUT,
  `// GENERATED by scripts/i18n/gen-keys.ts — do not edit by hand.\n` +
    `// Run \`npm run i18n:gen-keys\` after changing any en dictionary key.\n` +
    `export type DictionaryKey =\n${body};\n`,
);
console.log(`i18n-keys.ts: ${union.length} keys.`);
