// A CASCADE-AWARE reader for `src/app/globals.css` — enough of one to answer
// "which rule wins this property on this element", which is the question a
// `css.toContain("…")` grep structurally cannot ask.
//
// WHY THIS EXISTS (R3 review round, `_INDEX.md`). Task B4 added
//
//   .pad-half:focus-visible { outline-color: var(--sport-led); }
//
// UNLAYERED, at specificity (0,2,0). The platform's own focus ring
// (`:where(a, button, summary, [role="tab"]):focus-visible`) is also unlayered
// but scores (0,1,0), because `:where()` contributes ZERO — so the pad rule
// won, and cricket's scorebug focus ring turned from violet `--ps-accent` to
// the default LED lime. A cricket PIXEL MOVED, which ruling R3-6 forbids
// outright ("any implementation that changes a cricket pixel is wrong").
//
// It survived a dedicated cricket-identity proof (`sport-theme.test.ts`)
// because that proof runs in a NODE environment against class names and hex
// tables, and the defect lives in the CSS CASCADE. The Tailwind utility the
// rule replaced (`focus-visible:outline-lime-400`) had always LOST to the
// platform ring — it sits in `@layer utilities`, and any layer loses to
// unlayered — so the visible colour never changed until the rule left the
// layer. Nothing in a class-name assertion can see that.
//
// ---------------------------------------------------------------------------
// WHAT THIS CAN AND CANNOT SEE — stated plainly, because a guard that
// overstates its reach is worse than one that admits its edge.
//
// CAN: layer membership (unlayered beats every `@layer`), selector
// specificity with `:where()` zeroed, source order, `@media`-conditional
// rules, and descendant matching for the small selector grammar globals.css
// actually uses (type / `.class` / `[attr]` / `[attr="v"]` / pseudo-classes /
// `:where(list)` / descendant combinators).
//
// CANNOT: anything outside globals.css. Tailwind's compiled utilities are
// generated by `@import "tailwindcss"` and are not in this file's text. That
// is SOUND for the question asked here rather than a hole, and for a stated
// reason: every generated utility lands in `@layer utilities`, and the cascade
// puts every layered rule below every unlayered one — so no utility can beat a
// rule this reader does see. It is NOT sound for a question about two
// utilities, and this file must not be used for one.
//
// It is also not a browser: no `!important`, no inline styles, no
// `@scope`/`@container`, no shadow DOM, no user/UA origins. Every rule it is
// pointed at must be an author-origin, non-important declaration — which every
// rule in globals.css is.
import { readFileSync } from "node:fs";
import { join } from "node:path";

export interface CssRule {
  /** The `@layer` name this rule sits in, or `null` for UNLAYERED — which is
   *  the whole point: unlayered author rules beat every layered one. */
  layer: string | null;
  /** Enclosing conditional at-rules (`@media …`), outermost first. Recorded
   *  rather than evaluated: a caller decides which conditions its element is
   *  under. */
  conditions: readonly string[];
  /** ONE selector — a comma-separated list is split into one rule each, which
   *  is what the cascade does too. */
  selector: string;
  /** The raw declaration block, semicolon-separated. */
  declarations: string;
  /** Position in the file, for the cascade's final tie-break. */
  order: number;
}

const AT_RULES_WITHOUT_SELECTORS = ["@keyframes", "@theme", "@font-face", "@property", "@counter-style"];

/**
 * globals.css as a flat rule list. A hand-written scanner rather than a CSS
 * parser dependency: the grammar here is small and stable, and the
 * alternative is a new production-adjacent dependency for one test file.
 */
export function parseCss(css: string): CssRule[] {
  const rules: CssRule[] = [];
  const stack: { kind: "layer" | "condition" | "opaque"; name: string }[] = [];
  let i = 0;
  let order = 0;
  let buffer = "";

  const layerOf = (): string | null => {
    for (let s = stack.length - 1; s >= 0; s--) if (stack[s]!.kind === "layer") return stack[s]!.name;
    return null;
  };
  const conditionsOf = (): string[] => stack.filter((s) => s.kind === "condition").map((s) => s.name);

  while (i < css.length) {
    const ch = css[i]!;
    if (ch === "/" && css[i + 1] === "*") {
      const end = css.indexOf("*/", i + 2);
      i = end === -1 ? css.length : end + 2;
      continue;
    }
    if (ch === "{") {
      const prelude = buffer.trim();
      buffer = "";
      i++;
      if (prelude.startsWith("@layer")) {
        stack.push({ kind: "layer", name: prelude.slice("@layer".length).trim() });
        continue;
      }
      if (prelude.startsWith("@media") || prelude.startsWith("@supports")) {
        stack.push({ kind: "condition", name: prelude });
        continue;
      }
      if (AT_RULES_WITHOUT_SELECTORS.some((at) => prelude.startsWith(at)) || stack.some((s) => s.kind === "opaque")) {
        stack.push({ kind: "opaque", name: prelude });
        continue;
      }
      if (prelude.startsWith("@")) {
        stack.push({ kind: "opaque", name: prelude });
        continue;
      }
      // A style rule. Read to its matching close brace; nested blocks are not
      // used in this file, so a depth counter is enough to stay honest if one
      // ever appears.
      let depth = 1;
      const start = i;
      while (i < css.length && depth > 0) {
        if (css[i] === "{") depth++;
        else if (css[i] === "}") depth--;
        i++;
      }
      const declarations = css.slice(start, i - 1);
      const layer = layerOf();
      const conditions = conditionsOf();
      for (const selector of splitSelectorList(prelude)) {
        rules.push({ layer, conditions, selector, declarations, order: order++ });
      }
      continue;
    }
    if (ch === "}") {
      stack.pop();
      buffer = "";
      i++;
      continue;
    }
    if (ch === ";") {
      buffer = "";
      i++;
      continue;
    }
    buffer += ch;
    i++;
  }
  return rules;
}

export function readGlobalsCss(): string {
  return readFileSync(join(process.cwd(), "src/app/globals.css"), "utf8");
}

/** Splits a selector list on top-level commas — never inside `:where(…)`. */
export function splitSelectorList(prelude: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let current = "";
  for (const ch of prelude) {
    if (ch === "(" || ch === "[") depth++;
    else if (ch === ")" || ch === "]") depth--;
    if (ch === "," && depth === 0) {
      out.push(current.trim());
      current = "";
      continue;
    }
    current += ch;
  }
  if (current.trim().length > 0) out.push(current.trim());
  return out;
}

/** One element, as much of it as the grammar below can read. */
export interface ElementSpec {
  tag: string;
  classes: readonly string[];
  /** Attributes present, e.g. `{ "data-sport-theme": "football" }`. */
  attrs?: Readonly<Record<string, string>>;
  /** Pseudo-classes currently matching, e.g. `["focus-visible"]`. */
  pseudo?: readonly string[];
}

/** Splits a complex selector into compound selectors on DESCENDANT combinators
 *  only. A `>`/`+`/`~` is deliberately unsupported and throws rather than
 *  quietly matching the wrong thing. */
function compounds(selector: string): string[] {
  if (/[>+~]/.test(selector.replace(/\([^)]*\)/g, ""))) {
    throw new Error(`_globals-css.ts cannot evaluate the combinator in "${selector}" — extend it, do not guess`);
  }
  // Whitespace splits ONLY at depth 0. `:where(a, button, summary,
  // [role="tab"])` contains three spaces of its own, and splitting on them
  // turned one compound into four — which scored the platform ring at (0,1,2)
  // instead of (0,1,0) and would have made this reader agree with the defect.
  const out: string[] = [];
  let current = "";
  let depth = 0;
  for (const ch of selector) {
    if (ch === "(" || ch === "[") depth++;
    if (ch === ")" || ch === "]") depth--;
    if (depth === 0 && /\s/.test(ch)) {
      if (current.length > 0) out.push(current);
      current = "";
      continue;
    }
    current += ch;
  }
  if (current.length > 0) out.push(current);
  return out;
}

/** Splits one compound selector into its atoms (`button`, `.x`, `[a="b"]`,
 *  `:focus-visible`, `:where(...)`). */
function atoms(compound: string): string[] {
  const out: string[] = [];
  let current = "";
  let depth = 0;
  for (const ch of compound) {
    if (depth === 0 && (ch === "." || ch === "#" || ch === ":" || ch === "[") && current.length > 0) {
      out.push(current);
      current = "";
    }
    if (ch === "(" || ch === "[") depth++;
    if (ch === ")" || ch === "]") depth--;
    current += ch;
  }
  if (current.length > 0) out.push(current);
  return out;
}

function matchesAtom(atom: string, element: ElementSpec): boolean {
  if (atom.startsWith(":where(") || atom.startsWith(":is(")) {
    const inner = atom.slice(atom.indexOf("(") + 1, atom.lastIndexOf(")"));
    return splitSelectorList(inner).some((sel) => matchesCompound(sel, element));
  }
  if (atom.startsWith(":")) return (element.pseudo ?? []).includes(atom.slice(1));
  if (atom.startsWith(".")) return element.classes.includes(atom.slice(1));
  if (atom.startsWith("[")) {
    const body = atom.slice(1, -1);
    const eq = body.indexOf("=");
    if (eq === -1) return Object.prototype.hasOwnProperty.call(element.attrs ?? {}, body);
    const name = body.slice(0, eq);
    const value = body.slice(eq + 1).replace(/^["']|["']$/g, "");
    return (element.attrs ?? {})[name] === value;
  }
  if (atom === "*") return true;
  return atom === element.tag;
}

function matchesCompound(compound: string, element: ElementSpec): boolean {
  return atoms(compound).every((atom) => matchesAtom(atom, element));
}

/**
 * Whether `selector` matches `element` sitting inside `ancestors` (outermost
 * first). Descendant combinators only — see `compounds`.
 */
export function matches(selector: string, element: ElementSpec, ancestors: readonly ElementSpec[] = []): boolean {
  const parts = compounds(selector);
  const subject = parts[parts.length - 1]!;
  if (!matchesCompound(subject, element)) return false;
  // Walk the remaining compounds right-to-left against the ancestor chain.
  let a = ancestors.length - 1;
  for (let p = parts.length - 2; p >= 0; p--) {
    let found = false;
    while (a >= 0) {
      const candidate = ancestors[a]!;
      a--;
      if (matchesCompound(parts[p]!, candidate)) {
        found = true;
        break;
      }
    }
    if (!found) return false;
  }
  return true;
}

/** `[ids, classes+attrs+pseudo-classes, types]`, with `:where()` zeroed —
 *  the one rule that decided this defect. */
export function specificity(selector: string): [number, number, number] {
  let ids = 0;
  let mid = 0;
  let types = 0;
  for (const compound of compounds(selector)) {
    for (const atom of atoms(compound)) {
      if (atom.startsWith(":where(")) continue; // ZERO, by spec — the whole story
      if (atom.startsWith(":is(")) {
        const inner = atom.slice(4, -1);
        let best: [number, number, number] = [0, 0, 0];
        for (const sel of splitSelectorList(inner)) {
          const s = specificity(sel);
          if (s[0] > best[0] || (s[0] === best[0] && (s[1] > best[1] || (s[1] === best[1] && s[2] > best[2])))) best = s;
        }
        ids += best[0];
        mid += best[1];
        types += best[2];
        continue;
      }
      if (atom.startsWith("::")) types += 1;
      else if (atom.startsWith("#")) ids += 1;
      else if (atom.startsWith(".") || atom.startsWith("[") || atom.startsWith(":")) mid += 1;
      else if (atom !== "*") types += 1;
    }
  }
  return [ids, mid, types];
}

/** The value a rule gives `prop`, expanding the ONE shorthand that matters
 *  here (`outline` sets `outline-color`). `undefined` when the rule says
 *  nothing about it. */
export function declaredValue(rule: CssRule, prop: string): string | undefined {
  let found: string | undefined;
  for (const raw of rule.declarations.split(";")) {
    const colon = raw.indexOf(":");
    if (colon === -1) continue;
    const name = raw.slice(0, colon).trim();
    const value = raw.slice(colon + 1).trim();
    if (name === prop) found = value;
    else if (prop === "outline-color" && name === "outline") {
      // `outline: 2px solid var(--ps-accent)` — the colour is the component
      // that is neither a length nor a line-style.
      const colour = value
        .split(/\s+(?![^(]*\))/)
        .find((part) => !/^\d/.test(part) && !["none", "solid", "dashed", "dotted", "double", "auto"].includes(part));
      if (colour !== undefined) found = colour;
    }
  }
  return found;
}

/**
 * WHICH RULE WINS `prop` on `element`, by the real cascade order for
 * author-origin, non-important declarations:
 *
 *   1. UNLAYERED beats every `@layer` (CSS Cascade 5 §6.4.4).
 *   2. then specificity,
 *   3. then source order.
 *
 * Layer-vs-layer ordering is deliberately NOT implemented: globals.css
 * declares exactly one layer of its own, so any comparison between two layers
 * would be untested code pretending to be a rule. It throws instead.
 */
export function cascadeWinner(
  rules: readonly CssRule[],
  prop: string,
  element: ElementSpec,
  ancestors: readonly ElementSpec[] = [],
  opts: { conditions?: (condition: string) => boolean } = {},
): CssRule | undefined {
  const applies = (rule: CssRule): boolean =>
    rule.conditions.every((condition) => opts.conditions?.(condition) ?? false) &&
    declaredValue(rule, prop) !== undefined &&
    matches(rule.selector, element, ancestors);

  let best: CssRule | undefined;
  for (const rule of rules) {
    if (!applies(rule)) continue;
    if (best === undefined) {
      best = rule;
      continue;
    }
    if (best.layer !== rule.layer) {
      if (best.layer === null) continue; // unlayered already wins
      if (rule.layer === null) {
        best = rule;
        continue;
      }
      throw new Error(
        `_globals-css.ts cannot order @layer "${best.layer}" against @layer "${rule.layer}" — ` +
          "declare the order and implement it rather than guessing",
      );
    }
    const a = specificity(best.selector);
    const b = specificity(rule.selector);
    const cmp = b[0] - a[0] || b[1] - a[1] || b[2] - a[2] || rule.order - best.order;
    if (cmp > 0) best = rule;
  }
  return best;
}
