"""BUILD model acceptance tests.

The board under test is the production shape that motivated the whole
investigation (37 fixtures, 5 courts, 26 days x 5 courts x 64 ticks) and it is
generated by `placement_bench_boards.production_board()` — the SAME generator the
bench sweep drives, deliberately shared rather than copied, so the two cannot
drift apart (see the prompt's Step 2b).

These exercise the real solver end to end. Nothing here is mocked: a green run
means CP-SAT actually proved optimality on the real board inside the budget.

--- round 6: identity is POSITIONAL, `bench/` is not ------------------------

`bench/placement_bench_boards.py` is out of scope for round 6 and still returns
string-keyed boards (fixture ids, court names, division/entrant ids) — see
`placement.model`'s module docstring. `_board_positional.to_positional` is the
one place that bridges the two: every board below is converted immediately
after generation, so `build_model` only ever sees the positional shape a real
caller would send after this round.
"""

import logging
import os

import pytest
import structlog
from ortools.sat.python import cp_model

from _board_positional import rule_groups_for, to_positional
from placement.model import DAY_MS, MIN_MS, build_model, solve

#: The production budget from the design spec, and the wall the acceptance
#: criterion is stated at.
PRODUCTION_WALL_SECONDS = 8.0


def _load():
    """One-minute load average, for failure messages only.

    Every wall-clock claim in this service is load-sensitive — the same board
    measures ~4 940 ms/OPTIMAL on an idle box and 8 044 ms/FEASIBLE at load 11
    — so a red that does not say how busy the machine was cannot be triaged.
    Reported, never branched on: a test that skips itself under load is a test
    that never runs in CI.
    """
    return os.getloadavg()[0]


def _production_board():
    """The bench's `production_board()`, converted to the positional shape,
    PLUS the `rule_groups` its declared `rest_by_division`/`day_cap_by_
    division` now have to reach `build_model` through: `division_rules`
    (proto field 10), the wire path those dict keys used to be fed through,
    is retired (`placement.schema`'s module docstring). Without this, every
    caller below would silently solve an UNCAPPED, un-rested board -- a
    materially EASIER-to-place but HARDER-to-optimise problem (see
    `test_absent_day_cap_rule_means_no_cap`'s own docstring: the day cap is
    what pins fixtures across the lattice, and without it T1 does not finish
    inside a budget that used to be generous), not the same production board
    this file's tests are meant to be about.

    Returns an 8-tuple: the 7 `build_model(*board)`-shaped elements
    (`to_positional`'s own output) plus `rule_groups`.
    """
    # Module name follows the file the prompt's Step 2b names
    # (bench/placement_bench_boards.py) and its siblings placement_bench.py /
    # placement_repair_bench.py. bench/ reaches sys.path via `pythonpath` in
    # pyproject.toml — it is a script directory, not an installed package.
    from placement_bench_boards import production_board

    board = production_board()
    return (*to_positional(board), rule_groups_for(board))


def test_production_board_meets_the_stated_acceptance_criterion():
    """Prompt 02's acceptance criterion, asserted as written, for the first time.

    *"the production board solves to OPTIMAL with 35-37 assignments in under 8
    seconds, verified by an automated test."* Both halves existed in the suite;
    neither was asserted against the other. `test_production_board_solves_under_budget`
    accepts FEASIBLE and `tiers_completed >= 1` at the 8 s wall, and the OPTIMAL
    half is proved in `test_objective.py` at a THIRTY second wall. Measured at
    8 s under load 11: `FEASIBLE, 37 placed, tiers=2, elapsed_ms=8044` — the
    criterion not met, the suite green.

    Note what OPTIMAL means for this chain and why the count is asserted beside
    it: `status` is OPTIMAL only when every requested tier was PROVED, so it
    carries the four-tier claim; and a model with no objective at all also
    returns OPTIMAL, with ZERO placed, so status alone is vacuous. Both
    assertions are load-bearing.

    THIS TEST IS LOAD-SENSITIVE ON PURPOSE. The same board measures ~4 940 ms
    OPTIMAL idle and 8 044 ms FEASIBLE at load 11, on eight search workers over
    six physical cores. That is the acceptance criterion being genuinely
    marginal on a contended box, not a defect in the tier code, and weakening
    the assertion would hide the one thing this test exists to say. The load
    average is reported in the failure message so a red can be triaged rather
    than guessed at; re-run alone before calling it a regression.
    """
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps, rule_groups = (
        _production_board()
    )
    model = build_model(
        fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps,
        rule_groups=rule_groups,
    )
    load = _load()
    outcome = solve(model, wall_seconds=PRODUCTION_WALL_SECONDS)
    detail = (
        f"status={outcome.status} placed={len(outcome.assignments)} "
        f"tiers_completed={outcome.tiers_completed} elapsed_ms={outcome.elapsed_ms} "
        f"wall={PRODUCTION_WALL_SECONDS}s load1={load:.2f}"
    )
    assert 35 <= len(outcome.assignments) <= 37, detail
    assert outcome.status == "OPTIMAL", detail


def test_production_board_solves_under_budget():
    """The board solves, completely, inside the production wall.

    Renamed from `..._solves_optimal_under_budget`, and the `status ==
    "OPTIMAL"` assertion is gone, because `solve()` no longer answers the
    question that assertion was asking. It was written when `solve()` was T0
    alone (~100 ms, always proved); it now drives the whole T0->T3 chain, whose
    final status reports whether all FOUR tiers were proved inside 8 s. That is
    a claim about the machine as much as the board — measured at 4 940 ms idle
    and past the wall under concurrent load — so it belongs in
    `test_objective.py`, which owns it and runs it deterministically.

    What is asserted here is what this test was always really about, and it is
    the assertion that carries the weight anyway: the board comes back whole.
    A missing objective returns OPTIMAL with ZERO placed, so the count is what
    catches that mutant, never the status.

    The 8 s wall here is inherited, not justified. An earlier version of this
    docstring claimed cutting it to 3 s let the participant-rest and court-gap
    mutants survive; that came from a single run per cell and does not
    reproduce — at six runs both mutants die MORE reliably at 3 s than at 8 s.
    The measured table is in
    `test_assignments_satisfy_every_stated_constraint`, and those two families
    are now guarded properly by `test_participant_rest_is_binding` and
    `test_the_court_turnaround_gap_is_binding`, on contended boards that do not
    depend on the wall at all.
    """
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps, rule_groups = (
        _production_board()
    )
    model = build_model(
        fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps,
        rule_groups=rule_groups,
    )
    outcome = solve(model, wall_seconds=8.0)
    assert outcome.status in ("OPTIMAL", "FEASIBLE")
    assert 35 <= len(outcome.assignments) <= 37
    assert outcome.tiers_completed >= 1
    assert outcome.elapsed_ms <= 8250


def test_no_court_double_booking():
    # The 8 s wall carries no coverage claim — an earlier comment here said it
    # did, on the strength of one run per cell, and six runs reversed the
    # result. See the measured table in
    # `test_assignments_satisfy_every_stated_constraint`. The court-gap family
    # is guarded by `test_the_court_turnaround_gap_is_binding`, not here.
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps, rule_groups = (
        _production_board()
    )
    model = build_model(
        fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps,
        rule_groups=rule_groups,
    )
    outcome = solve(model, wall_seconds=8.0)
    assert outcome.assignments, "nothing placed — the loop below would be vacuous"
    seen = {}
    for fixture_index, court_index, start_ms in outcome.assignments:
        key = (court_index, start_ms)
        assert key not in seen, f"double-booked {key}"
        seen[key] = fixture_index


def test_assignments_satisfy_every_stated_constraint():
    """Re-verify the solver's answer against each constraint family, in plain
    Python, the way `validateAssignments` does on the TS side.

    The two tests above leave most of the model untestable: deleting the
    participant-rest `AddNoOverlap`, the order-dependency inequality or the
    per-division day cap leaves both of them green (measured — the rest mutant
    survived them). A solver whose constraint families can be removed without
    a test noticing is the failure mode this repo has been bitten by before,
    so each family gets an assertion that fails without it.

    DO NOT TREAT THIS TEST AS THE GUARD FOR COURT GAP OR PARTICIPANT REST.
    It catches them only by luck. Measured over six runs per cell against a
    pristine mirror, with the mutation's presence verified in each run:

        mutant                                   8 s wall     3 s wall
        M2  participant-rest NoOverlap deleted   RED 5/6      RED 6/6
        M7  gap dropped from the court width     RED 1/6      RED 6/6
        baseline (unmutated)                     GREEN 2/2    GREEN 2/2

    Two things follow, and the second corrects a claim an earlier version of
    this docstring asserted as fact:

      * M7 is a **coin flip here — 1 in 6** at the shipped wall. It is now
        genuinely guarded by `test_the_court_turnaround_gap_is_binding`, and
        M2 by `test_participant_rest_is_binding`, both on purpose-built
        contended boards that decide on a proved COUNT in milliseconds.
      * A LONGER WALL MAKES THESE TWO **LESS** DETECTABLE, NOT MORE. The
        earlier claim that "T1's packing pressure is what exposes them" was
        drawn from a single run per cell and is wrong — with six runs the
        effect reverses. The real driver is that this board is uncontended:
        8 320 slots, 37 fixtures and a day cap of one per division per day
        leave everything naturally spread out, so a deleted turnaround or rest
        window usually changes no placement at all. The more tiers finish, the
        better-optimised the board, and the fewer incidental violations remain
        for this test to trip over.

    So the 8 s wall is NOT load-bearing coverage. It is kept only because it
    is what the other assertions here were measured at and nothing argues for
    changing it; if suite runtime ever needs to come down this is a legitimate
    place to take it from, provided the M1-M8 matrix is re-run to confirm the
    families it really does guard (M1, M3, M4, M5, M8) still die.
    """
    # `rule_groups` (from `_production_board()`, derived from the SAME
    # declared `rest_by_division`/`day_cap_by_division` `constraints` below
    # still carries, for computing the EXPECTED numbers this test checks the
    # board against) is what actually binds the rest/cap families now:
    # `division_rules` (proto field 10), the wire path that used to carry
    # them, is retired -- see `_board_positional.rule_groups_for`'s own
    # docstring, and `placement.schema`'s module docstring for the wire side.
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps, rule_groups = (
        _production_board()
    )
    model = build_model(
        fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps,
        rule_groups=rule_groups,
    )
    outcome = solve(model, wall_seconds=8.0)
    assert outcome.assignments, "nothing placed — the rest of this test would be vacuous"
    assert len(outcome.assignments) == len(fixtures), (
        "not every fixture was placed, so some constraint arm below may be vacuous"
    )

    dur_ms = constraints["match_minutes"] * MIN_MS
    gap_ms = constraints["gap_minutes"] * MIN_MS
    rest_by_division = constraints["rest_by_division"]
    day_cap_by_division = constraints["day_cap_by_division"]

    # Fixture identity is now POSITION, so these are lists, not id-keyed dicts.
    entrants_of = [ents for ents, _div in fixtures]
    division_of = [div for _ents, div in fixtures]
    placed = {fi: (court, start) for fi, court, start in outcome.assignments}
    legal_court_starts = {(court, start) for court, start, _day in grid_slots}

    # every placement lands on a tick THAT COURT actually offers
    for fi, (court, start) in placed.items():
        assert 0 <= court < num_courts, f"fixture {fi} placed on unknown court {court}"
        assert (court, start) in legal_court_starts, (
            f"fixture {fi} placed at {start} on court {court}, not a legal slot"
        )

    # court turnaround (match+gap), movable vs movable AND vs immovable rows
    occupancy = [(court, start, fi) for fi, (court, start) in placed.items()]
    occupancy += [(court, start, f"existing:{k}") for k, (court, start) in enumerate(existing)]
    for a in range(len(occupancy)):
        for b in range(a + 1, len(occupancy)):
            court_a, start_a, name_a = occupancy[a]
            court_b, start_b, name_b = occupancy[b]
            if court_a != court_b:
                continue
            assert abs(start_a - start_b) >= dur_ms + gap_ms, (
                f"court turnaround violated on court {court_a}: {name_a}@{start_a} vs {name_b}@{start_b}"
            )

    # participant rest: an entrant's two matches are separated by match+rest
    by_entrant = {}
    for fi, (_court, start) in placed.items():
        for entrant in entrants_of[fi]:
            by_entrant.setdefault(entrant, []).append((start, fi))
    for entrant, rows in by_entrant.items():
        rows.sort()
        for a in range(len(rows)):
            for b in range(a + 1, len(rows)):
                (start_a, fi_a), (start_b, fi_b) = rows[a], rows[b]
                need = dur_ms + rest_by_division.get(division_of[fi_a], 0) * MIN_MS
                assert start_b - start_a >= need, (
                    f"rest violated for entrant {entrant}: fixture {fi_a}@{start_a} vs "
                    f"fixture {fi_b}@{start_b}, need {need}ms"
                )

    # order dependencies: `after` starts no earlier than `before` + match + its own rest
    checked_deps = 0
    for before_i, after_i in deps:
        if before_i not in placed or after_i not in placed:
            continue
        need = dur_ms + rest_by_division.get(division_of[after_i], 0) * MIN_MS
        assert placed[after_i][1] >= placed[before_i][1] + need, (
            f"dependency violated: fixture {after_i} must start >= fixture {before_i} + {need}ms"
        )
        checked_deps += 1
    assert checked_deps == len(deps), "a dependency pair went unplaced — that arm would be vacuous"

    # per-division day cap. Bucketed by the board's own `day_index`, not by
    # re-deriving `start // DAY_MS` — the model groups by the caller's day and
    # re-deriving here would let a wrong day_index satisfy both sides at once.
    day_of_start = {start: day for _court, start, day in grid_slots}
    per_division_day = {}
    for fi, (_court, start) in placed.items():
        key = (division_of[fi], day_of_start[start])
        per_division_day[key] = per_division_day.get(key, 0) + 1
    for (division, day), count in per_division_day.items():
        assert count <= day_cap_by_division[division], (
            f"day cap violated: division {division} day {day} has {count} > "
            f"{day_cap_by_division[division]}"
        )


# --- pinned/immovable rows, on a board where they actually contend ----------


def test_pinned_rows_are_not_overwritten_when_a_fixture_wants_the_slot():
    """The `existing` constraint family, on the only board that can test it.

    On `production_board()` this family is INERT, not merely unasserted: three
    pins against 8 320 grid slots and 37 movable fixtures means nothing ever
    competes for a pinned (court, tick). Measured, with the pinned-row fold
    deleted from `build_model`: **0 pin-involving violations with the
    constraint and 0 without it**, on both the zero-epoch and the real-epoch
    board. An assertion added to the production board therefore cannot catch
    the deletion — the corpus is blind, and no amount of asserting fixes a
    corpus.

    `pin_contended_board()` fixes the corpus instead. Five of its six
    (court, tick) pairs are pinned and three movable fixtures compete for the
    sixth, so the constraint is the ONLY thing keeping them off an occupied
    court. With it: one placement. Without it: three, two of them on top of a
    match already being played, reported OPTIMAL with `error` unset.
    """
    from placement_bench_boards import PIN_BOARD_FIXTURES, PIN_BOARD_FREE_SLOTS, pin_contended_board

    board = to_positional(pin_contended_board())
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps = board

    # The board genuinely contends — otherwise everything below is vacuous.
    assert PIN_BOARD_FIXTURES > PIN_BOARD_FREE_SLOTS
    assert len(fixtures) == PIN_BOARD_FIXTURES
    assert len(existing) == len(grid_slots) - PIN_BOARD_FREE_SLOTS
    assert not constraints["day_cap_by_division"], "a day cap would confound the pinned-row family"
    assert set(constraints["rest_by_division"].values()) == {0}, "rest would confound the pinned-row family"

    model = build_model(*board)
    outcome = solve(model, wall_seconds=5.0)
    detail = f"status={outcome.status} tiers={outcome.tiers_completed} board={sorted(outcome.assignments)}"

    assert outcome.tiers_completed == 4, detail  # tiny board; anything less means it did not run
    assert len(outcome.assignments) == PIN_BOARD_FREE_SLOTS, (
        "a movable fixture was placed into a pinned slot — the pinned-row fold in build_model "
        f"is not binding. {detail}"
    )

    pinned = set(existing)  # (court_index, start) -- PinnedRow carries no identity of its own
    for _fi, court, start in outcome.assignments:
        assert (court, start) not in pinned, f"fixture placed on top of an immovable row at {(court, start)}"

    # The one placement is on the one free slot, and it is a real slot.
    free = sorted({(court, start) for court, start, _day in grid_slots} - pinned)
    assert [(court, start) for _fi, court, start in outcome.assignments] == free, detail


def test_the_court_turnaround_gap_is_binding():
    """The court gap, on a board where it actually decides something.

    `gap_minutes` widens every court interval to `match + gap`. On
    `production_board()` that is almost never observable: 8 320 slots, 37
    fixtures and a day cap of one per division per day mean nothing is forced
    onto the same court close together, so narrowing the interval usually
    changes no placement. Measured over six runs at the production 8 s wall,
    the mutant that drops `gap_ms` from the width was caught **2 times in 6** —
    a coin flip, not a guard, and one that reads as a regression in CI.

    Here the gap is the only thing deciding how many fixtures fit:

        width = match + gap  ->  GAP_PROBE_CAPACITY            placements
        width = match alone  ->  GAP_PROBE_CAPACITY_WITHOUT_GAP placements

    T0 settles that in milliseconds and the answer does not depend on the
    wall, on how many tiers completed, or on the day cap.

    Run as a T0-ONLY chain (`tiers=(TIER_PLACED,)`, the prefix the bench also
    uses) rather than through `solve()`. That is not a shortcut, it is the
    question: "how many fit" is exactly what T0 proves, and `tiers_completed
    == 1` here means CP-SAT proved no board places more. Measured, the full
    chain on this board burns a 5 s wall and still returns `tiers_completed=1`
    — fourteen interchangeable fixtures over thirteen ticks is a symmetric
    packing problem and T1 cannot close its bound — so asserting the whole
    ladder here would have made a T0 fact hostage to a T1 proof that never
    lands.
    """
    from placement.objective import TIER_PLACED, run_tier_chain
    from placement_bench_boards import (
        GAP_PROBE_CAPACITY,
        GAP_PROBE_CAPACITY_WITHOUT_GAP,
        GAP_PROBE_FIXTURES,
        gap_contended_board,
    )

    board = to_positional(gap_contended_board())
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps = board

    # The board must genuinely contend, or every assertion below is vacuous.
    assert GAP_PROBE_CAPACITY < GAP_PROBE_CAPACITY_WITHOUT_GAP <= GAP_PROBE_FIXTURES
    assert len(fixtures) == GAP_PROBE_FIXTURES
    assert not existing and not deps, "pins or dependencies would confound the gap family"
    assert not constraints["day_cap_by_division"], "a day cap would confound the gap family"
    assert set(constraints["rest_by_division"].values()) == {0}, "rest would confound the gap family"

    model = build_model(*board)
    outcome = run_tier_chain(model, model.fixture_vars, wall_seconds=5.0, tiers=(TIER_PLACED,))
    detail = f"status={outcome.status} tiers={outcome.tiers_completed} board={sorted(outcome.assignments)}"

    # T0 PROVED its maximum — without this the count below could be a board the
    # clock cut short rather than the most that fits.
    assert outcome.tiers_completed == 1, detail
    assert outcome.status == "OPTIMAL", detail

    assert dict(outcome.objective_values)[TIER_PLACED] == GAP_PROBE_CAPACITY, (
        f"expected {GAP_PROBE_CAPACITY} placements; {GAP_PROBE_CAPACITY_WITHOUT_GAP} means the court "
        f"interval lost its turnaround gap. {detail}"
    )
    assert len(outcome.assignments) == GAP_PROBE_CAPACITY, detail

    # ...and say it directly, not only as a count.
    need = (constraints["match_minutes"] + constraints["gap_minutes"]) * MIN_MS
    placed = sorted((court, start) for _fi, court, start in outcome.assignments)
    for a in range(len(placed)):
        for b in range(a + 1, len(placed)):
            if placed[a][0] == placed[b][0]:
                assert abs(placed[a][1] - placed[b][1]) >= need, (
                    f"court turnaround violated on court {placed[a][0]}: {placed[a][1]} vs "
                    f"{placed[b][1]}, need {need}ms"
                )


def test_participant_rest_is_binding():
    """Participant rest, on a board where it actually decides something.

    Seven fixtures share one entrant across seven courts, so court exclusivity
    cannot bind and the per-entrant rest window is the only thing spacing them:

        rest enforced   ->  REST_PROBE_CAPACITY placements
        rest removed    ->  REST_PROBE_FIXTURES placements

    On `production_board()` the same mutant is caught only most of the time —
    re-measured over six runs, RED 5 of 6 at the production 8 s wall and 6 of 6
    at a 3 s wall. One miss in six is a flake that reads as a regression, and
    note the direction: the SHORTER wall was the more reliable killer, so this
    was never something a longer solve could fix.

    Kills both the "rest `AddNoOverlap` deleted" mutant and the "rest_ms
    zeroed" one, since either lets all seven seat.

    The rest itself now reaches `build_model` via `rule_groups`
    (`_board_positional.rule_groups_for`, one group covering every fixture in
    `rest_contended_board`'s single division) rather than `constraints.
    rest_by_division` directly: `division_rules` (proto field 10), the wire
    path that dict was fed through, is retired. `to_positional`'s own output
    still carries the DECLARED `rest_by_division` dict unchanged (used below
    only to compute the EXPECTED gap, not to bind anything).
    """
    from placement.objective import TIER_PLACED, run_tier_chain
    from placement_bench_boards import REST_PROBE_CAPACITY, REST_PROBE_FIXTURES, rest_contended_board

    raw_board = rest_contended_board()
    board = to_positional(raw_board)
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps = board
    rule_groups = rule_groups_for(raw_board)

    assert REST_PROBE_CAPACITY < REST_PROBE_FIXTURES == len(fixtures)
    assert num_courts >= REST_PROBE_FIXTURES, "court exclusivity must not be able to bind"
    assert not existing and not deps and not constraints["day_cap_by_division"]
    assert rule_groups, "the declared rest must have produced at least one rule group"
    shared = set.intersection(*(set(entrants) for entrants, _div in fixtures))
    assert len(shared) == 1, "every fixture must share exactly one entrant for rest to be the variable"
    (shared_entrant,) = shared

    model = build_model(*board, rule_groups=rule_groups)
    outcome = run_tier_chain(model, model.fixture_vars, wall_seconds=5.0, tiers=(TIER_PLACED,))
    detail = f"status={outcome.status} tiers={outcome.tiers_completed} board={sorted(outcome.assignments)}"

    assert outcome.tiers_completed == 1, detail
    assert outcome.status == "OPTIMAL", detail
    assert dict(outcome.objective_values)[TIER_PLACED] == REST_PROBE_CAPACITY, (
        f"expected {REST_PROBE_CAPACITY} placements; {REST_PROBE_FIXTURES} means the participant-rest "
        f"window is not binding. {detail}"
    )

    # ...and directly: the shared entrant's matches are match+rest apart.
    only_division = next(iter(constraints["rest_by_division"]))
    need = (constraints["match_minutes"] + constraints["rest_by_division"][only_division]) * MIN_MS
    starts = sorted(start for _fi, _court, start in outcome.assignments)
    for earlier, later in zip(starts, starts[1:]):
        assert later - earlier >= need, (
            f"rest violated for entrant {shared_entrant}: {earlier} vs {later}, need {need}ms"
        )


# --- an unplaceable board must not report a NEGATIVE makespan ---------------


def test_an_empty_board_reports_a_non_negative_makespan():
    """`mk_hi - mk_lo` is unpinned when nothing is placed, and T1 MINIMISES it.

    Both squeeze constraints are `OnlyEnforceIf(placed[i])`, so with an empty
    board `mk_lo` and `mk_hi` float freely over `[0, max_end]` and minimising
    their difference drives `mk_hi` to 0 and `mk_lo` to `max_end`. The chain
    then proves that optimal and publishes it. Measured 6/6, one fixture made
    unplaceable by a self-dependency:

        OPTIMAL, placed=0, error unset,
        objective_values=[('placed', 0), ('makespan', -1767258600000), ...]

    A negative epoch-shaped number on the wire, presented as a proved optimum.
    `build.ts` compares tier values against its own board metrics, and no
    caller has any reason to defend against a negative duration.

    Fixed in the model rather than at the ACL: a duration cannot be negative is
    an invariant of the term, so every consumer — the bench, the tier chain,
    the wire — gets the same answer. An empty board has a makespan of zero.

    Self-dependency is DELIBERATELY still accepted (an unplaceable fixture
    shows up as a lower `placed`, which is visible); it is only the negative
    number that had to go.
    """
    num_courts = 1
    grid_slots = [(0, _STRADDLE_A, 0), (0, _STRADDLE_A + 40 * MIN_MS, 0)]
    fixtures = [([0, 1], 0)]
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 10,
        "rest_by_division": {0: 0},
        "day_cap_by_division": {},
    }
    # A self-dependency (fixture 0 depends on itself) makes it unplaceable.
    model = build_model(fixtures, num_courts, grid_slots, 40, constraints, [], [(0, 0)])
    outcome = solve(model, wall_seconds=5.0)

    assert outcome.assignments == [], "the self-dependency should make fixture 0 unplaceable"
    reported = dict(outcome.objective_values)
    assert reported["placed"] == 0
    assert reported["makespan"] >= 0, (
        f"a negative duration reached the objective values: {outcome.objective_values}"
    )
    assert reported["makespan"] == 0, (
        f"an empty board has no makespan at all, got {reported['makespan']}"
    )


def test_a_placed_board_still_reports_its_real_makespan():
    """The clamp must not have flattened the term. Two fixtures forced onto two
    different ticks by a single court give a makespan of exactly one tick gap
    plus one match."""
    num_courts = 1
    step = 40 * MIN_MS
    grid_slots = [(0, _STRADDLE_A + k * step, 0) for k in range(2)]
    fixtures = [([0, 1], 0), ([2, 3], 0)]
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 10,
        "rest_by_division": {0: 0},
        "day_cap_by_division": {},
    }
    model = build_model(fixtures, num_courts, grid_slots, 40, constraints, [], [])
    outcome = solve(model, wall_seconds=5.0)

    assert len(outcome.assignments) == 2
    assert dict(outcome.objective_values)["makespan"] == step + 30 * MIN_MS


def test_model_built_debug_event_reports_fixture_and_court_counts():
    """`build_model` had no logging at all before this — the ONLY visibility
    into how big a board the CP-SAT model ended up encoding. DEBUG, not INFO:
    this runs on the hot, latency-sensitive path and `PLACEMENT_LOG_LEVEL`
    defaults to INFO in production, so the event costs nothing there; it only
    fires once an operator has explicitly turned the level down to look.

    `capture_logs()` overrides the processor chain but not the filtering
    level (`wrapper_class`), so a DEBUG event is invisible to it under any
    config that filters DEBUG out — production's default INFO, for one. The
    level is pinned to DEBUG here and restored afterwards so this test's
    result does not depend on which other test last touched global structlog
    configuration.
    """
    num_courts = 1
    step = 40 * MIN_MS
    grid_slots = [(0, _STRADDLE_A + k * step, 0) for k in range(2)]
    fixtures = [([0, 1], 0), ([2, 3], 0)]
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 10,
        "rest_by_division": {0: 0},
        "day_cap_by_division": {},
    }

    old_wrapper_class = structlog.get_config()["wrapper_class"]
    structlog.configure(wrapper_class=structlog.make_filtering_bound_logger(logging.DEBUG))
    try:
        with structlog.testing.capture_logs() as captured:
            build_model(fixtures, num_courts, grid_slots, 40, constraints, [], [])
    finally:
        structlog.configure(wrapper_class=old_wrapper_class)

    events = [entry for entry in captured if entry["event"] == "model_built"]
    assert len(events) == 1, f"expected exactly one model_built event, got {captured}"
    entry = events[0]
    assert entry["fixtures"] == 2
    assert entry["courts"] == num_courts
    assert entry["existing"] == 0
    assert entry["dependencies"] == 0
    assert entry["rule_groups"] == 0


# --- T1's span now includes pinned rows (#511) -------------------------------

_T1_PIN_ANCHOR = 1_800_000_000_000  # arbitrary positive ms epoch, see _GROUP_ANCHOR below


def test_pins_join_the_makespan_span_so_the_solver_places_near_them():
    """THE LOAD-BEARING TEST for #511. A naive "pin on day 0, assert movables
    land on day 0" board is a TIE without the fix -- the movable-only span is
    identical either way, and CP-SAT is nondeterministic, so it would pass by
    luck roughly half the time even with the fix reverted. This board is
    built so the two arms are STRICTLY ordered in BOTH directions instead.

    One pin, two movable fixtures, two candidate placements:
      * "day 0": the pin's own instant, plus a second admissible tick 6 hours
        later on a different court -- FAR APART, so the movable-only span
        there is wide even before the pin is considered at all.
      * "day 1": a single admissible instant, offered on BOTH courts, a full
        day after the pin -- ADJACENT (colocated), so the movable-only span
        there is the narrowest one can be: one match duration.

    Computed spans (dur_ms = 1_800_000, one match, checkable by eye):
      WITHOUT the fix (movable-only, pin excluded):
        day 0: A0_2 + dur - A0_1 = 6h + dur  = 23_400_000 ms
        day 1: dur                           =  1_800_000 ms  <- narrower, wins
      WITH the fix (pin included):
        day 0: unchanged -- the pin coincides with A0_1, adding nothing
                                              = 23_400_000 ms  <- now the winner
        day 1: (B + dur) - P = DAY_MS + dur  = 88_200_000 ms  <- a whole day worse

    T0 ties either way (both movables fit on either day), so T1 alone decides
    -- and T1 (minimised) strictly prefers day 1 without the fix and strictly
    prefers day 0 with it. Neither arm is a tie, so this cannot pass by
    nondeterministic luck the way a "pin on day 0, assert day 0" board would.
    Measured 6/6 red with the fix reverted (see task report).
    """
    dur_ms = 30 * MIN_MS
    six_hours = 6 * 60 * MIN_MS
    pin_start = _T1_PIN_ANCHOR
    day0_far_tick = _T1_PIN_ANCHOR + six_hours
    day1_tick = _T1_PIN_ANCHOR + DAY_MS

    num_courts = 2
    grid_slots = [
        (1, pin_start, 0),  # day 0, court 1 -- same instant as the pin (court 0)
        (1, day0_far_tick, 0),  # day 0, court 1 -- 6h later: FAR APART
        (0, day1_tick, 1),  # day 1, both courts -- ADJACENT (colocated)
        (1, day1_tick, 1),
    ]
    fixtures = [([0, 1], 0), ([2, 3], 0)]
    existing = [(0, pin_start)]
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 0,
        "rest_by_division": {0: 0},
        "day_cap_by_division": {},
    }

    model = build_model(fixtures, num_courts, grid_slots, 30, constraints, existing, [])
    outcome = solve(model, wall_seconds=5.0)
    detail = f"status={outcome.status} assignments={sorted(outcome.assignments)}"

    assert len(outcome.assignments) == 2, detail
    starts = {start for _fixture, _court, start in outcome.assignments}
    assert starts == {pin_start, day0_far_tick}, (
        f"expected both movables on day 0 (the pin's tick + the far tick), got {detail}"
    )


def test_a_lone_pin_stops_the_makespan_from_collapsing_to_zero():
    """The hunk's own comment claims the pin bounds "strengthen the `mk_hi >=
    mk_lo` clamp below on any board with a pin -- `mk_lo` and `mk_hi` can no
    longer both float when nothing movable is placed." Verified directly: no
    movable fixtures at all (fixtures=[]), one pin.

    Without the fix this is `test_an_empty_board_reports_a_non_negative_makespan`'s
    scenario restated with a pin present: nothing constrains `mk_lo`/`mk_hi`
    beyond the `mk_hi >= mk_lo` clamp (Task 05c), so T1 collapses them to the
    same point and the reported span is 0 -- degenerate, and a pin sitting
    right there does nothing to stop it, because nothing reads `existing` in
    the T1 section at all yet.

    With the fix, `mk_lo <= P` and `mk_hi >= P + dur_ms` are hard bounds
    regardless of placement. The sole grid slot sits AT `P`, so
    `max_end == P + dur_ms` -- `mk_hi`'s own domain upper bound forces it to
    exactly `P + dur_ms`, and minimising `mk_hi - mk_lo` then pushes `mk_lo`
    up to its only upper bound, `P`. The span is therefore provably exactly
    `dur_ms`, not just "at least" it (verified: 1_800_000 both times run), but
    the assertion below only claims the non-degenerate half, matching what
    the comment actually promises rather than over-claiming from one board.
    """
    num_courts = 1
    dur_ms = 30 * MIN_MS
    pin_start = 5_000_000
    grid_slots = [(0, pin_start, 0)]  # sole admissible start == the pin's own
    fixtures: list = []
    existing = [(0, pin_start)]
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 0,
        "rest_by_division": {},
        "day_cap_by_division": {},
    }

    model = build_model(fixtures, num_courts, grid_slots, 30, constraints, existing, [])
    outcome = solve(model, wall_seconds=5.0)

    reported = dict(outcome.objective_values)
    assert reported["placed"] == 0
    assert reported["makespan"] >= dur_ms, (
        f"a lone pin should have forced a non-degenerate span, got {outcome.objective_values}"
    )


def test_an_in_range_pin_does_not_cost_a_movable_its_placement():
    """T0 (placed count) is lexicographically first, so adding `existing` to
    the T1 span must not cost placements. A board where everything fits
    places the same number of fixtures with the pin present as without it.

    NOT falsifiable by reverting the 3-line loop, and that is reported here
    rather than hidden: verified (scratch script, not this test) that on this
    board the assignment set is BYTE-IDENTICAL with the loop present and
    reverted. T0's objective (`placed_sum`) never references `mk_lo`/`mk_hi`,
    and the new pin bounds never reference `start[i]`/`placed[i]` either --
    the two families share no variable, so the only way reverting them could
    ever change T0's optimum is if they render `mk_lo`/`mk_hi` themselves
    infeasible against their OWN declared domain (`max_end`, computed from
    `grid_slots` alone -- never from `existing`, see line ~862).

    That mechanism is real, just not on an in-range board: a pin whose
    `start_at_ms` exceeds `max(admissible_starts)` makes `mk_hi >=
    existing_start + dur_ms` unsatisfiable against `mk_hi`'s own upper bound,
    and `placement.schema._validated_existing` (schema.py:369-412) does not
    bound-check a pin's start against the grid at all. Confirmed empirically
    (scratch script, not committed here, reported to the task controller): an
    otherwise-solvable one-fixture board went from OPTIMAL/1-placed to
    INFEASIBLE/0-placed purely by adding the fix's two bounds for a pin 9M ms
    past the grid's own last tick -- with the loop reverted the same board
    stayed OPTIMAL/1-placed. That is a genuine hole in the #511 hunk, out of
    this task's scope to fix, and it is why this test's own claim -- "an
    in-range pin is free" -- is written as a positive assertion rather than a
    reverted one: reverting only ever matters in the OUT-of-range case, where
    the CURRENT tree is the one that regresses, not the reverted one.
    """
    dur_ms = 30 * MIN_MS
    anchor = 1_000_000_000
    grid_slots = [(0, anchor + k * dur_ms, 0) for k in range(3)]
    fixtures = [([0, 1], 0), ([2, 3], 0)]
    existing = [(0, anchor)]  # in-range: coincides with the grid's own earliest tick
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 0,
        "rest_by_division": {0: 0},
        "day_cap_by_division": {},
    }

    model = build_model(fixtures, 1, grid_slots, 30, constraints, existing, [])
    outcome = solve(model, wall_seconds=5.0)

    assert len(outcome.assignments) == 2, (
        f"both movables should have fit around the in-range pin: "
        f"status={outcome.status} assignments={outcome.assignments}"
    )


# --- the day cap binds on the CALLER's day, not on a UTC boundary -----------

#: A UTC-midnight-straddling session, in `build_model`'s parameter shape.
#:
#: 2026-01-01T23:00:00Z and 2026-01-02T01:00:00Z. For an org two hours ahead of
#: UTC those are 01:00 and 03:00 on the SAME local morning — one session day,
#: and one day-cap bucket. `start_ms // DAY_MS` puts them in two.
_STRADDLE_A = 1_767_308_400_000  # 2026-01-01T23:00:00Z
_STRADDLE_B = 1_767_315_600_000  # 2026-01-02T01:00:00Z


def _straddling_board(day_index_of):
    """Two ticks either side of UTC midnight, two courts, two `d1`-equivalent
    (division 0) fixtures capped at one per day. Court capacity cannot bind
    (two courts, two ticks, two fixtures) and entrants are disjoint, so the
    day cap is the only thing deciding how many are placed — a COUNT that T0
    proves in milliseconds, independent of the wall and of which tiers ran.

    The cap reaches `build_model` via `rule_groups` (one group covering both
    fixtures, `max_fixtures_per_day=1`) rather than `constraints.day_cap_by_
    division`: `division_rules` (proto field 10), the wire path that dict was
    fed through, is retired -- see `placement.schema`'s module docstring.
    Returned as an 8-tuple; `build_model(*board)` passes `rule_groups`
    positionally, matching `placement.main`'s own all-positional call.
    """
    num_courts = 2
    grid_slots = [
        (c, start, day_index_of(start)) for c in (0, 1) for start in (_STRADDLE_A, _STRADDLE_B)
    ]
    fixtures = [([0, 1], 0), ([2, 3], 0)]
    constraints = {"match_minutes": 30, "gap_minutes": 0}
    rule_groups = [([0, 1], None, 1)]  # both fixtures, no rest rule, cap 1
    return fixtures, num_courts, grid_slots, 60, constraints, [], [], rule_groups


def test_the_day_cap_groups_by_the_callers_day_index_not_by_utc():
    """One local day is one cap bucket, whatever UTC thinks.

    `start_ms // DAY_MS` is a UTC day. The deploy region is `lhr` and
    Europe/London is UTC+1 for about seven months of the year, and orgs further
    out are worse: for UTC+10, a 09:00 local match and a 19:00 local match on
    the same day land in DIFFERENT UTC buckets, so a cap of one per day admits
    two. Same class as this repo's `settings.tz`-vs-`settings.orgTz` bug.

    The solver stays timezone-agnostic by design (timezones-as-policy are
    outside this bounded context): the caller, which already knows the org's
    zone, resolves each slot to its local calendar day and sends the integer.

    Both ticks carry `day_index = 0`, so the cap admits exactly ONE. Deriving
    the day from the timestamp instead admits TWO, and reports it OPTIMAL.
    """
    board = _straddling_board(lambda _start: 0)
    model = build_model(*board)
    outcome = solve(model, wall_seconds=3.0)

    assert outcome.tiers_completed >= 1, "T0 itself did not complete — the count below is vacuous"
    assert len(outcome.assignments) == 1, (
        f"expected the cap to admit one fixture on the single local day, got "
        f"{outcome.assignments}"
    )


def test_two_day_indices_over_one_utc_day_give_two_buckets():
    """The converse, so the test above cannot pass by the cap simply being
    stricter. Same two ticks, same cap — but the caller calls them two days, so
    two fixtures fit. Without both halves, `on_day[i][d] = 0` for every d would
    satisfy the first assertion and nothing would notice.
    """
    board = _straddling_board(lambda start: 0 if start == _STRADDLE_A else 1)
    grid_slots = board[2]
    day_of_start = {start: day for _court, start, day in grid_slots}
    model = build_model(*board)
    outcome = solve(model, wall_seconds=3.0)

    assert outcome.tiers_completed >= 1
    assert len(outcome.assignments) == 2, (
        f"two declared days must give two cap buckets, got {outcome.assignments}"
    )
    # And they must land on ONE DAY EACH, not merely number two. The count
    # alone cannot see a fixture claiming a day it is not on: total capacity is
    # `days * cap` however the claims are distributed, so dropping the upper
    # range bound leaves the count at 2 while both fixtures sit on the day-1
    # tick and one of them books day 0's allowance. T1 actively drives that —
    # a shorter makespan wants both on the same tick.
    assert sorted(day_of_start[start] for _fi, _court, start in outcome.assignments) == [0, 1], (
        f"the cap of one per day was satisfied by a day CLAIM, not by a placement: "
        f"{[(fi, day_of_start[start]) for fi, _court, start in outcome.assignments]}"
    )


def test_rejects_a_start_declared_on_two_different_days():
    """The same tick on two courts must carry the same day. Two slots
    disagreeing about which day one instant belongs to is not a board the
    caller can have meant, and the range encoding below it assumes days
    partition the admissible starts."""
    num_courts = 2
    grid_slots = [(0, _STRADDLE_A, 0), (1, _STRADDLE_A, 1)]
    fixtures = [([0, 1], 0)]
    constraints = {"match_minutes": 30, "gap_minutes": 0, "rest_by_division": {}, "day_cap_by_division": {}}
    with pytest.raises(ValueError, match="day_index"):
        build_model(fixtures, num_courts, grid_slots, 60, constraints, [], [])


def test_rejects_interleaved_day_indices():
    """Days must occupy disjoint stretches of the timeline.

    The cap is encoded as `on_day[i][d] => lo_d <= start[i] <= hi_d`, two
    linear constraints rather than a 64-value domain per fixture per day —
    which is exact only while no other day's ticks fall inside `[lo_d, hi_d]`.
    A caller that interleaves them would get a cap that binds on the wrong
    fixtures, silently, so the model refuses to be built instead."""
    num_courts = 1
    middle = (_STRADDLE_A + _STRADDLE_B) // 2
    grid_slots = [(0, _STRADDLE_A, 0), (0, middle, 1), (0, _STRADDLE_B, 0)]
    fixtures = [([0, 1], 0)]
    constraints = {"match_minutes": 30, "gap_minutes": 0, "rest_by_division": {}, "day_cap_by_division": {}}
    with pytest.raises(ValueError, match="day_index"):
        build_model(fixtures, num_courts, grid_slots, 60, constraints, [], [])


# --- C4: a pinned row consumes its day's allowance (rule_groups) -----------
#
# `day_cap_by_division` capped movable fixtures only; a pinned row on a
# capped day was not counted at all, so an organiser could pin a day full and
# the solver would add another cap's worth on top of it -- measured on a real
# staging board: day cap 7, six matches pinned on one day, the solver placed
# seven more (thirteen total). `rule_groups` / `pinned_rule_group_indices`
# (already parsed and validated by `placement.schema`, task #21) generalise the
# cap past division scope and carry the pin-to-group attribution the old
# shape had no field for. These are domain tests against `build_model`
# directly, in plain Python, per `_RULES.md` section 6.

_GROUP_ANCHOR = 1_800_000_000_000  # arbitrary positive ms epoch; only offsets from here matter


def test_a_pinned_row_consumes_its_days_allowance():
    """THE LOAD-BEARING TEST. A day capped at 3, with 2 pins already on it
    counting against the same rule group, and 3 movable fixtures wanting the
    same (only) day -- more than the `cap - pinned = 1` remaining.

    Before this change (`rule_groups` unread by `build_model`): the cap
    applies to movable fixtures alone, admitting up to the FULL cap of 3 on
    top of the 2 pins -- 5 total on a day capped at 3. After: at most 1
    movable fixture joins the 2 pins, for exactly 3 -- the cap, INCLUDING the
    pins. An assertion over movable placements alone would not prove the pins
    were ever counted; the number that matters is the one on the day.
    """
    num_courts = 2
    step = 30 * MIN_MS
    # 4 ticks x 2 courts = 8 (court, tick) cells, all day 0 -- plenty of court
    # capacity so the DAY CAP is the only thing that can be binding here.
    grid_slots = [(c, _GROUP_ANCHOR + k * step, 0) for c in (0, 1) for k in range(4)]
    # 3 movable fixtures, disjoint entrants, so participant rest cannot bind.
    fixtures = [([0, 1], 0), ([2, 3], 0), ([4, 5], 0)]
    # 2 pins, different courts/ticks from each other (so they do not collide
    # with one another), both counting against rule group 0.
    existing = [(0, _GROUP_ANCHOR), (1, _GROUP_ANCHOR)]
    pinned_rule_group_indices = [[0], [0]]
    rule_groups = [([0, 1, 2], None, 3)]  # cap = 3, no rest rule
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 0,
        "rest_by_division": {0: 0},
        # Deliberately empty: this test isolates the rule_groups mechanism.
        # "not applied twice" (division AND group at once) is a separate test.
        "day_cap_by_division": {},
    }

    model = build_model(
        fixtures,
        num_courts,
        grid_slots,
        30,
        constraints,
        existing,
        [],
        rule_groups=rule_groups,
        pinned_rule_group_indices=pinned_rule_group_indices,
    )
    outcome = solve(model, wall_seconds=5.0)
    detail = f"status={outcome.status} assignments={sorted(outcome.assignments)}"

    assert outcome.status in ("OPTIMAL", "FEASIBLE"), detail
    assert len(outcome.assignments) == 1, (
        f"expected exactly cap(3) - pinned(2) = 1 movable fixture admitted, got {detail}"
    )
    # The count that actually matters: pins INCLUDED. An assertion over
    # movable placements alone would look identical whether or not the pins
    # were ever read -- with day_cap_by_division also empty, an
    # implementation that silently ignores rule_groups admits all 3 movable
    # fixtures (no cap at all), which this line catches too: 2 pins + 3
    # movable = 5 != 3.
    total_on_day = len(existing) + len(outcome.assignments)
    assert total_on_day == 3, f"day 0 carries {total_on_day} matches against a cap of 3: {detail}"


def test_a_pin_off_lattice_counts_against_nothing():
    """A pin's `start_at_ms` is an organiser's manual placement, not a grid
    tick -- nothing requires it to land inside any day's admissible range at
    all. `day_bounds` maps a day to [lo, hi] over ADMISSIBLE STARTS; a pin
    outside every day's range must count against no group's cap, deliberately
    -- not a fallthrough, and not attributed to the nearest day by guesswork.

    Cap of 1, the group has exactly one movable fixture wanting the day, and
    one pin sitting well before the day's earliest tick. If the pin wrongly
    counted against day 0 the remaining allowance would be 0 and the fixture
    could never be placed; correctly ignored, the full cap of 1 is available.
    """
    num_courts = 2
    step = 30 * MIN_MS
    grid_slots = [(c, _GROUP_ANCHOR + k * step, 0) for c in (0, 1) for k in range(2)]
    fixtures = [([0, 1], 0)]
    # Court 1 (not 0), 10 minutes before the day's earliest tick -- outside
    # [lo, hi] and off the court the movable fixture will actually need.
    existing = [(1, _GROUP_ANCHOR - 10 * MIN_MS)]
    pinned_rule_group_indices = [[0]]
    rule_groups = [([0], None, 1)]
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 0,
        "rest_by_division": {0: 0},
        "day_cap_by_division": {},
    }

    # Must not raise -- an off-lattice pin is a legitimate board, not a defect.
    model = build_model(
        fixtures,
        num_courts,
        grid_slots,
        30,
        constraints,
        existing,
        [],
        rule_groups=rule_groups,
        pinned_rule_group_indices=pinned_rule_group_indices,
    )
    outcome = solve(model, wall_seconds=5.0)

    assert len(outcome.assignments) == 1, (
        f"the off-lattice pin consumed the day's allowance when it should not have: "
        f"status={outcome.status} assignments={outcome.assignments}"
    )


def test_pins_already_over_the_cap_clamp_instead_of_going_infeasible():
    """The hard case: 2 pins already on a day capped at 1 -- the cap was
    already violated before the solver ran anything. `max(0, cap - pinned)`
    clamps to 0 rather than handing `model.Add` a NEGATIVE bound, which would
    make the WHOLE model INFEASIBLE (a sum of booleans can never be <= a
    negative number) and return no board at all.

    Same call this repo already made in
    `apps/web/src/server/usecases/schedule.ts:798` (`assertNoNewBlocking`):
    refuse only what a change introduces or worsens, so an already-imperfect
    board stays editable instead of trapping its owner. Pins are immovable by
    definition -- the solver cannot repair the violation -- so refusing the
    whole solve would give the organiser nothing to act on, just a service
    that stopped answering.
    """
    num_courts = 2
    step = 30 * MIN_MS
    grid_slots = [(c, _GROUP_ANCHOR + k * step, 0) for c in (0, 1) for k in range(2)]
    fixtures = [([0, 1], 0)]  # wants the only day this board has
    existing = [(0, _GROUP_ANCHOR), (1, _GROUP_ANCHOR)]  # 2 pins, cap is 1
    pinned_rule_group_indices = [[0], [0]]
    rule_groups = [([0], None, 1)]  # cap = 1, already exceeded by the pins alone
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 0,
        "rest_by_division": {0: 0},
        "day_cap_by_division": {},
    }

    model = build_model(
        fixtures,
        num_courts,
        grid_slots,
        30,
        constraints,
        existing,
        [],
        rule_groups=rule_groups,
        pinned_rule_group_indices=pinned_rule_group_indices,
    )
    outcome = solve(model, wall_seconds=5.0)

    assert outcome.status != "INFEASIBLE", (
        f"an already-over-cap pin set made the whole solve refuse, not just that day: "
        f"status={outcome.status}"
    )
    assert outcome.status in ("OPTIMAL", "FEASIBLE"), outcome.status
    # The pre-existing violation stands (2 pins on a cap of 1); the solver
    # adds nothing further on top of it -- the movable fixture has nowhere
    # else to go (this board has only one day) and is correctly left unplaced.
    assert outcome.assignments == [], (
        f"the clamp should leave no room for the movable fixture: {outcome.assignments}"
    )


# `division_rules` (proto field 10) is retired, and with it `day_cap_by_
# division` -- `constraints` carries only `match_minutes`/`gap_minutes` now
# (`placement.schema`'s module docstring), so `build_model` has no second
# day-cap source left to prefer `rule_groups` OVER. Two tests used to live
# here: a caller with `rule_groups=[]` seeing the old division-only cap
# apply obliviously to a pin, and `rule_groups` winning when BOTH shapes were
# present. Neither scenario can occur any more -- an empty `rule_groups`
# now caps nothing at all (see `model.py` section 9's own comment), which
# is exactly what `test_a_caller_without_rule_groups_gets_the_old_uncounted_
# pin_behaviour` became once `day_cap_by_division` stopped being a thing a
# caller could send.


# --- C6: a pinned row joins its entrants' participant-rest groups -----------
#
# `by_entrant` used to be built by walking `fixtures` (movable rows) alone, so
# two PINNED rows sharing an entrant were invisible to section 6 no matter
# what rest was owed -- a board z3 proves INFEASIBLE came back OPTIMAL.
# `pinned_entrant_indices` (#21, parallel to `existing`) carries the identity
# section 6 was missing; a pin's own rest is the max `min_rest_minutes` over
# the rule groups it counts against (`pinned_rule_group_indices`).


def test_two_pinned_rows_sharing_an_entrant_conflict_under_group_rest():
    """THE C6 DEFECT, closed. Two PINNED rows -- no movable fixture on the
    board at all -- thirty minutes apart on DIFFERENT courts, sharing one
    entrant, under a rule group requiring thirty minutes' rest.

    Different courts, so section 7's court-overlap half cannot be what trips
    this; no movable fixtures at all, so there is nothing else on the board
    that could produce INFEASIBLE. The only path left to it is section 6's
    pin-rest fold this task adds: each pin becomes a FIXED interval sized
    dur_ms + 30 minutes, both folded into entrant 0's group, and two FIXED
    intervals thirty minutes apart at that width cannot both hold.

    Before this change: OPTIMAL, unconditionally -- the pair never shared a
    group. Same board `schedule-solver-telemetry.test.ts`'s tripwire drives
    over the wire (two cards, 30 minutes apart, 30 minutes' rest, sharing an
    entrant).
    """
    num_courts = 2
    grid_slots = [
        (0, _GROUP_ANCHOR, 0),
        (1, _GROUP_ANCHOR, 0),
        (0, _GROUP_ANCHOR + 30 * MIN_MS, 0),
        (1, _GROUP_ANCHOR + 30 * MIN_MS, 0),
    ]
    fixtures: list[tuple[list[int], int]] = []
    existing = [(0, _GROUP_ANCHOR), (1, _GROUP_ANCHOR + 30 * MIN_MS)]
    pinned_entrant_indices = [[0], [0]]
    pinned_rule_group_indices = [[0], [0]]
    rule_groups = [([], 30, None)]  # 30 minutes' rest, no cap, no movable fixtures
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 0,
        "rest_by_division": {},
        "day_cap_by_division": {},
    }

    model = build_model(
        fixtures,
        num_courts,
        grid_slots,
        30,
        constraints,
        existing,
        [],
        rule_groups=rule_groups,
        pinned_rule_group_indices=pinned_rule_group_indices,
        pinned_entrant_indices=pinned_entrant_indices,
    )
    outcome = solve(model, wall_seconds=5.0)

    assert outcome.status == "INFEASIBLE", (
        f"two pins 30 minutes apart sharing an entrant, 30 minutes' rest owed, must be proven "
        f"impossible together: status={outcome.status} assignments={outcome.assignments}"
    )


def test_two_pinned_rows_sharing_an_entrant_stay_independent_without_rule_groups():
    """The converse, so the test above cannot pass by `existing` having
    somehow become load-bearing unconditionally. Identical board, but the
    caller has not upgraded to `rule_groups` -- `pinned_entrant_indices` is
    sent (a caller could populate it on the old contract shape too) but
    `rule_groups` itself is empty, so there is no rest figure to resolve a
    pin's own rest from. Section 6 must stay a no-op for pins here, exactly
    today's behaviour, matching the fallback `test_a_caller_without_rule_
    groups_gets_the_old_uncounted_pin_behaviour` proves for the day-cap half.
    """
    num_courts = 2
    grid_slots = [
        (0, _GROUP_ANCHOR, 0),
        (1, _GROUP_ANCHOR, 0),
        (0, _GROUP_ANCHOR + 30 * MIN_MS, 0),
        (1, _GROUP_ANCHOR + 30 * MIN_MS, 0),
    ]
    fixtures: list[tuple[list[int], int]] = []
    existing = [(0, _GROUP_ANCHOR), (1, _GROUP_ANCHOR + 30 * MIN_MS)]
    constraints = {
        "match_minutes": 30,
        "gap_minutes": 0,
        "rest_by_division": {},
        "day_cap_by_division": {},
    }

    model = build_model(
        fixtures,
        num_courts,
        grid_slots,
        30,
        constraints,
        existing,
        [],
        rule_groups=[],
        pinned_rule_group_indices=[],
        pinned_entrant_indices=[[0], [0]],
    )
    outcome = solve(model, wall_seconds=5.0)

    assert outcome.status != "INFEASIBLE", (
        f"a caller still on the previous contract shape (no rule_groups) must keep today's "
        f"behaviour -- pins uncounted for rest: status={outcome.status}"
    )


# --- a movable fixture's OWN rest folds in rule_groups (module docstring,
# --- "A SEVENTH is CLOSED") -- the ONLY source now that `division_rules`
# --- (proto field 10) and the `rest_by_division` dict key it fed are retired
#
# `rule_groups[].min_rest_minutes` was already read for a PIN's own rest (C6,
# above) and for a rule group's day cap (C4), before it was also read for a
# movable fixture's own width. The verifier's `hardRestMinutesFor`
# (`calendar.ts`) was already resolving a fixture's own typed rest as the MAX
# over every covering rule, so a placer that did not fold `rule_groups` in at
# all could ship a board the verifier then rejected -- the recurring
# placer/verifier fork this programme keeps producing.
#
# All boards below share one two-tick, two-court shape: fixtures 0 and 1
# both cover entrant 0 (so participant rest is the only thing that can ever
# separate them -- court exclusivity cannot bind, matching
# `rest_contended_board`'s own convention), and the two ticks are
# `match_minutes` + a chosen "slack" apart. Run as a T0-ONLY chain
# (`tiers=(TIER_PLACED,)`), the same technique `test_participant_rest_is_
# binding` and `test_the_court_turnaround_gap_is_binding` already use: the
# PLACED COUNT is a PROVEN optimum on a board this small, not a matter of
# which of several equally-good boards CP-SAT's nondeterministic search
# happens to land on -- so unlike a test asserting WHICH tick was chosen,
# these are not a coin flip. Still measured 6x each per `_RULES.md` section
# 6b's own standing advice for anything CP-SAT decides ("a small
# deterministic board beats a large stochastic one every time"); the tally is
# reported in the task report rather than asserted here.


def _rest_probe_board(rule_groups, slack_minutes):
    """Two fixtures sharing entrant 0, two ticks `match_minutes +
    slack_minutes` apart. Both fit iff `slack_minutes >= ` the resolved
    binding rest; otherwise only one does -- see each test's own docstring
    for why its `slack_minutes` was chosen.
    """
    t0 = _GROUP_ANCHOR
    t1 = t0 + (30 + slack_minutes) * MIN_MS
    num_courts = 2
    grid_slots = [(c, t, 0) for c in (0, 1) for t in (t0, t1)]
    fixtures = [([0], 0), ([0], 0)]
    constraints = {"match_minutes": 30, "gap_minutes": 0}
    return build_model(
        fixtures, num_courts, grid_slots, 30, constraints, [], [], rule_groups=rule_groups
    )


def _rest_probe_capacity(model):
    from placement.objective import TIER_PLACED, run_tier_chain

    outcome = run_tier_chain(model, model.fixture_vars, wall_seconds=5.0, tiers=(TIER_PLACED,))
    detail = f"status={outcome.status} tiers={outcome.tiers_completed} board={sorted(outcome.assignments)}"
    assert outcome.tiers_completed == 1, detail
    assert outcome.status == "OPTIMAL", detail
    return len(outcome.assignments), detail


def test_a_covering_rule_groups_min_rest_minutes_binds():
    """A rule group's `min_rest_minutes` (45) covering both fixtures, with 30
    minutes' slack between the two ticks:

        no rest at all: 0 <= 30 slack     -> BOTH fit, capacity 2
        group's rest 45 > 30 slack        -> only ONE fits, capacity 1

    Genuinely red without the fold: with the loop over `rule_groups` deleted,
    `rest_ms` stays at its bare-0 starting value and the solver proves 2, not
    1 (see task report for the actual failure text).
    """
    model = _rest_probe_board(rule_groups=[([0, 1], 45, None)], slack_minutes=30)
    capacity, detail = _rest_probe_capacity(model)
    assert capacity == 1, (
        f"expected the group's 45-minute rest to bind, giving capacity 1: {detail}"
    )


def test_a_larger_covering_rule_groups_rest_is_not_overridden_by_a_smaller_one():
    """The MAX claim, discriminated from a last-write-wins bug. TWO rule
    groups cover the same fixtures -- 45 minutes' rest, then 15 -- and the
    fold must keep the LARGER regardless of which was processed last. 20
    minutes' slack (deliberately between 15 and 45) is what makes this board
    discriminate a MAX fold from an assignment (`=`) that lets whichever
    group is walked last win:

        correctly max(45, 15) = 45 > 20 slack  -> only ONE fits, capacity 1
        wrongly last-write-wins, 15 <= 20 slack -> BOTH fit, capacity 2

    The 45-then-15 order is the discriminating one: a `rest_ms[i] = minutes`
    assignment (dropping the `max()` this fold depends on -- see `model.py`
    section 6's own comment, "MAX, not assignment") would leave the SMALLER,
    later value in place and wrongly admit both fixtures.
    """
    model = _rest_probe_board(
        rule_groups=[([0, 1], 45, None), ([0, 1], 15, None)],
        slack_minutes=20,
    )
    capacity, detail = _rest_probe_capacity(model)
    assert capacity == 1, (
        f"expected the larger 45-minute rest (not the later, smaller 15) to bind, giving "
        f"capacity 1: {detail}"
    )


def test_a_covering_rule_groups_none_rest_contributes_nothing():
    """`min_rest_minutes = None` on a covering group ('this group carries no
    rest rule at all' -- C1's presence tracking, module docstring) must
    contribute nothing, distinct from contributing 0 -- and, more sharply,
    must not CRASH: `max(0, None)` raises `TypeError`, so a fold that omits
    the presence check does not silently misbehave here, it stops the solve
    outright. With no OTHER rest source any more, 30 minutes' slack gives
    capacity 2 (both fit) whether the group is skipped correctly or the board
    simply had no group at all -- the meaningful red/green proof for this one
    is the crash, not a capacity difference (see task report).
    """
    model = _rest_probe_board(rule_groups=[([0, 1], None, None)], slack_minutes=30)
    capacity, detail = _rest_probe_capacity(model)
    assert capacity == 2, (
        f"a covering group with no rest rule must leave a fixture's rest at its 0 floor, "
        f"giving capacity 2: {detail}"
    )


def test_rule_groups_empty_leaves_the_model_byte_identical():
    """Backward compatibility -- proved at the `CpModel` level, not merely by
    argument. The fold (module docstring, "A SEVENTH is CLOSED") is a loop
    over `rule_groups`; with none, the loop body never executes and
    `rest_ms` is left at its bare-0 starting value. Two calls on the SAME
    board, differing only in whether `rule_groups` is passed explicitly as
    `[]` or omitted entirely (the calling convention every other test in
    this file still uses), must therefore be indistinguishable at the
    `CpModel` proto level.

    This does not, on its own, rule out a bug shared by BOTH call styles --
    that half is covered by the pre-existing suite instead: none of this
    file's other tests pass `rule_groups` at all, and this task's own
    verification run confirms their count is unchanged, before this diff and
    after (task report has the raw numbers).

    `CpModel.Proto()` here is a pybind11-wrapped `CpModelProto`
    (`ortools.sat.python.cp_model_helper`), not a `google.protobuf.Message`
    -- it has no `SerializeToString`, and `==` between two structurally
    identical instances is object identity, not structural (both confirmed
    by hand, not assumed). `str()` on it IS the text-format serialisation
    (confirmed: two structurally-identical-but-distinct models produce equal
    strings, and a genuinely different one does not), so it is the
    byte-for-byte comparison this test needs.
    """
    t0 = _GROUP_ANCHOR
    t1 = t0 + 60 * MIN_MS
    num_courts = 2
    grid_slots = [(c, t, 0) for c in (0, 1) for t in (t0, t1)]
    fixtures = [([0], 0), ([1], 0)]
    constraints = {"match_minutes": 30, "gap_minutes": 0}

    omitted = build_model(fixtures, num_courts, grid_slots, 30, constraints, [], [])
    explicit_empty = build_model(
        fixtures, num_courts, grid_slots, 30, constraints, [], [], rule_groups=[]
    )

    omitted_text = str(omitted.Proto())
    explicit_text = str(explicit_empty.Proto())
    assert omitted_text == explicit_text

    # Not vacuous: the two protos are non-trivial and actually contain the
    # participant-rest intervals this task's fold could have touched.
    names = {c.name for c in omitted.Proto().constraints}
    assert "ivr_0" in names and "ivr_1" in names, sorted(names)


# --- degenerate constraint values must fail loudly, not solve quietly -------
#
# proto3 scalars are non-optional: an unset `match_minutes` arrives as 0,
# indistinguishable from a deliberate 0, and used to be accepted and produce
# a confidently WRONG board reported as OPTIMAL. Measured before the guard
# existed: `match_minutes 0 -> OPTIMAL, 37 zero-length matches stacked`.
# These are domain-layer guards. `placement.schema` (Prompt 04) still owes the
# wire-boundary validation; this is defence in depth, not a replacement.
#
# A day-cap counterpart used to live here too (`day_cap_by_division {0: 0,
# 1: 1} -> OPTIMAL, placed 18/37, zero division-0 fixtures`), guarding the
# dict `division_rules` (proto field 10) fed. Both are retired: a day cap now
# reaches this module only via `rule_groups[].max_fixtures_per_day`, already
# guarded at the wire in `placement.schema._validated_rule_groups` -- there
# is no domain-layer copy of that guard to test here (see model.py section 9
# and `placement.schema`'s module docstring).


def test_absent_day_cap_rule_means_no_cap():
    """No `rule_groups` (hence no day cap -- the only source left; see the
    section comment above) is uncapped, on the production board.

    This asserted `status == "OPTIMAL"` while `solve()` was T0-only. It now
    drives the whole T0->T3 chain, and the UNCAPPED board does not finish it —
    measured, with the cap removed and nothing else changed:

        T0 (placed)     OPTIMAL, 37 placed, 157 ms
        T1 (makespan)   still FEASIBLE after 120 000 ms

    which is not a regression but the board getting HARDER: the day cap is
    what pins fixtures across the 26-day lattice, and without it proving a
    minimal makespan is an open packing problem. The chain reports
    `tiers_completed=1` rather than claiming an optimality it did not prove.

    So the status assertion is dropped and replaced by the two that are
    actually about this test's subject: every fixture placed, and T0 saying so
    itself. Neither is vacuous — pass a `rule_groups` day cap covering
    division 0 and both fail (see `test_assignments_satisfy_every_stated_
    constraint`, which does exactly that).

    The wall is 3 s rather than the production 8 s for the same reason: T0
    settles this question in 157 ms and T1 then burns every remaining second
    to no purpose, on eight search workers. Nothing here asks about the
    budget, and a suite that heats the box for six seconds per test makes the
    tests that DO ask about it flakier.
    """
    # Deliberately NOT passing `rule_groups` (unlike every other
    # `_production_board()` caller from here on): the point of this test is
    # the UNCAPPED board, so the fixture's day cap is discarded rather than
    # forwarded to `build_model`.
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps, _rule_groups = (
        _production_board()
    )
    model = build_model(fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps)
    outcome = solve(model, wall_seconds=3.0)
    assert outcome.tiers_completed >= 1, "T0 itself did not complete — the rest would be vacuous"
    assert len(outcome.assignments) == len(fixtures)
    assert dict(outcome.objective_values)["placed"] == len(fixtures)


def test_rejects_zero_match_minutes():
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps, _rule_groups = (
        _production_board()
    )
    constraints = {**constraints, "match_minutes": 0}
    with pytest.raises(ValueError, match="match_minutes"):
        build_model(fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps)


def test_rejects_missing_match_minutes():
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps, _rule_groups = (
        _production_board()
    )
    constraints = {k: v for k, v in constraints.items() if k != "match_minutes"}
    with pytest.raises(ValueError, match="match_minutes"):
        build_model(fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps)


# --- negative-AFTER-ARITHMETIC values: the same family, one step further ----
#
# The guards above catch `<= 0` and missing. They do not catch a NEGATIVE value
# that only becomes degenerate once the model adds it to `match_minutes`, and
# that case is strictly worse than zero: zero fails to constrain, negative
# CANCELS the match length and reopens a constraint family that was closed.
# Measured on the production board, returning OPTIMAL with `error`
# unset — the service's most dangerous shape, a confident wrong answer:
#   gap_minutes = -40  -> OPTIMAL, 37 placed, 4 tiers, 1 same-court MATCH overlap
# `-match_minutes` is used below because it is the exact value that zeroes the
# interval width; any negative value is rejected, but this is the one that
# demonstrably produces the wrong board.
#
# A `rest_by_division = -40` counterpart used to live here too, guarding the
# dict `division_rules` fed. Retired along with that field: `rule_groups[].
# min_rest_minutes` is the only rest source left, already guarded at the wire
# in `placement.schema._validated_rule_groups` -- there is no domain-layer
# copy of that guard to test here either.


def test_rejects_negative_gap_minutes():
    """A negative turnaround zeroes the court interval and two matches land on
    one court simultaneously — the exact failure `match_minutes`' own guard
    text describes, through a field that had no guard at either layer."""
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps, _rule_groups = (
        _production_board()
    )
    constraints = {**constraints, "gap_minutes": -constraints["match_minutes"]}
    with pytest.raises(ValueError, match="gap_minutes"):
        build_model(fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps)


def test_accepts_zero_gap_minutes():
    """Zero turnaround is legitimate (courts with no changeover), so the guard
    must reject negatives WITHOUT closing the contract's own zero case."""
    fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps, _rule_groups = (
        _production_board()
    )
    constraints = {**constraints, "gap_minutes": 0}
    model = build_model(fixtures, num_courts, grid_slots, step_minutes, constraints, existing, deps)
    # One decision var per fixture -- identity is position, so this is just a
    # count now rather than the old `fixture_ids == [...]` id-list check.
    assert len(model.fixture_vars.placed) == len(fixtures)


def test_rejects_an_empty_grid():
    """A grid with no admissible ticks must not silently invent one.

    `build_model` fell back to `Domain.FromValues([0])` and a single day bucket
    `[0]`, so fixtures were placed at `start_at_ms=0` on a grid offering zero
    legal slots — measured: OPTIMAL, 2 placed, 4 tiers. `placement.schema` already
    rejects an empty slot list at the wire, so the SERVICE path was safe; the
    domain object could still be constructed invalid, which leaves `bench/`,
    `test_objective.py` and any future direct caller holding the silent wrong
    board. A domain object must refuse to exist in an invalid state.
    """
    fixtures, num_courts, _grid_slots, step_minutes, constraints, existing, deps, _rule_groups = (
        _production_board()
    )
    with pytest.raises(ValueError, match="grid_slots"):
        build_model(fixtures, num_courts, [], step_minutes, constraints, existing, deps)


# --- per-court grids: each court's OWN tick set is enforced, not just the ---
# --- union (task C2 — closes the gap the module docstring records) ---------
#
# Before this fix, `start[i]`'s domain was `full_domain`, the UNION of every
# court's admissible starts (`admissible_starts` a few lines up in
# `build_model`). Nothing tied a fixture's start to the specific court it was
# placed on, so a fixture presence on court c could legally land on a tick c
# never actually offered. `placement.schema._validate_court_slot_coverage`
# used to catch this at the wire by REFUSING the whole request; C2 replaces
# the refusal with the real fix, so a per-court blackout is placed correctly
# instead of bouncing the caller back to its own greedy fallback.


def test_a_fixture_cannot_be_forced_onto_a_court_at_a_tick_it_does_not_offer():
    """Court 0 offers both T and T+40; court 1 offers ONLY T+40 — exactly the
    module docstring's own measured repro ("with C0 offering {T, T+40} and C1
    only {T+40}, a fixture was placed on C1 at T, OPTIMAL").

    Forced via explicit constraints rather than left to the tier chain's own
    search: with a single fixture and two otherwise-identical courts, nothing
    in the T0-T3 objective prefers one legal (court, tick) pair over another
    (court imbalance is identical whichever lone court is used), so a FREE
    solve landing on the illegal tick would be a matter of search luck, not
    proof that the model permits it. Pinning both the court and the start and
    checking feasibility is the deterministic form of the same question: if
    the model still allows this combination, `solver.Solve` reports it SAT
    (or better) and `extract_assignments`-equivalent reads back exactly the
    illegal placement; once the fix is in, the same request is INFEASIBLE.
    """
    t = 3_600_000  # a real epoch tick, never 0 (the module's own convention)
    t_plus_40 = t + 40 * MIN_MS
    grid_slots = [(0, t, 0), (0, t_plus_40, 0), (1, t_plus_40, 0)]
    constraints = {"match_minutes": 30, "gap_minutes": 0, "rest_by_division": {}, "day_cap_by_division": {}}
    model = build_model([([0], 0)], 2, grid_slots, 40, constraints, [], [])
    fv = model.fixture_vars
    model.Add(fv.presence_court[0][1] == 1)  # force the fixture onto court 1
    model.Add(fv.start[0] == t)  # force it onto the tick court 1 does not offer

    solver = cp_model.CpSolver()
    status = solver.Solve(model)

    detail = f"status={solver.StatusName(status)}"
    if status in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        detail += (
            f" -- fixture 0 placed on court {solver.Value(fv.presence_court[0][1])} "
            f"at start={solver.Value(fv.start[0])}, but court 1 only offers {t_plus_40}"
        )
    assert status == cp_model.INFEASIBLE, detail


def test_a_declared_but_slotless_court_never_receives_a_fixture():
    """The other shape `_validate_court_slot_coverage` used to refuse: a
    declared court (in range for `num_courts`) that no slot offers at all.

    C2 lifts that refusal too (`placement.schema` no longer rejects it — a
    court blacked out for the whole horizon is a legitimate thing for an
    organiser to configure) and moves the rule into the domain: forcing
    `presence_court[i][c] == 0` for every fixture, on every such court,
    directly -- `Domain.FromValues([])` is deliberately NOT used for this,
    per the module docstring.

    Two courts, only one of which (court 0) is ever mentioned by a slot.
    Forcing the fixture onto court 1 must be INFEASIBLE; leaving it free must
    still place it, on court 0.
    """
    t = 3_600_000
    grid_slots = [(0, t, 0)]
    constraints = {"match_minutes": 30, "gap_minutes": 0, "rest_by_division": {}, "day_cap_by_division": {}}

    forced = build_model([([0], 0)], 2, grid_slots, 40, constraints, [], [])
    forced.Add(forced.fixture_vars.presence_court[0][1] == 1)
    solver = cp_model.CpSolver()
    status = solver.Solve(forced)
    assert status == cp_model.INFEASIBLE, (
        f"court 1 has no slots at all, yet the fixture was forced onto it and the model "
        f"allowed it: status={solver.StatusName(status)}"
    )

    free = build_model([([0], 0)], 2, grid_slots, 40, constraints, [], [])
    outcome = solve(free, wall_seconds=5.0)
    assert outcome.assignments == [(0, 0, t)], (
        f"expected the fixture placed on the only court that offers slots (court 0 at {t}), "
        f"got {outcome.assignments}"
    )


def test_per_court_domain_adds_constraints_only_when_courts_disagree():
    """Structural proxy for the docstring's efficiency claim, checked by
    constraint COUNT rather than by timing: timing is measured separately
    (bench, N>=6, `_RULES.md` section 6b) because CP-SAT's search is
    nondeterministic and a wall-clock assertion inside a unit test would be
    exactly the load-flaky test this suite avoids elsewhere.

    Same fixture, same day structure, same size of admissible-start union
    either way — the only thing that differs is whether every court's OWN
    tick set equals that shared union. `AddLinearExpressionInDomain` is
    emitted only for a court whose set is a STRICT SUBSET of the union, so
    the asymmetric board must produce MORE raw constraints than the
    homogeneous one; a homogeneous board pays nothing extra at all.
    """
    t = 3_600_000
    constraints = {"match_minutes": 30, "gap_minutes": 0, "rest_by_division": {}, "day_cap_by_division": {}}

    # Homogeneous: both courts offer the identical two ticks.
    homogeneous_slots = [(c, t + k * 40 * MIN_MS, 0) for c in (0, 1) for k in range(2)]
    homogeneous = build_model([([0], 0)], 2, homogeneous_slots, 40, constraints, [], [])

    # Asymmetric: court 1 offers only the SECOND tick -- a strict subset, and
    # the union is still {t, t+40} exactly as above, so any constraint-count
    # difference cannot be explained by a different admissible-starts size.
    asymmetric_slots = [(0, t, 0), (0, t + 40 * MIN_MS, 0), (1, t + 40 * MIN_MS, 0)]
    asymmetric = build_model([([0], 0)], 2, asymmetric_slots, 40, constraints, [], [])

    homogeneous_count = len(homogeneous.Proto().constraints)
    asymmetric_count = len(asymmetric.Proto().constraints)
    assert asymmetric_count > homogeneous_count, (
        f"a court offering a strict subset of the shared tick set should add per-court domain "
        f"constraints the homogeneous board does not need: homogeneous={homogeneous_count} "
        f"asymmetric={asymmetric_count}"
    )


def test_a_pin_past_the_last_admissible_tick_does_not_brick_the_whole_solve():
    """#511 REGRESSION. `mk_hi >= pin + dur_ms` is a HARD constraint, so the
    horizon `mk_hi` is declared over has to cover pins and not only admissible
    ticks. Derived from `admissible_starts` alone, a pin past the last tick
    made `pin + dur_ms > max_end` unsatisfiable and the ENTIRE model came back
    INFEASIBLE -- the organiser gets no board at all, from a pin the wire
    accepts as valid.

    Not a contrived input: a pin is deliberately allowed to sit OFF the grid
    lattice (module docstring -- it counts against no day by design), and
    `schema.py`'s `_validated_existing` ties a pin to no grid bound. Dragging
    one match past the end of the last play window is enough.

    The movable fixture here is placeable on its own tick and shares nothing
    with the pin -- no entrant, no court -- so the ONLY thing that can make
    this board infeasible is the horizon bound. That is what keeps this test
    pointed at the bug rather than at some incidental conflict.
    """
    t = 3_600_000
    constraints = {"match_minutes": 30, "gap_minutes": 0, "rest_by_division": {}, "day_cap_by_division": {}}
    slots = [(0, t, 0), (0, t + 40 * MIN_MS, 0)]

    # A whole day PAST the last admissible tick, on a court the movable
    # fixture is not using, with an entrant the movable fixture does not share.
    late_pin = [(1, t + DAY_MS)]

    model = build_model([([0], 0)], 2, slots, 40, constraints, late_pin, [])
    outcome = solve(model, wall_seconds=8.0)

    assert outcome.status != "infeasible", (
        f"a pin past the last admissible tick must not make the board infeasible; "
        f"status={outcome.status!r} assignments={outcome.assignments!r}"
    )
    assert len(outcome.assignments) == 1, (
        f"the one movable fixture is placeable and shares nothing with the pin, so it must "
        f"still be placed: {outcome.assignments!r}"
    )
