// MATRIX.md, rendered ONLY from results JSON (R10). Deterministic: no clock,
// no durations. A cell shows the worst state among its cases; a cell with no
// case is ░. An empty run is a banner, never an empty table (R13).
//
// The rows and columns are the run's own `grid` — the catalogue as it was when
// the run was made — never the live catalogue (T11 review M4): a catalogue
// edit in a later wave cannot change how committed evidence renders, so the
// committed-matrix drift test reds only when the evidence or the renderer
// changes. This module must not import the catalogue.
//
// A case whose row or sport is not on that grid is REFUSED rather than left
// out: it would still count in the totals while its cell read ░ "not run" —
// a suppressed result, not a clean one.
import { CASE_STATES, GLYPH, type CaseState, type RunResults } from "./results.ts";

export const SEVERITY: readonly CaseState[] = ["red", "later", "needs_ruling", "no_path", "not_run", "refused", "works"];

export function worstState(states: readonly CaseState[]): CaseState | null {
  for (const s of SEVERITY) if (states.includes(s)) return s;
  return null;
}

/** One markdown table cell: GFM splits on `|` even inside a code span, and a
 *  newline ends the row, so both are neutralised (error reasons carry both). */
const cell = (text: string): string => text.replace(/\s*[\r\n]+\s*/g, " ").replace(/\|/g, "\\|");

const HEAD = (r: RunResults) => [
  "# Format × sport matrix",
  "",
  `> Generated by \`pnpm matrix:render\` from \`results.json\` (run \`${r.runId}\`, harness \`${r.harnessCommit}\`, schema v${r.schemaVersion}). Do not edit by hand (R10).`,
  "",
];

export function renderMatrix(results: RunResults): string {
  if (results.cases.length === 0) {
    return [...HEAD(results), `> **No cases run.** \`results.json\` for run \`${results.runId}\` holds zero cases. An empty run is a failure (R13), not a clean matrix.`, ""].join("\n");
  }
  const { rows, sports } = results.grid;
  const cellOf = (row: string, sport: string) => `${row}|${sport}`;
  const byCell = new Map<string, CaseState[]>();
  for (const c of results.cases) {
    if (!rows.includes(c.row) || !sports.includes(c.sport)) {
      throw new Error(`renderMatrix: case ${c.caseId} (row '${c.row}', sport '${c.sport}') is not on this run's own grid (results.grid)`);
    }
    const k = cellOf(c.row, c.sport);
    byCell.set(k, [...(byCell.get(k) ?? []), c.state]);
  }
  const legend = CASE_STATES.map((s) => `${GLYPH[s]} ${s}`).join(" · ");
  const table = [
    `| row | ${sports.join(" | ")} |`,
    `|---|${sports.map(() => "---").join("|")}|`,
    ...rows.map((row) => `| ${row} | ${sports.map((s) => GLYPH[worstState(byCell.get(cellOf(row, s)) ?? []) ?? "not_run"]).join(" | ")} |`),
  ];
  const totals = CASE_STATES.map((s) => `| ${GLYPH[s]} ${s} | ${results.cases.filter((c) => c.state === s).length} |`);
  const cases = [...results.cases]
    .sort((a, b) => a.caseId.localeCompare(b.caseId))
    .map((c) => {
      const applied = c.checks.filter((k) => k.verdict !== "abstain");
      const items = applied.reduce((n, k) => n + k.checked, 0);
      return `| \`${cell(c.caseId)}\` | ${GLYPH[c.state]} | ${cell(c.reason)} | ${applied.length}/${c.checks.length} | ${items} |`;
    });
  return [
    ...HEAD(results),
    legend,
    "",
    ...table,
    "",
    "## Totals",
    "",
    "| state | cases |",
    "|---|---|",
    ...totals,
    `| total | ${results.cases.length} |`,
    "",
    "## Cases",
    "",
    "| case | state | reason | checks applied | items checked |",
    "|---|---|---|---|---|",
    ...cases,
    "",
  ].join("\n");
}
