// Types for stryker.groups.mjs (the engine tsconfig includes test/**, and a .ts test importing an untyped .mjs is TS7016).
// Exactly the exports the .mjs has; test/stryker-groups.test.ts holds the two equal, and holds the group-name union below to
// the .mjs's keys, in order.
export declare const STRYKER_GROUPS: Record<
  | "competition-1"
  | "competition-2"
  | "competition-3"
  | "competition-4"
  | "competition-5"
  | "competition-6"
  | "competition-7"
  | "core-1"
  | "core-2"
  | "core-3"
  | "modules-1"
  | "modules-2"
  | "modules-3"
  | "modules-4"
  | "modules-5"
  | "modules-6"
  | "modules-7"
  | "draws-1"
  | "draws-2"
  | "draws-3"
  | "draws-4"
  | "sports-cricket-1"
  | "sports-cricket-2"
  | "sports-cricket-3"
  | "sports-cricket-4"
  | "sports-cricket-5"
  | "sports-cricket-6"
  | "sports-cricket-7"
  | "sports-cricket-8"
  | "sports-cricket-9"
  | "sports-cricket-10"
  | "sports-cricket-11"
  | "sports-cricket-12"
  | "sports-cricket-13"
  | "sports-cricket-14"
  | "sports-football-1"
  | "sports-football-2"
  | "sports-football-3"
  | "sports-football-4"
  | "sports-football-5"
  | "sports-football-6"
  | "sports-football-7"
  | "sports-period-1"
  | "sports-period-2"
  | "sports-period-3"
  | "sports-period-4"
  | "sports-period-5"
  | "sports-period-6"
  | "sports-period-7"
  | "sports-period-8"
  | "sports-period-9"
  | "sports-setbased-1"
  | "sports-setbased-2"
  | "sports-setbased-3"
  | "sports-setbased-4"
  | "sports-setbased-5"
  | "sports-setbased-6"
  | "sports-nested-1"
  | "sports-nested-2"
  | "sports-nested-3"
  | "sports-nested-4"
  | "sports-nested-5"
  | "sports-other-1"
  | "sports-other-2"
  | "sports-other-3"
  | "sports-other-4"
  | "sports-other-5"
  | "sports-other-6"
  | "sports-other-7"
  | "probe",
  string[]
>;
export declare const STRYKER_SPLITS: Record<string, string[]>;
export declare const STRYKER_FAMILIES: Record<
  "competition" | "core" | "modules" | "draws" | "sports-cricket" | "sports-football" | "sports-period" | "sports-setbased" | "sports-nested" | "sports-other",
  string[]
>;
export declare const STRYKER_EXCLUDED: Record<string, string>;
export declare const STRYKER_PLACEMENT_OUT_OF_SCOPE: Record<string, string>;
export declare const STRYKER_VITEST_WORKERS: number;
export declare function strykerConcurrency(o: { cores: number; memBytes: number; workersPerSandbox: number }): number;
