// The ten organiser commands of design §7.5, as fast-check async commands over
// (ModelState, OrganiserDriver). Each carries k (which candidate) and w (which
// side / winner) as plain fields, generated by fc.nat() — so a shrunk path
// replays exactly, and a hand-written sequence (commandOf) runs the same code
// as a generated one (modelCommands). After every command: checkStep. Every
// product refusal must be named (observed.ts isNamedRefusal), or it is a
// violation, never a skip.
import fc from "fast-check";
import { RefusedCall, type OrganiserDriver, type PostedEvent } from "../driver/types.ts";
import { isNamedRefusal, isTerminal } from "../observed.ts";
import { generateStream } from "../streams/index.ts";
import { START, type StreamEvent } from "../streams/types.ts";
import { fenceBlocking } from "./fences.ts";
import { liveEntries, type LedgerEntry } from "./ledger-fold.ts";
import { COMMAND_KINDS, ModelViolation, absorbFixtures, checkStep, type CommandKind, type FixtureModel, type ModelState } from "./state.ts";

export { COMMAND_KINDS, ModelViolation, checkStep, newModelState, type CommandKind, type FixtureModel, type ModelState } from "./state.ts";

/** The roster ceiling: the model grows a field, it does not stress one. */
const MAX_ENTRANTS = 8;

/** Candidate `k` of `xs`. `ready()` guarantees candidates; an empty list here
 *  is a model defect, refused by name rather than read as `undefined`. */
function pick<T>(xs: readonly T[], k: number, what: string): T {
  if (xs.length === 0) throw new Error(`model: no candidate ${what} — ready() let an empty command through`);
  return xs[k % xs.length];
}
function seatsOf(f: FixtureModel): [string, string] {
  if (f.home === null || f.away === null) throw new Error(`model: fixture ${f.id} is not seated`);
  return [f.home, f.away];
}
function knownLedger(f: FixtureModel): LedgerEntry[] {
  if (f.ledger === null) throw new Error(`model: fixture ${f.id}'s ledger is unknown`);
  return f.ledger;
}
const seated = (f: FixtureModel) => f.home !== null && f.away !== null;
/** Scorable from a clean slate: seated, nothing posted by the model, not finished. */
const open = (m: ModelState) => [...m.fixtures.values()].filter((f) => seated(f) && f.ledger !== null && f.ledger.length === 0 && !isTerminal(f.status));
const withLive = (m: ModelState) => [...m.fixtures.values()].filter((f) => f.ledger !== null && liveEntries(f.ledger).length > 0);
const decided = (m: ModelState) => [...m.fixtures.values()].filter((f) => seated(f) && f.ledger !== null && f.status === "decided");

abstract class Cmd implements fc.AsyncCommand<ModelState, OrganiserDriver> {
  abstract readonly kind: CommandKind;
  readonly k: number;
  readonly w: number;
  readonly fences: boolean;
  constructor(k: number, w: number, fences: boolean) {
    this.k = k;
    this.w = w;
    this.fences = fences;
  }
  protected abstract ready(m: ModelState): boolean;
  protected abstract act(m: ModelState, d: OrganiserDriver): Promise<void>;
  check(m: Readonly<ModelState>): boolean {
    if (!this.ready(m)) return false;
    const fence = fenceBlocking(m, this.kind, this.fences);
    if (fence !== null) {
      m.fenced.set(fence.id, (m.fenced.get(fence.id) ?? 0) + 1);
      return false;
    }
    return true;
  }
  async run(m: ModelState, d: OrganiserDriver): Promise<void> {
    m.counts[this.kind].ran++;
    m.history.push(this.toString());
    try {
      await this.act(m, d);
      m.counts[this.kind].accepted++;
    } catch (e) {
      if (!(e instanceof RefusedCall)) throw e;
      if (!isNamedRefusal(e.status, e.code)) throw new ModelViolation("model-refusal-named", [`${this.toString()}: ${e.method} ${e.path} → ${e.status} ${e.code ?? "(no code)"}`]);
      m.counts[this.kind].refused++;
      this.onRefused(m, e);
    }
    await checkStep(m, d);
  }
  protected onRefused(_m: ModelState, _e: RefusedCall): void {}
  toString(): string { return `${this.kind}(${this.k},${this.w})`; }
}

/** Posts events and records them in the fixture's ledger. A core.void's
 *  target is the payload's event_id, as the product lifts it (scoring.ts). A
 *  refusal part-way leaves the ledger unknown: the posted prefix is not
 *  reported back. */
async function post(m: ModelState, d: OrganiserDriver, f: FixtureModel, events: readonly StreamEvent[]): Promise<PostedEvent[]> {
  const prefix = `${m.tag}:${f.id}:p${++m.posts}`;
  let out: PostedEvent[];
  try {
    out = await d.postStream(f.id, events, prefix);
  } catch (e) {
    f.ledger = null;
    throw e;
  }
  if (out.length !== events.length) {
    f.ledger = null;
    throw new Error(`model: the driver answered ${out.length} events for ${events.length} posted to ${f.id}`);
  }
  events.forEach((ev, i) => {
    const target = ev.type === "core.void" ? (ev.payload as { event_id?: unknown } | null)?.event_id : undefined;
    f.ledger?.push({ id: out[i].event_id, seq: out[i].seq, type: ev.type, payload: ev.payload, ...(typeof target === "string" ? { voids: target } : {}) });
  });
  const last = out.at(-1);
  if (last !== undefined) f.status = last.status;
  return out;
}

function winStream(m: ModelState, f: FixtureModel, winner: "home" | "away"): StreamEvent[] {
  const [home, away] = seatsOf(f);
  return generateStream({ sportKey: m.sport, cfg: m.cfg, stageKind: m.stageKind as never, home, away, outcome: { kind: "win", winner } });
}

class Start extends Cmd {
  readonly kind = "Start" as const;
  protected ready(m: ModelState) { return !m.started; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    await d.start(m.divisionId);
    m.started = true;
    absorbFixtures(m, await d.listFixtures(m.divisionId));
  }
}
class AddEntrant extends Cmd {
  readonly kind = "AddEntrant" as const;
  protected ready(m: ModelState) { return m.entrants.length < MAX_ENTRANTS && !m.completed; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const n = m.entrants.length + 1;
    const [e] = await d.addEntrants(m.divisionId, [{ displayName: `Matrix Player ${n}`, seed: n, kind: m.kind }]);
    if (e === undefined) throw new Error("model: addEntrants answered no entrant");
    m.entrants.push(e.id);
    if (m.started) m.lateEntry = true;
  }
}
class Withdraw extends Cmd {
  readonly kind = "Withdraw" as const;
  protected ready(m: ModelState) { return m.started && m.withdrawn.size === 0 && m.entrants.length > 2; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const id = pick(m.entrants, this.k, "entrant");
    // The cascade posts events the model does not write (walkover forfeits,
    // voids, abandons) — even when it is refused part-way: unknown from here.
    for (const f of m.fixtures.values()) if (f.home === id || f.away === id) f.ledger = null;
    await d.withdraw(id);
    m.withdrawn.add(id);
  }
}
class Score extends Cmd {
  readonly kind = "Score" as const;
  protected ready(m: ModelState) { return m.started && open(m).length > 0; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const f = pick(open(m), this.k, "open fixture");
    await post(m, d, f, winStream(m, f, this.w % 2 === 0 ? "home" : "away"));
  }
}
class Walkover extends Cmd {
  readonly kind = "Walkover" as const;
  protected ready(m: ModelState) { return m.started && open(m).length > 0; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const f = pick(open(m), this.k, "open fixture");
    const [home, away] = seatsOf(f);
    // HttpDriver.forfeit's composition on a scheduled fixture: START, then the forfeit.
    await post(m, d, f, [START, { type: "core.forfeit", payload: { by: this.w % 2 === 0 ? home : away, reason: "walkover" } }]);
  }
}
class Void extends Cmd {
  readonly kind = "Void" as const;
  protected ready(m: ModelState) { return m.started && withLive(m).length > 0; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const f = pick(withLive(m), this.k, "fixture with a live event");
    const target = pick(liveEntries(knownLedger(f)).reverse(), 0, "live event");
    await post(m, d, f, [{ type: "core.void", payload: { event_id: target.id } }]);
  }
}
class Correct extends Cmd {
  readonly kind = "Correct" as const;
  protected ready(m: ModelState) { return m.started && decided(m).length > 0; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const f = pick(decided(m), this.k, "decided fixture");
    // Void every live event newest first, then record the result again.
    const voids = liveEntries(knownLedger(f)).reverse().map((t): StreamEvent => ({ type: "core.void", payload: { event_id: t.id } }));
    await post(m, d, f, voids);
    await post(m, d, f, winStream(m, f, this.w % 2 === 0 ? "away" : "home"));
  }
}
class Generate extends Cmd {
  readonly kind = "Generate" as const;
  protected ready(m: ModelState) { return m.started && !m.completed; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const g = await d.generate(m.stageId);
    // I8 judges what is recorded here: `total` is the stage's full list, so a
    // 2xx answering zero fixtures is an empty generate (R13, carry b).
    m.generates.push({ status: 200, code: null, total: g.fixtures.length, created: g.created });
    absorbFixtures(m, await d.listFixtures(m.divisionId));
  }
  protected override onRefused(m: ModelState, e: RefusedCall) { m.generates.push({ status: e.status, code: e.code, total: 0, created: 0 }); }
}
class Rebuild extends Cmd {
  readonly kind = "Rebuild" as const;
  protected ready(m: ModelState) { return m.started && !m.completed; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    await d.rebuild(m.stageId);
    absorbFixtures(m, await d.listFixtures(m.divisionId));
  }
}
class Complete extends Cmd {
  readonly kind = "Complete" as const;
  protected ready(m: ModelState) { return m.started && !m.completed; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    // completed:false (fixtures still pending) leaves the stage open and the
    // command offered again. A named (4xx) refusal committed nothing and stays
    // retryable (HttpDriver, design §6.4); a 5xx is never named, so it ends the
    // run as a violation before HttpDriver's never-repeat guard could matter.
    const out = await d.completeStage(m.stageId);
    m.completed = out.completed;
  }
}

const CTORS: Readonly<Record<CommandKind, new (k: number, w: number, fences: boolean) => Cmd>> = {
  Start, AddEntrant, Withdraw, Score, Walkover, Void, Correct, Generate, Rebuild, Complete,
};

export function commandOf(kind: CommandKind, k: number, w: number, fences: boolean): fc.AsyncCommand<ModelState, OrganiserDriver> {
  return new CTORS[kind](k, w, fences);
}

export function modelCommands(opts: { fences: boolean }): fc.Arbitrary<fc.AsyncCommand<ModelState, OrganiserDriver>>[] {
  return COMMAND_KINDS.map((kind) => fc.tuple(fc.nat({ max: 63 }), fc.nat({ max: 1 })).map(([k, w]) => commandOf(kind, k, w, opts.fences)));
}
