// The ten organiser commands of design §7.5, as fast-check async commands over
// (ModelState, OrganiserDriver). Each carries k (which candidate) and w (which
// side / winner) as plain fields, generated by fc.nat() — so a shrunk path
// replays exactly, and a hand-written sequence (commandOf) runs the same code
// as a generated one (modelCommands). After every command: checkStep. Every
// product refusal must be named (observed.ts isNamedRefusal), or it is a
// violation, never a skip — except the one known code-less refusal the model
// EXPECTS (the roster lock after Start, finding CD-T13b), which is recorded
// and walked past. A named refusal of a command the model holds legal is a
// violation too (ruling I-1): an ordinary refusal is one the product may give.
// One named refusal is PERMITTED where the model cannot see its whole reason:
// a knockout take-back over a fed match (ruling RR-1, fed-seats.ts
// NEXT_MATCH_STARTED). When it comes it is judged on what the driver says
// then: it wrote nothing, and a fed match really has started by the
// product's own rule — expected; none has — unexpected; the model cannot
// see — an unknown.
import fc from "fast-check";
import { RefusedCall, type OrganiserDriver, type PostedEvent } from "../driver/types.ts";
import { isNamedRefusal, isTerminal } from "../observed.ts";
import { generateStream } from "../streams/index.ts";
import { START, type StreamEvent } from "../streams/types.ts";
import { postedTeamSides } from "../scenarios/lineup-plan.ts";
import { fenceBlocking } from "./fences.ts";
import { liveEntries, type LedgerEntry } from "./ledger-fold.ts";
import {
  COMMAND_KINDS, ModelViolation, NEXT_MATCH_CHECK, NEXT_MATCH_LOCK, REFUSAL_NAMED, ROSTER_LOCK, ROSTER_LOCK_CHECK, ROSTER_LOCK_FINDING, UNEXPECTED_REFUSAL,
  absorbFixtures, checkStep, ensureModelLineups, entrantInput, fedCandidates, fedMatchStarted, markUnknown, readRoster, recordFinding, rosterLocked,
  type CommandKind, type FixtureModel, type ModelState, type StepVerdict,
} from "./state.ts";

export { COMMAND_KINDS, ModelViolation, checkStep, newModelState, type CommandKind, type FixtureModel, type ModelState } from "./state.ts";

/** The roster ceiling: the model grows a field, it does not stress one. */
const MAX_ENTRANTS = 8;

/** Candidate `k` of `xs`. `ready()` guarantees candidates; an empty list here
 *  is a model defect, refused by name rather than read as `undefined`. */
function pick<T>(xs: readonly T[], k: number, what: string): T {
  if (xs.length === 0) throw new Error(`model: no candidate ${what} — ready() let an empty command through`);
  return xs[k % xs.length];
}
function seatsOf(f: FixtureModel): [string, string] {
  if (f.home === null || f.away === null) throw new Error(`model: fixture ${f.id} is not seated`);
  return [f.home, f.away];
}
function knownLedger(f: FixtureModel): LedgerEntry[] {
  if (f.ledger === null) throw new Error(`model: fixture ${f.id}'s ledger is unknown`);
  return f.ledger;
}
const seated = (f: FixtureModel) => f.home !== null && f.away !== null;
/** Scorable from a clean slate: seated, nothing posted by the model, not finished. */
const open = (m: ModelState) => [...m.fixtures.values()].filter((f) => seated(f) && f.ledger !== null && f.ledger.length === 0 && !isTerminal(f.status));
const withLive = (m: ModelState) => [...m.fixtures.values()].filter((f) => f.ledger !== null && liveEntries(f.ledger).length > 0);
const decided = (m: ModelState) => [...m.fixtures.values()].filter((f) => seated(f) && f.ledger !== null && f.status === "decided");

/** A named refusal the product MAY give, for a reason the model cannot see
 *  whole: matched on status AND code, `judge` then decides it on what the
 *  driver says now — expected, unexpected (with why), or unverified. */
type Judged = { kind: "expected" } | { kind: "unverified" } | { kind: "unexpected"; detail: string };
interface PermittedRefusal { status: number; code: string; judge: (d: OrganiserDriver, refusal: RefusedCall) => Promise<Judged> }

/** Ruling RR-1 (fix rounds 2 and 3): a take-back of `f` on a bracket may be
 *  refused under NEXT_MATCH_LOCK (fed-seats.ts). Judged in two parts:
 *  - it wrote nothing. The product refuses before the first write, and a
 *    take-back's FIRST void (newest first) already moves who `f` advances —
 *    voiding a win stream's last event un-decides it, pinned per sport in
 *    model-core.test.ts — so the tip must not move, and the ledger post()
 *    dropped on the refusal is the model's again;
 *  - it was right. Each candidate is re-read through the driver: one that has
 *    started (fedMatchStarted, the product's own rule with its cascade-
 *    walkover reset) makes it expected; none that has, and none unverified,
 *    makes it an unexpected refusal; otherwise the candidates the model
 *    cannot see are counted as unknowns and the refusal proves nothing.
 *  The candidates are the refusal's (W1c Task 2, ruling Q2): the fed match it
 *  names, when the model holds it — else the structural superset, which also
 *  decides whether the refusal is permitted at all. */
function takeBackLock(m: ModelState, f: FixtureModel): PermittedRefusal | null {
  if (fedCandidates(m, f).length === 0) return null;
  const known = [...knownLedger(f)];
  return {
    status: NEXT_MATCH_LOCK.status,
    code: NEXT_MATCH_LOCK.code,
    judge: async (d, refusal) => {
      const tip = await d.fixtureState(f.id);
      if (tip.last_seq !== known.length) {
        throw new ModelViolation(NEXT_MATCH_CHECK, [`fixture ${f.id}: refused ${NEXT_MATCH_LOCK.code}, yet the product's tip moved from ${known.length} to ${tip.last_seq} — a refused take-back writes nothing (fed-seats.ts runs before the first write)`]);
      }
      f.ledger = known;
      const candidates = fedCandidates(m, f, refusal);
      const read: { g: FixtureModel; line: string; verdict: ReturnType<typeof fedMatchStarted> }[] = [];
      for (const g of candidates) {
        const st = await d.fixtureState(g.id);
        const verdict = fedMatchStarted(st, g.ledger);
        if (verdict === "started") return { kind: "expected" };
        read.push({ g, verdict, line: `${g.id} (${st.status}, outcome ${JSON.stringify(st.outcome ?? null)}, ${st.last_seq} events): ${verdict}` });
      }
      const unseen = read.filter((r) => r.verdict === "unverified");
      for (const r of unseen) markUnknown(m, r.g, "next-match-unverified", `${f.id}'s take-back refused ${NEXT_MATCH_LOCK.code} over ${r.line}`);
      if (unseen.length > 0) return { kind: "unverified" };
      return { kind: "unexpected", detail: `no fed match has started — ${read.map((r) => r.line).join("; ")}` };
    },
  };
}

abstract class Cmd implements fc.AsyncCommand<ModelState, OrganiserDriver> {
  abstract readonly kind: CommandKind;
  readonly k: number;
  readonly w: number;
  readonly fences: boolean;
  constructor(k: number, w: number, fences: boolean) {
    this.k = k;
    this.w = w;
    this.fences = fences;
  }
  protected abstract ready(m: ModelState): boolean;
  protected abstract act(m: ModelState, d: OrganiserDriver): Promise<void>;
  /** The model holds this command legal here: a named refusal is a product
   *  defect, not an ordinary refusal (ruling I-1). */
  protected mustAccept(_m: ModelState): boolean { return false; }
  /** The model knows the product refuses this command here. */
  protected expectsRefusal(_m: ModelState): boolean { return false; }
  /** The check an acceptance violates when a refusal was expected. */
  protected expectedCheck(): string { return "model-expected-refusal"; }
  /** A known code-less refusal: the finding it is recorded under, or null. */
  protected knownUnnamed(_e: RefusedCall): string | null { return null; }
  protected async afterExpectedRefusal(_m: ModelState, _d: OrganiserDriver): Promise<void> {}
  /** A named refusal the product may give here, or null (ruling RR-1). */
  protected permittedRefusal(_m: ModelState): PermittedRefusal | null { return null; }
  /** The entrant this command would act on, when it picks one — what a fence
   *  reads (fences.ts); null for a command that picks none. */
  protected subject(_m: ModelState): string | null { return null; }
  check(m: Readonly<ModelState>): boolean {
    if (!this.ready(m)) return false;
    const fence = fenceBlocking(m, this.kind, this.fences, this.subject(m));
    if (fence !== null) {
      m.fenced.set(fence.id, (m.fenced.get(fence.id) ?? 0) + 1);
      return false;
    }
    return true;
  }
  async run(m: ModelState, d: OrganiserDriver): Promise<void> {
    const c = m.counts[this.kind];
    c.ran++;
    m.history.push(this.toString());
    // Judged on the state the command was drawn in, before it acts.
    const must = this.mustAccept(m);
    const expected = this.expectsRefusal(m);
    const permitted = this.permittedRefusal(m);
    const unknownsBefore = m.unknowns.length;
    let verdict: StepVerdict = "accepted";
    try {
      await this.act(m, d);
      if (expected) throw new ModelViolation(this.expectedCheck(), [`${this.toString()}: the product accepted a command the model expected it to refuse`]);
      c.accepted++;
    } catch (e) {
      if (!(e instanceof RefusedCall)) throw e;
      const line = `${this.toString()}: ${e.method} ${e.path} → ${e.status} ${e.code ?? "(no code)"}`;
      // The product's own words (redacted, RefusedCall): a committed case's
      // `match` names its failure by them, and by nothing else (T15 fix
      // rounds 2 and 3). ModelViolation appends them to the evidence.
      const said = e.message;
      const named = isNamedRefusal(e.status, e.code);
      if (expected) {
        if (!named) {
          const finding = this.knownUnnamed(e);
          if (finding === null) throw new ModelViolation(REFUSAL_NAMED, [line], said);
          recordFinding(m, finding, line);
        }
        c.expected++;
        verdict = "expected-refusal";
        await this.afterExpectedRefusal(m, d);
      } else if (permitted !== null && e.status === permitted.status && e.code === permitted.code) {
        const j = await permitted.judge(d, e);
        if (j.kind === "unexpected") {
          c.unexpected++;
          throw new ModelViolation(UNEXPECTED_REFUSAL, [`${line} — ${j.detail}`], said);
        }
        if (j.kind === "expected") {
          c.expected++;
          verdict = "expected-refusal";
        } else {
          // Refused, and the model can hold it neither legal nor wrong. The
          // unknowns judge() recorded say why, and make this step "unknown"
          // below — one rule for every step that leaves the model unsure.
          c.refused++;
        }
      } else {
        if (!named) throw new ModelViolation(REFUSAL_NAMED, [line], said);
        if (must) {
          c.unexpected++;
          throw new ModelViolation(UNEXPECTED_REFUSAL, [`${line} — the model holds ${this.kind} legal here`], said);
        }
        c.refused++;
        verdict = "refused";
        this.onRefused(m, e);
      }
    }
    await checkStep(m, d);
    if (verdict === "accepted" && m.unknowns.length > unknownsBefore) verdict = "unknown";
    m.steps.push({ cmd: this.toString(), verdict });
  }
  protected onRefused(_m: ModelState, _e: RefusedCall): void {}
  toString(): string { return `${this.kind}(${this.k},${this.w})`; }
}

/** Posts events and records them in the fixture's ledger. On a team division
 *  each side's lineup is PUT first (ensureModelLineups, T45-R1/R2), and the
 *  sides posted to are recorded for the lineup check (decideFixture's
 *  teamPosts). A core.void's
 *  target is the payload's event_id, as the product lifts it (scoring.ts). A
 *  refusal part-way leaves the ledger unknown: the posted prefix is not
 *  reported back. So does an answer the driver marks `retried` (HttpDriver's
 *  one SEQ_CONFLICT retry): the product's count moved under the post. */
async function post(m: ModelState, d: OrganiserDriver, f: FixtureModel, events: readonly StreamEvent[]): Promise<PostedEvent[]> {
  await ensureModelLineups(m, d, f);
  const prefix = `${m.tag}:${f.id}:p${++m.posts}`;
  let out: PostedEvent[];
  try {
    out = await d.postStream(f.id, events, prefix);
  } catch (e) {
    f.ledger = null;
    throw e;
  }
  // The model has no rosterless setup (that is PADPROOF's, D3): a team division is always owed its lineups.
  if (m.kind === "team") m.teamPosts.set(f.id, postedTeamSides(f.home, f.away, (e) => m.entrants.includes(e)));
  if (out.length !== events.length) {
    f.ledger = null;
    throw new Error(`model: the driver answered ${out.length} events for ${events.length} posted to ${f.id}`);
  }
  events.forEach((ev, i) => {
    const target = ev.type === "core.void" ? (ev.payload as { event_id?: unknown } | null)?.event_id : undefined;
    f.ledger?.push({ id: out[i].event_id, seq: out[i].seq, type: ev.type, payload: ev.payload, ...(typeof target === "string" ? { voids: target } : {}) });
  });
  const last = out.at(-1);
  if (last !== undefined) f.status = last.status;
  const retried = out.filter((p) => p.retried === true).map((p) => p.seq);
  if (retried.length > 0 && f.ledger !== null) markUnknown(m, f, "retried", `seq ${retried.join(", ")} retried`);
  return out;
}

function winStream(m: ModelState, f: FixtureModel, winner: "home" | "away"): StreamEvent[] {
  const [home, away] = seatsOf(f);
  return generateStream({ sportKey: m.sport, cfg: m.cfg, stageKind: m.stageKind as never, home, away, outcome: { kind: "win", winner } });
}

class Start extends Cmd {
  readonly kind = "Start" as const;
  protected ready(m: ModelState) { return !m.started; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    await d.start(m.divisionId);
    m.started = true;
    absorbFixtures(m, await d.listFixtures(m.divisionId));
  }
}
class AddEntrant extends Cmd {
  readonly kind = "AddEntrant" as const;
  protected ready(m: ModelState) { return m.entrants.length < MAX_ENTRANTS && !m.completed; }
  // After Start the product locks the roster (entrants.ts): offered, EXPECTED
  // to be refused, the roster judged unchanged.
  protected override expectsRefusal(m: ModelState) { return rosterLocked(m); }
  protected override expectedCheck() { return ROSTER_LOCK_CHECK; }
  protected override knownUnnamed(e: RefusedCall) { return e.status === ROSTER_LOCK.status ? ROSTER_LOCK_FINDING : null; }
  protected override async afterExpectedRefusal(m: ModelState, d: OrganiserDriver) {
    const now = (await d.listEntrants(m.divisionId)).map((e) => e.id);
    const had = new Set(m.entrants);
    if (now.length !== had.size || now.some((id) => !had.has(id))) {
      throw new ModelViolation(ROSTER_LOCK_CHECK, [`${this.toString()}: refused, yet the roster went from ${had.size} to ${now.length} entrants`]);
    }
  }
  protected async act(m: ModelState, d: OrganiserDriver) {
    // A late team entrant carries its full roster too, read back like the first ones (ruling 49).
    const [e] = await d.addEntrants(m.divisionId, [entrantInput(m, m.entrants.length + 1)]);
    if (e === undefined) throw new Error("model: addEntrants answered no entrant");
    if (m.kind === "team") m.rosters.set(e.id, await readRoster(d, m, e));
    m.entrants.push(e.id);
    // #879's trigger: the roster grew while the stage already had fixtures.
    if (m.fixtures.size > 0) m.lateEntry = true;
  }
}
class Withdraw extends Cmd {
  readonly kind = "Withdraw" as const;
  protected ready(m: ModelState) { return m.started && m.withdrawn.size === 0 && m.entrants.length > 2; }
  /** The first withdrawal of an active entrant is always the organiser's to make. */
  protected override mustAccept(m: ModelState) { return m.withdrawn.size === 0; }
  /** The one pick both the fence and the act read, so they cannot disagree. */
  protected override subject(m: ModelState): string { return pick(m.entrants, this.k, "entrant"); }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const id = this.subject(m);
    // The cascade posts events the model does not write (walkover forfeits,
    // voids, abandons) — even when it is refused part-way: unknown from here.
    for (const f of m.fixtures.values()) if (f.home === id || f.away === id) f.ledger = null;
    await d.withdraw(id);
    m.withdrawn.add(id);
  }
}
class Score extends Cmd {
  readonly kind = "Score" as const;
  protected ready(m: ModelState) { return m.started && open(m).length > 0; }
  protected override mustAccept() { return true; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const f = pick(open(m), this.k, "open fixture");
    await post(m, d, f, winStream(m, f, this.w % 2 === 0 ? "home" : "away"));
  }
}
class Walkover extends Cmd {
  readonly kind = "Walkover" as const;
  protected ready(m: ModelState) { return m.started && open(m).length > 0; }
  protected override mustAccept() { return true; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const f = pick(open(m), this.k, "open fixture");
    const [home, away] = seatsOf(f);
    // HttpDriver.forfeit's composition on a scheduled fixture: START, then the forfeit.
    await post(m, d, f, [START, { type: "core.forfeit", payload: { by: this.w % 2 === 0 ? home : away, reason: "walkover" } }]);
  }
}
class Void extends Cmd {
  readonly kind = "Void" as const;
  protected ready(m: ModelState) { return m.started && withLive(m).length > 0; }
  // Must-accept, except a take-back the product may refuse by name (RR-1).
  protected override mustAccept() { return true; }
  protected override permittedRefusal(m: ModelState) { return takeBackLock(m, this.target(m)); }
  private target(m: ModelState) { return pick(withLive(m), this.k, "fixture with a live event"); }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const f = this.target(m);
    const target = pick(liveEntries(knownLedger(f)).reverse(), 0, "live event");
    await post(m, d, f, [{ type: "core.void", payload: { event_id: target.id } }]);
  }
}
class Correct extends Cmd {
  readonly kind = "Correct" as const;
  protected ready(m: ModelState) { return m.started && decided(m).length > 0; }
  // Must-accept, except a take-back the product may refuse by name (RR-1).
  protected override mustAccept() { return true; }
  protected override permittedRefusal(m: ModelState) { return takeBackLock(m, this.target(m)); }
  private target(m: ModelState) { return pick(decided(m), this.k, "decided fixture"); }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const f = this.target(m);
    // Void every live event newest first, then record the result again.
    const voids = liveEntries(knownLedger(f)).reverse().map((t): StreamEvent => ({ type: "core.void", payload: { event_id: t.id } }));
    await post(m, d, f, voids);
    await post(m, d, f, winStream(m, f, this.w % 2 === 0 ? "away" : "home"));
  }
}
class Generate extends Cmd {
  readonly kind = "Generate" as const;
  // Before Start too: POST /stages/:id/generate refuses only a frozen schedule
  // (stages.ts generateStageFixturesWrite), and it is how fixtures come to
  // exist before Start — the first half of #879's sequence.
  protected ready(m: ModelState) { return !m.completed; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    const g = await d.generate(m.stageId);
    // I8 judges what is recorded here: `total` is the stage's full list, so a
    // 2xx answering zero fixtures is an empty generate (R13, carry b).
    m.generates.push({ status: 200, code: null, total: g.fixtures.length, created: g.created });
    // The reconcile ran over the grown roster: the late entry is spent.
    m.lateEntry = false;
    absorbFixtures(m, await d.listFixtures(m.divisionId));
  }
  protected override onRefused(m: ModelState, e: RefusedCall) { m.generates.push({ status: e.status, code: e.code, total: 0, created: 0 }); }
}
class Rebuild extends Cmd {
  readonly kind = "Rebuild" as const;
  // Whenever the stage has fixtures, before Start too: rebuildStageFixtures
  // has no division-status gate, and it is the organiser's fix for #879.
  protected ready(m: ModelState) { return !m.completed && m.fixtures.size > 0; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    await d.rebuild(m.stageId);
    // Every fixture re-seated from the current roster: the late entry is resolved.
    m.lateEntry = false;
    absorbFixtures(m, await d.listFixtures(m.divisionId));
  }
}
class Complete extends Cmd {
  readonly kind = "Complete" as const;
  protected ready(m: ModelState) { return m.started && !m.completed; }
  protected async act(m: ModelState, d: OrganiserDriver) {
    // completed:false (fixtures still pending) leaves the stage open and the
    // command offered again. A named (4xx) refusal committed nothing and stays
    // retryable (HttpDriver, design §6.4); a 5xx is never named, so it ends the
    // run as a violation before HttpDriver's never-repeat guard could matter.
    const out = await d.completeStage(m.stageId);
    m.completed = out.completed;
  }
}

const CTORS: Readonly<Record<CommandKind, new (k: number, w: number, fences: boolean) => Cmd>> = {
  Start, AddEntrant, Withdraw, Score, Walkover, Void, Correct, Generate, Rebuild, Complete,
};

export function commandOf(kind: CommandKind, k: number, w: number, fences: boolean): fc.AsyncCommand<ModelState, OrganiserDriver> {
  return new CTORS[kind](k, w, fences);
}

/** Ruling 49: a swiss cell's weights. A swiss seats one round per Generate,
 *  and only a decided board can be corrected, so a uniform draw rarely got a
 *  Correct in at the default runs (W1b's swiss|badminton read vacuous live).
 *  Start, Generate and Score drawn three times as often get it there. */
export const SWISS_BIAS: Readonly<Partial<Record<CommandKind, number>>> = Object.freeze({ Start: 3, Generate: 3, Score: 3 });

/** One arbitrary per command kind — `bias[kind]` of them when a bias weights
 *  it (never fewer than one, so no kind is dropped). No bias is the uniform
 *  set every cell drew before Task 14, so a non-swiss cell, and every case
 *  found on one, generates exactly what it did. */
export function modelCommands(opts: { fences: boolean; bias?: Readonly<Partial<Record<CommandKind, number>>> }): fc.Arbitrary<fc.AsyncCommand<ModelState, OrganiserDriver>>[] {
  return COMMAND_KINDS.flatMap((kind) => Array.from({ length: Math.max(1, opts.bias?.[kind] ?? 1) }, () => fc.tuple(fc.nat({ max: 63 }), fc.nat({ max: 1 })).map(([k, w]) => commandOf(kind, k, w, opts.fences))));
}
