// Live pre-flight for the OpenRouter shootout. Run by hand, never in CI.
//
//   OPENROUTER_API_KEY=... node --experimental-strip-types scripts/openrouter-preflight.ts
//
// Does two things:
//   1. fetches /api/v1/models and applies the pure capability filter;
//   2. sends one tiny request per named candidate carrying the real data
//      policy, to find out whether it has any route at all under
//      data_collection:"deny" + zdr:true.
//
// Writes design/v4/05-openrouter-candidates.md. A candidate that cannot route
// under the policy is recorded as such — that is a result, not a blocker.
import fs from "node:fs";
import {
  eligibleCandidates,
  MIN_CONTEXT_TOKENS,
  type OpenRouterModel,
} from "../apps/web/src/server/ai/candidate-filter.ts";

const KEY = process.env.OPENROUTER_API_KEY;
if (!KEY) throw new Error("OPENROUTER_API_KEY is required");

const BASE = process.env.OPENROUTER_BASE_URL ?? "https://openrouter.ai/api/v1";

// Named entrants from the design spec §8. They pass through the same filter
// and the same policy probe as everything the models endpoint returns.
const NAMED = ["x-ai/grok-4.5", "z-ai/glm-5.2", "moonshotai/kimi-k2.6"];

// Raw upstream error bodies can carry account identifiers (we've seen
// "user_id" show up in OpenRouter 403 payloads), and this table gets
// committed to the repo. Strip it before it ever reaches the report.
function redactUserId(body: string): string {
  return body.replace(/"user_id"\s*:\s*"[^"]*"/g, '"user_id":"<redacted>"');
}

async function probePolicy(model: string): Promise<{ ok: boolean; detail: string }> {
  const res = await fetch(`${BASE}/chat/completions`, {
    method: "POST",
    headers: { authorization: `Bearer ${KEY}`, "content-type": "application/json" },
    body: JSON.stringify({
      model,
      max_tokens: 16,
      messages: [{ role: "user", content: "Reply with the single word: ok" }],
      provider: { data_collection: "deny", allow_fallbacks: false },
      zdr: true,
    }),
  });
  const body = await res.text();
  if (!res.ok) return { ok: false, detail: `HTTP ${res.status}: ${redactUserId(body.slice(0, 300))}` };
  return { ok: true, detail: "routed under data_collection=deny + zdr" };
}

const listRes = await fetch(`${BASE}/models`, {
  headers: { authorization: `Bearer ${KEY}` },
});
if (!listRes.ok) throw new Error(`models list failed: HTTP ${listRes.status}`);
const models = ((await listRes.json()) as { data: OpenRouterModel[] }).data;

const derived = eligibleCandidates(models);
const derivedIds = new Set(derived.map((c) => c.id));

const rows: string[] = [];
for (const id of [...NAMED, ...derived.map((c) => c.id)].filter(
  (id, i, all) => all.indexOf(id) === i,
)) {
  const capable = derivedIds.has(id);
  const policy = capable
    ? await probePolicy(id)
    : { ok: false, detail: "failed the capability filter; not probed" };
  rows.push(
    `| \`${id}\` | ${NAMED.includes(id) ? "named" : "derived"} | ${capable ? "yes" : "no"} | ${
      policy.ok ? "yes" : "no"
    } | ${policy.detail.replace(/\|/g, "\\|")} |`,
  );
}

const doc = `# OpenRouter shootout candidates

Generated by \`scripts/openrouter-preflight.ts\` on ${new Date().toISOString().slice(0, 10)}.
Do not hand-edit — re-run the script.

Capability filter: \`reasoning\` + \`structured_outputs\` + context >= ${MIN_CONTEXT_TOKENS.toLocaleString()} tokens.
Policy probe: one live request carrying \`data_collection: "deny"\` and \`zdr: true\`.

| model | source | capable | policy-routable | detail |
|---|---|---|---|---|
${rows.join("\n")}

Stage-1 entrants are the rows where both **capable** and **policy-routable** are yes.
`;

fs.writeFileSync("design/v4/05-openrouter-candidates.md", doc);
console.log(doc);
