-- Competition desk W2 walkthrough gate 1, finding 1 (2026-09-05): the bracket
-- generator wrote a bye's outcome with JSON.stringify() into this jsonb
-- column instead of the tx.json() every other writer in the codebase uses.
-- JSON.stringify produces a JS string, and the driver then stores that as a
-- JSON STRING SCALAR (jsonb_typeof = 'string'), not an object — so every
-- reader doing outcome?.kind / outcome?.winner silently saw undefined for
-- every generated bye, including the PUBLIC bracket's winner badge
-- (components/public-site/bracket.tsx). No reader in this codebase ever
-- treats a legitimate `outcome` as a JSON string, so jsonb_typeof = 'string'
-- unambiguously identifies rows hit by this bug.
--
-- `outcome #>> '{}'` extracts the jsonb string scalar's content as plain
-- text, unescaped — recovering the original JSON text the generator meant to
-- store. Casting that text to jsonb parses it into the real object.
update fixtures
set outcome = (outcome #>> '{}')::jsonb
where jsonb_typeof(outcome) = 'string';
