// The division page's draw list names an unfilled knockout seat by its
// FEEDER ("Winner of R1·1"), and the four columns that make that possible
// have to come off `listDivisionFixtures`'s OWN select — the seam the
// component tests cannot see.
//
// `run-sheet-feeder-labels.test.tsx` proves the rendering, from hand-built
// props. That is exactly the shape that ships an inert seam: drop the four
// columns from the SQL and every one of those assertions still passes, while
// the live page goes back to "TBD vs TBD". So this file drives the REAL
// producer — a real setup-path progression bracket, generated by the real
// generator, read back through the real usecase — and folds its output
// through the real builder (`feedLabels`) and the real resolver
// (`resolveSlotLabel`). Nothing here is hand-written on both ends.
//
// It also pins WHY the feed is needed at all, as a value rather than a
// comment: the final's stored `*_slot_label` is NULL. That is deliberate in
// `generateProgressionSetupFixtures` — it labels a synthetic seed ref and
// `bracket.slot.bye` and nothing else, because `stageOwesDraw`/
// `awaitsSeedDraw` read "no label ⇒ sibling-fed" for `timing: "setup"`
// stages. If a later change starts stamping a label there, this assertion
// fails and whoever made it has to decide about the draw ledger too, rather
// than finding out from it.
import { afterAll, describe, expect, it } from "vitest";
import { sql } from "@/lib/db";
import { createDivision } from "@/server/usecases/divisions";
import { createEntrants } from "@/server/usecases/entrants";
import { createStages, generateStageFixtures } from "@/server/usecases/stages";
import { listDivisionFixtures, listDivisionFixturesForBoard } from "@/server/usecases/fixtures";
import { seedOrg, GENERIC_CONFIG } from "@/server/usecases/__tests__/_seed";
import { feedLabels, type FeedRow } from "@/lib/schedule-board";
import { resolveSlotLabel } from "@/lib/slot-label";
import { messages } from "@/lib/messages";
import type { MessageKey } from "@/lib/messages";

const HAS_DB = !!process.env.DATABASE_URL;

afterAll(async () => {
  if (!HAS_DB) return;
  const globalForDb = globalThis as { _sql?: { end(): Promise<void> } };
  await globalForDb._sql?.end();
});

const msg = ((key: string, vars?: Record<string, string | number>) => {
  const raw = (messages as Record<string, string>)[key];
  if (raw === undefined) return key;
  return raw.replace(/\{(\w+)\}/g, (_m, k: string) => String(vars?.[k] ?? `{${k}}`));
}) as (key: MessageKey, vars?: Record<string, string | number>) => string;

/** A league feeding a 4-qualifier knockout at `timing: "setup"` — the owner's
 *  reported shape, and the smallest one with a SIBLING-fed seat: round 1 is
 *  two semis seeded from the league, round 2 is the final, whose two seats are
 *  fed by fixtures rather than by a seed slot. */
async function seedSetupKnockout() {
  const { auth } = await seedOrg();
  const competition = await sql<{ id: string }[]>`
    insert into competitions (org_id, name, slug, ends_on, visibility, branding)
    values (${auth.orgId}, 'Draw List Cup', ${"draw-list-" + auth.orgId.slice(0, 8)}, '2030-12-31', 'private', '{}')
    returning id`;
  const division = await createDivision(auth, competition[0]!.id, {
    name: "Open",
    sport_key: "generic",
    variant_key: "score",
    config: GENERIC_CONFIG,
  });
  await createEntrants(
    auth,
    division.id,
    Array.from({ length: 4 }, (_, i) => ({
      kind: "individual" as const,
      display_name: `Entrant ${i + 1}`,
      seed: i + 1,
      members: [],
    })),
  );
  const stages = await createStages(auth, division.id, [
    { seq: 1, kind: "league", name: "League", config: { legs: 1 } },
    {
      seq: 2,
      kind: "knockout",
      name: "Cup",
      config: {},
      progression: {
        sources: [{ stage: "previous", take: [{ kind: "rankRange", from: 1, to: 4 }] }],
        placement: "rank_order",
        timing: "setup",
      },
    },
  ]);
  const ko = stages.find((s) => s.kind === "knockout")!;
  await generateStageFixtures(auth, ko.id);
  return { auth, divisionId: division.id, stageId: ko.id };
}

describe.skipIf(!HAS_DB)("listDivisionFixtures — bracket feed edges reach the draw list", () => {
  it("selects the four feed columns, and they resolve to the schedule's own feeder labels", async () => {
    const { auth, divisionId, stageId } = await seedSetupKnockout();

    const all = await listDivisionFixtures(auth, divisionId);
    const ko = all.filter((f) => f.stage_id === stageId).sort((a, b) =>
      a.round_no - b.round_no || a.seq_in_round - b.seq_in_round,
    );
    // Positive pair: a knockout really was generated, two rounds deep.
    expect(ko.map((f) => `${f.round_no}.${f.seq_in_round}`)).toEqual(["1.1", "1.2", "2.1"]);
    const [semi1, semi2, final] = ko as [typeof ko[0], typeof ko[0], typeof ko[0]];

    // WHY the feed is needed: the final's seats carry NO stored label. (The
    // semis DO — `descriptorLabel` stamps the qualifier slots.)
    expect(final.home_slot_label).toBeNull();
    expect(final.away_slot_label).toBeNull();
    expect(final.home_entrant_id).toBeNull();
    expect(final.away_entrant_id).toBeNull();
    expect(semi1.home_slot_label).not.toBeNull();

    // The columns are actually SELECTED, and carry the real edges. This is
    // the assertion that dies if the SQL projection loses them — one column
    // at a time, because two can cover for each other in a projection.
    expect(semi1.winner_to_fixture).toBe(final.id);
    expect(semi1.winner_to_slot).toBe(1);
    expect(semi2.winner_to_fixture).toBe(final.id);
    expect(semi2.winner_to_slot).toBe(2);
    // A single-elim bracket wires no loser edges — present and null, not
    // absent, which is what tells the two apart.
    expect(final.winner_to_fixture).toBeNull();
    expect(semi1).toHaveProperty("loser_to_fixture");
    expect(semi1.loser_to_fixture).toBeNull();
    expect(semi1.loser_to_slot).toBeNull();

    // Folded through the REAL builder the schedule board uses, then the REAL
    // resolver every renderer shares. The expected text is derived from the
    // dictionary, never typed in.
    const labels = feedLabels(
      ko.map(
        (f): FeedRow => ({
          id: f.id,
          round_no: f.round_no,
          seq_in_round: f.seq_in_round,
          winner_to_fixture: f.winner_to_fixture ?? null,
          winner_to_slot: f.winner_to_slot ?? null,
          loser_to_fixture: f.loser_to_fixture ?? null,
          loser_to_slot: f.loser_to_slot ?? null,
        }),
      ),
    );
    const pair = labels[final.id];
    expect(pair, "the final got no feeder labels at all").toBeDefined();
    const homeText = resolveSlotLabel(pair!.home ?? null, msg, "schedule.tbd");
    const awayText = resolveSlotLabel(pair!.away ?? null, msg, "schedule.tbd");
    const tbd = resolveSlotLabel(null, msg, "schedule.tbd");
    expect(homeText).not.toBe(tbd);
    expect(awayText).not.toBe(tbd);
    expect(homeText).not.toBe(awayText);
    // ORGANISER vocabulary — `slot.winner_match`, not the public
    // `knockout.feederWinner` ("Winner of Semi-finals, match 1") form.
    expect(homeText).toBe(
      resolveSlotLabel(
        { key: "slot.winner_match", params: { round: semi1.round_no, seq: semi1.seq_in_round } },
        msg,
        "schedule.tbd",
      ),
    );
    expect(awayText).toBe(
      resolveSlotLabel(
        { key: "slot.winner_match", params: { round: semi2.round_no, seq: semi2.seq_in_round } },
        msg,
        "schedule.tbd",
      ),
    );
  });

  // The other half of `board-fixture-projection.test.ts`'s invariant, for the
  // four columns this change added. The BOARD read is a narrower projection on
  // payload-budget grounds (board-v3.spec.ts's "gap 15": five unread columns
  // cost ~88 escaped bytes/fixture and put a 5-division board ~29KB over), and
  // the board renders an empty seat from `home_slot_label` + its own
  // `feedLabels()` over its OWN `tx<FeedRow[]>` read — it has no use for these
  // on the row. Without this, the next person to "keep the two selects in
  // sync" widens the board and nothing complains until CI's byte budget does.
  it("does NOT add the feed columns to the board projection", async () => {
    const { auth, divisionId } = await seedSetupKnockout();

    const full = await listDivisionFixtures(auth, divisionId);
    const board = await listDivisionFixturesForBoard(auth, divisionId);
    expect(board.length).toBe(full.length);
    expect(board.length).toBeGreaterThan(0); // the positive pair

    for (const row of board as unknown as Record<string, unknown>[]) {
      for (const col of ["winner_to_fixture", "winner_to_slot", "loser_to_fixture", "loser_to_slot"]) {
        expect(row, `${col} reached the board projection`).not.toHaveProperty(col);
      }
    }
    // …and the full read really does carry them, so the negative above is not
    // passing because the seed produced no edges at all.
    expect(full.some((f) => f.winner_to_fixture !== null)).toBe(true);
  });
});
