// The division page's draw list names an unfilled knockout seat by its
// FEEDER ("Winner of R1·1"), and the four columns that make that possible
// have to come off `listDivisionFixtures`'s OWN select — the seam the
// component tests cannot see.
//
// `run-sheet-feeder-labels.test.tsx` proves the rendering, from hand-built
// props. That is exactly the shape that ships an inert seam: drop the four
// columns from the SQL and every one of those assertions still passes, while
// the live page goes back to "TBD vs TBD". So this file drives the REAL
// producer — a real setup-path progression bracket, generated by the real
// generator, read back through the real usecase — and folds its output
// through the real builder (`feedLabels`) and the real resolver
// (`resolveSlotLabel`). Nothing here is hand-written on both ends.
//
// It also pins WHY the feed is needed at all, as a value rather than a
// comment: the final's stored `*_slot_label` is NULL. That is deliberate in
// `generateProgressionSetupFixtures` — it labels a synthetic seed ref and
// `bracket.slot.bye` and nothing else, because `stageOwesDraw`/
// `awaitsSeedDraw` read "no label ⇒ sibling-fed" for `timing: "setup"`
// stages. If a later change starts stamping a label there, this assertion
// fails and whoever made it has to decide about the draw ledger too, rather
// than finding out from it.
import { afterAll, describe, expect, it } from "vitest";
import { sql } from "@/lib/db";
import { createDivision } from "@/server/usecases/divisions";
import { createEntrants } from "@/server/usecases/entrants";
import { createStages, generateStageFixtures } from "@/server/usecases/stages";
import { listDivisionFixtures, listDivisionFixturesForBoard } from "@/server/usecases/fixtures";
import { seedOrg, GENERIC_CONFIG } from "@/server/usecases/__tests__/_seed";
import { feedLabels, type FeedRow } from "@/lib/schedule-board";
import { resolveSlotLabel } from "@/lib/slot-label";
import { messages } from "@/lib/messages";
import type { MessageKey } from "@/lib/messages";

const HAS_DB = !!process.env.DATABASE_URL;

afterAll(async () => {
  if (!HAS_DB) return;
  const globalForDb = globalThis as { _sql?: { end(): Promise<void> } };
  await globalForDb._sql?.end();
});

const msg = ((key: string, vars?: Record<string, string | number>) => {
  const raw = (messages as Record<string, string>)[key];
  if (raw === undefined) return key;
  return raw.replace(/\{(\w+)\}/g, (_m, k: string) => String(vars?.[k] ?? `{${k}}`));
}) as (key: MessageKey, vars?: Record<string, string | number>) => string;

/** A league feeding a 4-qualifier knockout at `timing: "setup"` — the owner's
 *  reported shape, and the smallest one with a SIBLING-fed seat: round 1 is
 *  two semis seeded from the league, round 2 is the final, whose two seats are
 *  fed by fixtures rather than by a seed slot. */
async function seedSetupKnockout() {
  const { auth } = await seedOrg();
  const competition = await sql<{ id: string }[]>`
    insert into competitions (org_id, name, slug, ends_on, visibility, branding)
    values (${auth.orgId}, 'Draw List Cup', ${"draw-list-" + auth.orgId.slice(0, 8)}, '2030-12-31', 'private', '{}')
    returning id`;
  const division = await createDivision(auth, competition[0]!.id, {
    name: "Open",
    sport_key: "generic",
    variant_key: "score",
    config: GENERIC_CONFIG,
  });
  await createEntrants(
    auth,
    division.id,
    Array.from({ length: 4 }, (_, i) => ({
      kind: "individual" as const,
      display_name: `Entrant ${i + 1}`,
      seed: i + 1,
      members: [],
    })),
  );
  const stages = await createStages(auth, division.id, [
    { seq: 1, kind: "league", name: "League", config: { legs: 1 } },
    {
      seq: 2,
      kind: "knockout",
      name: "Cup",
      config: {},
      progression: {
        sources: [{ stage: "previous", take: [{ kind: "rankRange", from: 1, to: 4 }] }],
        placement: "rank_order",
        timing: "setup",
      },
    },
  ]);
  const ko = stages.find((s) => s.kind === "knockout")!;
  await generateStageFixtures(auth, ko.id);
  return { auth, divisionId: division.id, stageId: ko.id };
}

describe.skipIf(!HAS_DB)("listDivisionFixtures — bracket feed edges reach the draw list", () => {
  it("selects the four feed columns, and they resolve to the schedule's own feeder labels", async () => {
    const { auth, divisionId, stageId } = await seedSetupKnockout();

    const all = await listDivisionFixtures(auth, divisionId);
    const ko = all.filter((f) => f.stage_id === stageId).sort((a, b) =>
      a.round_no - b.round_no || a.seq_in_round - b.seq_in_round,
    );
    // Positive pair: a knockout really was generated, two rounds deep.
    expect(ko.map((f) => `${f.round_no}.${f.seq_in_round}`)).toEqual(["1.1", "1.2", "2.1"]);
    const [semi1, semi2, final] = ko as [typeof ko[0], typeof ko[0], typeof ko[0]];

    // WHY the feed is needed: the final's seats carry NO stored label. (The
    // semis DO — `descriptorLabel` stamps the qualifier slots.)
    expect(final.home_slot_label).toBeNull();
    expect(final.away_slot_label).toBeNull();
    expect(final.home_entrant_id).toBeNull();
    expect(final.away_entrant_id).toBeNull();
    expect(semi1.home_slot_label).not.toBeNull();

    // The columns are actually SELECTED, and carry the real edges. This is
    // the assertion that dies if the SQL projection loses them — one column
    // at a time, because two can cover for each other in a projection.
    expect(semi1.winner_to_fixture).toBe(final.id);
    expect(semi1.winner_to_slot).toBe(1);
    expect(semi2.winner_to_fixture).toBe(final.id);
    expect(semi2.winner_to_slot).toBe(2);
    // A single-elim bracket wires no loser edges — present and null, not
    // absent, which is what tells the two apart.
    expect(final.winner_to_fixture).toBeNull();
    expect(semi1).toHaveProperty("loser_to_fixture");
    expect(semi1.loser_to_fixture).toBeNull();
    expect(semi1.loser_to_slot).toBeNull();

    // Folded through the REAL builder the schedule board uses, then the REAL
    // resolver every renderer shares. The expected text is derived from the
    // dictionary, never typed in.
    const labels = feedLabels(
      ko.map(
        (f): FeedRow => ({
          id: f.id,
          round_no: f.round_no,
          seq_in_round: f.seq_in_round,
          winner_to_fixture: f.winner_to_fixture ?? null,
          winner_to_slot: f.winner_to_slot ?? null,
          loser_to_fixture: f.loser_to_fixture ?? null,
          loser_to_slot: f.loser_to_slot ?? null,
        }),
      ),
    );
    const pair = labels[final.id];
    expect(pair, "the final got no feeder labels at all").toBeDefined();
    const homeText = resolveSlotLabel(pair!.home ?? null, msg, "schedule.tbd");
    const awayText = resolveSlotLabel(pair!.away ?? null, msg, "schedule.tbd");
    const tbd = resolveSlotLabel(null, msg, "schedule.tbd");
    expect(homeText).not.toBe(tbd);
    expect(awayText).not.toBe(tbd);
    expect(homeText).not.toBe(awayText);
    // ORGANISER vocabulary — `slot.winner_match`, not the public
    // `knockout.feederWinner` ("Winner of Semi-finals, match 1") form.
    expect(homeText).toBe(
      resolveSlotLabel(
        { key: "slot.winner_match", params: { round: semi1.round_no, seq: semi1.seq_in_round } },
        msg,
        "schedule.tbd",
      ),
    );
    expect(awayText).toBe(
      resolveSlotLabel(
        { key: "slot.winner_match", params: { round: semi2.round_no, seq: semi2.seq_in_round } },
        msg,
        "schedule.tbd",
      ),
    );
  });

  // The other half of `board-fixture-projection.test.ts`'s invariant, for the
  // four columns this change added. The BOARD read is a narrower projection on
  // payload-budget grounds (board-v3.spec.ts's "gap 15": five unread columns
  // cost ~88 escaped bytes/fixture and put a 5-division board ~29KB over), and
  // the board renders an empty seat from `home_slot_label` + its own
  // `feedLabels()` over its OWN `tx<FeedRow[]>` read — it has no use for these
  // on the row. Without this, the next person to "keep the two selects in
  // sync" widens the board and nothing complains until CI's byte budget does.
  it("does NOT add the feed columns to the board projection", async () => {
    const { auth, divisionId } = await seedSetupKnockout();

    const full = await listDivisionFixtures(auth, divisionId);
    const board = await listDivisionFixturesForBoard(auth, divisionId);
    expect(board.length).toBe(full.length);
    expect(board.length).toBeGreaterThan(0); // the positive pair

    for (const row of board as unknown as Record<string, unknown>[]) {
      for (const col of ["winner_to_fixture", "winner_to_slot", "loser_to_fixture", "loser_to_slot"]) {
        expect(row, `${col} reached the board projection`).not.toHaveProperty(col);
      }
    }
    // …and the full read really does carry them, so the negative above is not
    // passing because the seed produced no edges at all.
    expect(full.some((f) => f.winner_to_fixture !== null)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// CROSS-STAGE feeds — why the tree's feed map is built from the WHOLE
// DIVISION and not from the stage slice it draws.
//
// `feedLabels()` needs BOTH ends of an edge in one row list
// (`schedule-board.ts`'s `!byId.has(target)` guard). `wireCrossFeeds`
// (usecases/stages.ts, reached from the tail of `generateStageFixtures`)
// writes edges whose source and destination sit in DIFFERENT stages, driven
// by a stage's `cross_feeds` config. A per-stage map therefore cannot see
// them.
//
// SAID HONESTLY, because the first version of this comment claimed more than
// the tests below prove: a per-stage map loses the LABEL, and no case here
// shows a PERSON reading "TBD" because of it. `seatLabel`'s precedence is
// `stored ?? feed`, and the two tests below enumerate why that matters —
// a setup progression's cross-fed seat already carries `slot.rank_range`,
// and every seat of a plain knockout is filled or carries a stored
// `slot.winner_match`. The render differential in the first test only appears
// once the stored label is cleared BY HAND, and that is marked where it
// happens. So the whole-division scope is scope insurance for a generator
// that does not exist yet, not the repair of a symptom anyone has seen.
//
// This drives the REAL producer: real stages, real generator, real
// `wireCrossFeeds`, read back through the real `listDivisionFixtures` and
// folded through the real `feedLabels`. Nothing is hand-built on both ends —
// which is the point, because the cross-stage case in
// `bracket-panel-feeder-labels.test.tsx` hand-builds the row and so can only
// prove the component, never that the edge exists in production at all.
// ---------------------------------------------------------------------------
describe.skipIf(!HAS_DB)("listDivisionFixtures — a CROSS-STAGE feed edge", () => {
  it("is wired by wireCrossFeeds, and only a DIVISION-scoped map can name it", async () => {
    const { auth, divisionId, stageId: koId } = await seedSetupKnockout();

    const stages = await sql<{ id: string; seq: number; kind: string }[]>`
      select id, seq, kind from stages where division_id = ${divisionId} order by seq`;
    const league = stages.find((s) => s.kind === "league")!;
    const koStage = stages.find((s) => s.kind === "knockout")!;

    // Generate the league so both ends EXIST, and read the real `ext_key`s
    // back out of the rows rather than guessing at either generator's id
    // scheme — the point of this test is the edge, not the id format.
    await generateStageFixtures(auth, league.id);
    const leagueRows = await sql<{ id: string; ext_key: string | null; round_no: number; seq_in_round: number }[]>`
      select id, ext_key, round_no, seq_in_round from fixtures
      where stage_id = ${league.id} order by round_no, seq_in_round`;
    const koRows = await sql<{ id: string; ext_key: string | null; round_no: number; seq_in_round: number }[]>`
      select id, ext_key, round_no, seq_in_round from fixtures
      where stage_id = ${koId} order by round_no, seq_in_round`;
    expect(leagueRows.length, "the league generated no fixtures to feed FROM").toBeGreaterThan(0);
    const source = leagueRows[0]!;
    const koTarget = koRows[0]!;
    expect(source.ext_key, "no ext_key to feed from").toBeTruthy();
    expect(koTarget.ext_key, "no ext_key to feed into").toBeTruthy();

    // The config the format gates would have written (`S.Stage.cross_feeds`),
    // merged with `||` exactly as this file's own config writers do so the
    // rest of the stage is untouched.
    await sql`
      update stages set config = config || ${sql.json({
        cross_feeds: [
          {
            from_ext_key: source.ext_key,
            side: "winner",
            to_stage_seq: koStage.seq,
            to_ext_key: koTarget.ext_key,
            slot: 2,
          },
        ],
      } as never)}
      where id = ${league.id}`;

    // `wireCrossFeeds` runs at the TAIL of `generateStageFixtures` and is
    // explicitly re-entrant — its own comment says an entry is "wired once
    // both stages generated", i.e. the pass that finds both ends present is
    // the one that writes the edge. So the second generate is not a test
    // contrivance; it is the production path for a feed configured before
    // its source stage existed. (It must be the LEAGUE: the knockout is
    // `timing: "setup"`, and that short-circuits into
    // `generateProgressionSetupFixtures` long before this tail.)
    await generateStageFixtures(auth, league.id);

    const all = await listDivisionFixtures(auth, divisionId);
    const wired = all.find((f) => f.id === source.id)!;
    // The edge is REAL, and it genuinely crosses a stage boundary — the
    // positive pair for the negative assertion below.
    expect(wired.winner_to_fixture, "wireCrossFeeds wired nothing").toBe(koTarget.id);
    expect(wired.winner_to_slot).toBe(2);
    expect(wired.stage_id).toBe(league.id);
    expect(all.find((f) => f.id === koTarget.id)!.stage_id).toBe(koId);
    expect(wired.stage_id).not.toBe(koId);

    const toFeedRow = (f: (typeof all)[number]): FeedRow => ({
      id: f.id,
      round_no: f.round_no,
      seq_in_round: f.seq_in_round,
      winner_to_fixture: f.winner_to_fixture ?? null,
      winner_to_slot: f.winner_to_slot ?? null,
      loser_to_fixture: f.loser_to_fixture ?? null,
      loser_to_slot: f.loser_to_slot ?? null,
    });

    // THE CLAIM. Division scope names the fed seat; the stage slice the tree
    // used to draw from cannot, because the source row is not in it.
    const divisionMap = feedLabels(all.map(toFeedRow));
    const stageMap = feedLabels(all.filter((f) => f.stage_id === koId).map(toFeedRow));

    expect(divisionMap[koTarget.id]?.away, "the division map lost the cross-stage feed").toEqual({
      key: "slot.winner_match",
      params: { round: source.round_no, seq: source.seq_in_round },
    });
    expect(stageMap[koTarget.id]?.away, "the stage slice somehow saw an out-of-stage source").toBeUndefined();

    // …and the difference is ONLY the cross-stage edge: the knockout's own
    // sibling feed resolves identically under both scopes, so the stage map
    // is not simply empty (which would satisfy the negative assertion above
    // for the wrong reason).
    const finalRow = koRows[koRows.length - 1]!;
    expect(divisionMap[finalRow.id]?.home, "the sibling feed vanished too").toBeDefined();
    expect(divisionMap[finalRow.id]?.home).toEqual(stageMap[finalRow.id]?.home);

    // THE UNLABELLED SEAT, pinned where it is easy to find — and pinned as
    // what it IS rather than what it is easy to mistake it for.
    //
    // This final is genuinely unlabelled: no entrant, no stored label, on
    // either seat, produced by the real generator. It is the seat the whole
    // desk-side fix exists for, and it is also the seat that gets offered as
    // evidence that a per-stage feed map "would read TBD".
    //
    // It is not that evidence. Its feeders are its OWN stage's semis, so the
    // assertion directly above — both scopes name it, identically — is what
    // settles it: a stage-scoped map names this seat perfectly well. To
    // witness the division-vs-stage divergence a seat would have to be BOTH
    // unlabelled AND fed from another stage, and the test after this one
    // enumerates why no generator here produces one.
    const finalFull = all.find((f) => f.id === finalRow.id)!;
    expect(
      {
        home: finalFull.home_entrant_id,
        away: finalFull.away_entrant_id,
        homeLabel: finalFull.home_slot_label,
        awayLabel: finalFull.away_slot_label,
      },
      "the setup bracket's final is no longer the unlabelled sibling-fed seat this rests on",
    ).toEqual({ home: null, away: null, homeLabel: null, awayLabel: null });


    // What a PERSON sees for that seat, resolved through the real resolver
    // from the real row — established by RUNNING this, not by reading the
    // generator.
    const target = all.find((f) => f.id === koTarget.id)!;
    const seat = (feed: (typeof divisionMap)[string] | undefined, stored = target.away_slot_label) =>
      resolveSlotLabel(stored ?? feed?.away ?? null, msg, "bracket.tbd" as MessageKey);

    // FINDING, pinned as a value: a `timing: "setup"` progression stamps a
    // seed label on every round-1 seat, so this cross-fed seat ALREADY has a
    // stored label and `seatLabel`'s precedence (stored wins — the live
    // bye-award collision) means the feed never shows here. The customer sees
    // the same words under either scope. If a future change stops stamping
    // that label, this fails and whoever made it meets the line below.
    expect(target.away_slot_label, "a cross-fed setup seat used to carry its seed label").toEqual({
      key: "slot.rank_range",
      seed: 4,
      params: { rank: 4 },
    });
    expect(seat(divisionMap[koTarget.id])).toBe(seat(stageMap[koTarget.id]));

    // …so the render differential lives one step down, on a seat with NO
    // stored label — which is what every sibling-fed seat in a setup bracket
    // is. Clearing it is the only hand-set value in this test, and it is
    // isolating precedence, not manufacturing the edge: the edge above was
    // written by the real `wireCrossFeeds` and is read back from the DB.
    const unlabelled = seat(divisionMap[koTarget.id], null);
    const unlabelledStageScoped = seat(stageMap[koTarget.id], null);
    expect(unlabelled, "the division-scoped map is what keeps this off TBD").toBe(
      msg("slot.winner_match" as MessageKey, {
        ext: msg("slot.match_ref" as MessageKey, { round: source.round_no, seq: source.seq_in_round }),
      }),
    );
    expect(unlabelledStageScoped, "the stage slice falls through to the tree's TBD").toBe(
      msg("bracket.tbd" as MessageKey),
    );
    expect(unlabelled).not.toBe(unlabelledStageScoped);
  });

  // -------------------------------------------------------------------------
  // WHY THE COMMENTS ABOVE SAY "SCOPE INSURANCE" AND NOT "THIS FIXES TBD".
  //
  // The case above proves the division-scoped map NAMES a cross-fed seat while
  // a stage slice does not. It does NOT prove a person ever sees the
  // difference, because that seat already carried a stored `slot.rank_range`
  // and `seatLabel`'s precedence is `stored ?? feed`. The obvious next move —
  // the reviewer's suggestion — is to find a cross-feed target that is
  // genuinely unlabelled, and the only bracket generated by the PLAIN path is
  // where one would live.
  //
  // So: enumerate that bracket's seats, rather than sample one (AGENTS.md 7).
  // Every seat of a plain knockout is EITHER filled with an entrant OR carries
  // a stored label, in every round — round 1 is seeded from the field, and
  // `generateStageFixtures` stamps `matchSlotLabel` on every sibling-fed seat
  // above it. There is therefore no seat in it whose render a cross-stage feed
  // could change, and the search for a customer-visible divergence ends here
  // rather than being left open as a maybe.
  //
  // This is a finding, not a defect: the whole-division scope is correct and
  // costs nothing, and it is what keeps a FUTURE generator — one that leaves a
  // cross-fed seat unlabelled the way `generateProgressionSetupFixtures`
  // already leaves sibling-fed seats unlabelled — from shipping as TBD. If
  // this test ever reds, that generator has arrived and the scope has become
  // load-bearing for a real person.
  // -------------------------------------------------------------------------
  it("has no unlabelled seat to rescue: every plain-knockout seat is filled or stored-labelled", async () => {
    const { auth } = await seedOrg();
    const competition = await sql<{ id: string }[]>`
      insert into competitions (org_id, name, slug, ends_on, visibility, branding)
      values (${auth.orgId}, 'Plain KO Cup', ${"plain-ko-" + auth.orgId.slice(0, 8)}, '2030-12-31', 'private', '{}')
      returning id`;
    const division = await createDivision(auth, competition[0]!.id, {
      name: "Open",
      sport_key: "generic",
      variant_key: "score",
      config: GENERIC_CONFIG,
    });
    await createEntrants(
      auth,
      division.id,
      Array.from({ length: 4 }, (_, i) => ({
        kind: "individual" as const,
        display_name: `Plain ${i + 1}`,
        seed: i + 1,
        members: [],
      })),
    );
    // No `progression`: this is the PLAIN path, the one that stamps
    // `slot.winner_match` into `*_slot_label` itself.
    const stages = await createStages(auth, division.id, [
      { seq: 1, kind: "knockout", name: "Cup", config: {} },
    ]);
    await generateStageFixtures(auth, stages[0]!.id);

    const rows = await listDivisionFixtures(auth, division.id);
    // The premise: a bracket with more than one round, so the enumeration
    // below covers a seeded round AND a sibling-fed one. Without it this
    // passes vacuously on a single final.
    expect(new Set(rows.map((f) => f.round_no)).size, "a one-round bracket proves nothing here").toBeGreaterThan(1);

    const bare = rows.flatMap((f) => [
      ...(f.home_entrant_id === null && f.home_slot_label === null
        ? [`r${f.round_no}·${f.seq_in_round} home`]
        : []),
      ...(f.away_entrant_id === null && f.away_slot_label === null
        ? [`r${f.round_no}·${f.seq_in_round} away`]
        : []),
    ]);
    expect(
      bare,
      "a plain-knockout seat is unlabelled after all — a cross-stage feed COULD change what a person reads here, and both 'scope insurance' comments should go back to being a claim about the customer",
    ).toEqual([]);
  });
});
