// W1d Task 21 (D19): the committed baseline's prose and generated files say what the committed data says.
//
// truth-runs/w1d-baseline holds the third dispatch's merged L1/L2/L3 and the files written about them. committed-matrix.test.ts
// judges the results themselves (re-render, re-decision, frozen plan). This file holds the rest to the data:
//   - the README's layer table, run ids and tag, HARNESS-GREEN.md's verbatim `judge across` / `judge faults` counts and
//     TIMINGS.md's per-layer and per-shard numbers are RE-COMPUTED here from the committed results.json — never typed;
//   - TRIAGE.md, REKEY.md and AUDIT-LEDGER.md are regenerated by the real CLIs from the committed baseline and the committed
//     catalogue, and compared byte for byte (a catalogue edit that moves a gap is then a visible edit of them too);
//   - the triage-shapes fixture is rebuilt by its generator (catalogue/scripts/gen-shapes.py) from the committed baseline and
//     dispatch-cuts.json (Task 19 review M4): the generators that read the dispatches are no longer "rebuilt by hand".
// Every sweep counts what it checked, and zero is a failure.
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { ceilingFromRuns, ceilingsOf, loadShardsConfig, shardMatrix } from "../ci/shard-matrix.ts";
import { AUDIT_DIR } from "../lib/audit-ledger.ts";
import { CATALOGUE_DIR } from "../lib/triage.ts";
import { LAYERS, type Layer } from "../lib/results.ts";
import { REPO, TRUTH_RUNS, trackedUnder } from "./committed-plans.ts";
import { SPAWN_MS, spawnBudget } from "./spawn-budget.ts";

const BASE = resolve(REPO, TRUTH_RUNS, "w1d-baseline");
/** The pinned tag's commit (progress record, T17): the tip of main after PR-A. Typed from the tag, not from a results file. */
const TAG = "matrix-truth/w1d-baseline";
const TAG_SHA = "47f210e3f2094405e4ed4c8b5c9ea6bd2a6085d9";

interface Case { caseId: string; state: string; durationMs: number; planned?: true; [k: string]: unknown }
interface Run { runId: string; harnessCommit: string; plan: string; scope?: string; shards: number; cases: Case[]; startedAt: string; finishedAt: string }
const runs = {} as Record<Layer, Run>;
const text = (name: string): string => readFileSync(resolve(BASE, name), "utf8");

beforeAll(() => {
  for (const l of LAYERS) runs[l] = JSON.parse(readFileSync(resolve(BASE, l, "results.json"), "utf8")) as Run;
});

const scratch = mkdtempSync(join(tmpdir(), "w1d-t21-ev-"));
afterAll(() => { rmSync(scratch, { recursive: true, force: true }); });

// --- the tools' independent restatement (the doc's numbers are not read back from the code that wrote them) -------------

const countOf = (r: Run, state: string): number => r.cases.filter((c) => c.state === state).length;
const drivenOf = (r: Run): Case[] => r.cases.filter((c) => c.planned !== true);
/** Nearest-rank percentile, restated from its definition: the smallest value with at least pct percent of the list at or below it. */
const rank = (sorted: readonly number[], pct: number): number => sorted[Math.ceil((pct * sorted.length) / 100) - 1]!;
const secs = (ms: number): string => `${(ms / 1000).toFixed(1)} s`;
const triple = (ms: readonly number[]): string => {
  const s = [...ms].sort((a, b) => a - b);
  return `${secs(rank(s, 50))} | ${secs(rank(s, 90))} | ${secs(s[s.length - 1]!)}`;
};
/** The doc's section that starts at the heading `head` (its text, e.g. "### L1\n") and runs to the next heading of the same level or higher. */
function section(doc: string, head: string): string {
  const at = doc.indexOf(head);
  expect(at, `${head} is in the document`).toBeGreaterThanOrEqual(0);
  const level = /^#+/.exec(head)![0].length;
  const rest = doc.slice(at + head.length);
  const next = rest.search(new RegExp(`^#{1,${level}} `, "m"));
  return next < 0 ? rest : rest.slice(0, next);
}

// --- the layers ------------------------------------------------------------------------------------------------------

describe("the committed layers: what they are", () => {
  it("three layers, one run each, all of the third dispatch: the same harness commit, the same workflow run, merged (shards N, no shard header)", () => {
    expect(LAYERS.map((l) => runs[l].runId.replace(/-l[123]$/, "")).filter((v, i, a) => a.indexOf(v) === i)).toHaveLength(1);
    let checked = 0;
    for (const l of LAYERS) {
      const r = runs[l];
      expect(TAG_SHA.startsWith(r.harnessCommit), `${l}: harnessCommit ${r.harnessCommit} is the tag's commit`).toBe(true);
      expect(r.harnessCommit.length).toBeGreaterThanOrEqual(7);
      expect(r.shards, `${l}: a merged run`).toBeGreaterThanOrEqual(2);
      expect(r.cases.length, l).toBeGreaterThan(0);
      checked++;
    }
    expect(checked).toBe(3);
  });

  it("shards.json takes each layer's per-case ceiling from the committed baseline, and the ceiling is the data's: ceil(max durationMs / 10 s) x 15 s", () => {
    const cfg = loadShardsConfig();
    let checked = 0;
    for (const l of LAYERS) {
      expect(cfg.layers[l].ceilingFrom, l).toEqual([`w1d-baseline/${l}`]);
      const maxMs = Math.max(...runs[l].cases.map((c) => c.durationMs));
      expect(maxMs, `${l}: the committed layer measured something`).toBeGreaterThan(0);
      expect(ceilingFromRuns(cfg.layers[l].ceilingFrom), l).toBe(Math.ceil(maxMs / 10_000) * 15);
      checked++;
    }
    expect(checked).toBe(3);
  });
});

// --- README ----------------------------------------------------------------------------------------------------------

describe("README.md says what the committed data says", () => {
  it("each layer's table row is built from the committed results.json: plan, run id, shards, cases, driven, works, red, no_path, not_run", () => {
    const readme = text("README.md");
    let checked = 0;
    for (const l of LAYERS) {
      const r = runs[l];
      const row = `| ${l} | \`${r.plan}\` | \`${r.runId}\` | ${r.shards} | ${r.cases.length} | ${drivenOf(r).length} | ${countOf(r, "works")} | ${countOf(r, "red")} | ${countOf(r, "no_path")} | ${countOf(r, "not_run")} |`;
      expect(readme, `README row for ${l}`).toContain(row);
      checked++;
    }
    expect(checked).toBe(3);
    // The histograms add up: a state this table does not list would be a case the table loses.
    for (const l of LAYERS) expect(["works", "red", "no_path", "not_run"].reduce((n, s) => n + countOf(runs[l], s), 0), `${l}: every case is in one listed state`).toBe(runs[l].cases.length);
  });

  it("names the tag and its commit, the three workflow runs (read from the committed cut), and the retention date", () => {
    const readme = text("README.md");
    const cuts = JSON.parse(text("dispatch-cuts.json")) as { dispatches: { n: number; workflowRun: number; runId: string }[] };
    expect(readme).toContain(`\`${TAG}\``);
    expect(readme).toContain(TAG_SHA);
    expect(cuts.dispatches.map((d) => d.n)).toEqual([1, 2, 3]);
    for (const d of cuts.dispatches) {
      expect(d.runId, `dispatch ${d.n}: its run id carries its workflow run`).toContain(`-${d.workflowRun}-`);
      expect(readme, `dispatch ${d.n}`).toContain(`| dispatch ${d.n} | workflow run ${d.workflowRun}`);
    }
    // The committed layers ARE the third dispatch's.
    expect(runs.L1.runId).toContain(`-${cuts.dispatches[2]!.workflowRun}-`);
    expect(readme).toContain("2027-01-03");
    expect(readme).toMatch(/90 days/);
    // A screenshot citation is 1-based (the case-N directory), and the doc says so.
    expect(readme).toMatch(/1-BASED/);
  });

  it("names every file of its own directory (a file the README does not mention is a file nobody reads), and every layer holds its two", () => {
    const readme = text("README.md");
    const top = readdirSync(BASE, { withFileTypes: true }).filter((e) => e.isFile() && e.name !== "README.md").map((e) => e.name);
    expect(top.length, "the directory's own files beside the README").toBeGreaterThanOrEqual(6);
    expect(top.filter((f) => !readme.includes(`\`${f}\``))).toEqual([]);
    const tracked = trackedUnder(`${TRUTH_RUNS}/w1d-baseline`);
    for (const l of LAYERS) expect(tracked.filter((f) => f.includes(`/${l}/`)).map((f) => f.split("/").at(-1)).sort(), l).toEqual(["MATRIX.md", "results.json"]);
    expect(tracked.length).toBeGreaterThanOrEqual(top.length + 1 + 6);
  });
});

// --- HARNESS-GREEN.md ------------------------------------------------------------------------------------------------

describe("HARNESS-GREEN.md: the verbatim judge outputs agree with the committed layers", () => {
  const doc = (): string => text("HARNESS-GREEN.md");

  it("each `judge across` block compared exactly the layer's cases, over three runs; its `differing` lines are the count it states", () => {
    const d = doc();
    let checked = 0;
    for (const l of LAYERS) {
      const block = section(d, `### ${l}\n`).replace(/^\n```text\n/, "");
      const head = /^(L\d): compared (\d+) cases across 3 runs; (\d+) differing; (\d+) faults$/m.exec(block);
      expect(head, `${l}: the across headline`).not.toBeNull();
      expect(head![1]).toBe(l);
      expect(Number(head![2]), `${l}: compared`).toBe(runs[l].cases.length);
      expect(Number(head![3]), `${l}: its differing lines`).toBe([...block.matchAll(/^ {2}differing /gm)].length);
      expect(Number(head![4]), `${l}: faults`).toBe(0);
      checked++;
    }
    expect(checked).toBe(3);
  });

  it("each dispatch-3 `judge faults` block names the committed run, its plan and its case count, with 0 faults; the table's dispatch-3 row is the committed histogram", () => {
    const d = doc();
    let checked = 0;
    for (const l of LAYERS) {
      const r = runs[l];
      const block = section(d, `### Dispatch 3, ${l}\n`);
      expect(block, l).toContain(`${l} ${r.runId} (${r.plan}): compared ${r.cases.length} cases; 0 faults`);
      checked++;
    }
    expect(checked).toBe(3);
    const hist = (r: Run): string => ["works", "red", "no_path", "not_run"].filter((s) => countOf(r, s) > 0).map((s) => `${s} ${countOf(r, s)}`).join(", ");
    const row = d.split("\n").find((line) => line.startsWith("| 3 | "));
    expect(row, "the dispatch-3 row").toBeDefined();
    for (const l of LAYERS) expect(row, l).toContain(`| ${hist(runs[l])} |`.replace("| ", "").replace(/ \|$/, ""));
  });
});

// --- TIMINGS.md ------------------------------------------------------------------------------------------------------

describe("TIMINGS.md: dispatch 3's numbers are re-computed from the committed results", () => {
  const doc = (): string => text("TIMINGS.md");

  it("per layer: shards, driven cases, and p50, p90, max of the driven cases' durationMs", () => {
    const body = section(doc(), "## Per layer, driven cases only");
    let checked = 0;
    for (const l of LAYERS) {
      const r = runs[l];
      const d = drivenOf(r).map((c) => c.durationMs);
      expect(d.length, `${l}: drove something`).toBeGreaterThan(0);
      expect(body, l).toContain(`| 3 | ${l} | ${r.shards} | ${d.length} | ${triple(d)} |`);
      checked++;
    }
    expect(checked).toBe(3);
  });

  it("per shard: the stripe (item i to shard i mod N + 1) of the merged plan order, its driven cases, and p50, p90, max", () => {
    const body = section(doc(), "## Per shard, dispatch 3");
    let checked = 0;
    for (const l of LAYERS) {
      const r = runs[l];
      for (let k = 1; k <= r.shards; k++) {
        const mine = r.cases.filter((_, i) => i % r.shards === k - 1);
        const d = mine.filter((c) => c.planned !== true).map((c) => c.durationMs);
        expect(d.length, `${l} ${k}/${r.shards}: the stripe drove something`).toBeGreaterThan(0);
        expect(body, `${l} shard ${k}/${r.shards}`).toContain(`| ${l} | ${k}/${r.shards} | ${mine.length} | ${d.length} | ${triple(d)} | `);
        checked++;
      }
    }
    // 8 + 2 + 2 stripes, none lost: the stripes tile each layer's plan exactly.
    expect(checked).toBe(LAYERS.reduce((n, l) => n + runs[l].shards, 0));
    expect(checked).toBe(12);
    for (const l of LAYERS) expect(Array.from({ length: runs[l].shards }, (_, k) => runs[l].cases.filter((_, i) => i % runs[l].shards === k).length).reduce((a, b) => a + b, 0), l).toBe(runs[l].cases.length);
  });

  it("the budget table quotes the ceilings the data gives: L1 and L2 195 s, L3 30 s", () => {
    const body = section(doc(), "## What the shard budgets do with these numbers");
    let checked = 0;
    for (const l of LAYERS) {
      const maxMs = Math.max(...runs[l].cases.map((c) => c.durationMs));
      const ceiling = Math.ceil(maxMs / 10_000) * 15;
      const row = body.split("\n").find((line) => line.startsWith(`| ${l} | `));
      expect(row, `${l}'s row`).toBeDefined();
      expect(row, l).toContain(`| ${ceiling} s |`);
      checked++;
    }
    expect(checked).toBe(3);
  });

  it("the budget table's `job timeouts now` are what shardMatrix derives for the committed plans, and the largest is under the cap the prose says no layer nears", () => {
    const cfg = loadShardsConfig();
    // The plan's driven flags, in plan order, are the committed runs' own (committed-matrix.test.ts holds them to the live planners).
    const plans = Object.fromEntries(LAYERS.map((l) => [l, runs[l].cases.map((c) => c.planned !== true)]));
    const { include } = shardMatrix(cfg, "full", plans, ceilingsOf(cfg));
    const body = section(doc(), "## What the shard budgets do with these numbers");
    let checked = 0;
    let largest = 0;
    for (const l of LAYERS) {
      const t = include.filter((j) => j.layer === l).map((j) => j.timeout);
      expect(t.length, `${l}: one job per shard`).toBe(runs[l].shards);
      const lo = Math.min(...t);
      const hi = Math.max(...t);
      largest = Math.max(largest, hi);
      const row = body.split("\n").find((line) => line.startsWith(`| ${l} | `))!;
      expect(row, l).toContain(lo === hi ? `| ${lo} min |` : `| ${lo} to ${hi} min |`);
      checked++;
    }
    expect(checked).toBe(3);
    expect(body).toContain(`the largest is ${largest} min`);
    expect(largest).toBeLessThan(cfg.maxTimeoutMinutes);
    expect(cfg.maxTimeoutMinutes).toBe(300);
  });
});

// --- the generated files, regenerated by the real CLIs -----------------------------------------------------------------

const scripts = (JSON.parse(readFileSync(resolve(REPO, "package.json"), "utf8")) as { scripts: Record<string, string> }).scripts;
/** A package script as package.json spells it, run for real (node + its preload), cwd the repo. */
function runScript(script: string, tail: readonly string[], env: Record<string, string> = {}): { status: number | null; stdout: string; stderr: string } {
  const words = (scripts[script] ?? "").split(" ");
  expect(words[0], `${script} runs node`).toBe("node");
  const r = spawnSync(process.execPath, [...words.slice(1), ...tail], { cwd: REPO, encoding: "utf8", timeout: 2 * SPAWN_MS, env: { PATH: process.env.PATH ?? "", PYTHONDONTWRITEBYTECODE: "1", ...env } });
  return { status: r.status, stdout: r.stdout, stderr: r.stderr };
}
const layerFiles = (): string[] => LAYERS.map((l) => resolve(BASE, l, "results.json"));
const W1_DRIVING_L3 = resolve(REPO, TRUTH_RUNS, "w1drv-l3", "results.json");

/** `pnpm matrix:triage` over the committed baseline, run once: its output directory. */
let triaged: string | null = null;
function triageOut(): string {
  if (triaged !== null) return triaged;
  const out = join(scratch, "triage");
  const r = runScript("matrix:triage", ["--runs", ...layerFiles(), "--rekey", W1_DRIVING_L3, "--rekey-map", resolve(CATALOGUE_DIR, "p-map.json"), "--out", out]);
  expect(r.status, `${r.stderr}\n${r.stdout}`).toBe(0);
  expect(r.stdout, "every red triaged").toMatch(/209 reds checked: 209 triaged, 0 untriaged, 0 ambiguous, 0 misrouted, 0 unknown/);
  triaged = out;
  return out;
}

describe("the generated files are what the CLIs write from the committed baseline and catalogue", () => {
  it("the triage input is the committed baseline: the red count the CLI reports is the committed layers' own", () => {
    const reds = LAYERS.reduce((n, l) => n + countOf(runs[l], "red"), 0);
    expect(reds).toBe(209);
    expect(LAYERS.reduce((n, l) => n + runs[l].cases.length, 0)).toBe(2899);
  });

  it("matrix:triage over L1, L2 and L3 writes TRIAGE.md and REKEY.md byte for byte", () => {
    const out = triageOut();
    let checked = 0;
    for (const f of ["TRIAGE.md", "REKEY.md"]) {
      const made = readFileSync(join(out, f));
      expect(made.length, `${f} is not empty`).toBeGreaterThan(1000);
      expect(made.equals(readFileSync(resolve(BASE, f))), `${f} differs from what matrix:triage writes (re-run it into the baseline directory)`).toBe(true);
      checked++;
    }
    expect(checked).toBe(2);
  }, spawnBudget(2));

  it("matrix:ledger over that triage writes AUDIT-LEDGER.md byte for byte", () => {
    const out = join(scratch, "ledger", "AUDIT-LEDGER.md");
    const r = runScript("matrix:ledger", ["--audit", AUDIT_DIR, "--triage", join(triageOut(), "triage.json"), "--verdicts", resolve(CATALOGUE_DIR, "audit-verdicts.json"), "--out", out]);
    expect(r.status, `${r.stderr}\n${r.stdout}`).toBe(0);
    const made = readFileSync(out);
    expect(made.length).toBeGreaterThan(10_000);
    expect(made.equals(readFileSync(resolve(BASE, "AUDIT-LEDGER.md"))), "AUDIT-LEDGER.md differs from what matrix:ledger writes").toBe(true);
  }, spawnBudget(3));
});

// --- the dispatch-fed catalogue generators (Task 19 review M4) -----------------------------------------------------------

describe("the generators that read the dispatches run against the committed baseline", () => {
  const SCRIPTS = resolve(CATALOGUE_DIR, "scripts");
  /** The layout the scripts read: <n>/<layer>/results.json. Dispatch 3 is the committed baseline; dispatches 1 and 2 are the cut's five L3 cases. */
  let staged: string | null = null;
  function stage(): string {
    if (staged !== null) return staged;
    const dir = join(scratch, "dispatches");
    const cuts = JSON.parse(text("dispatch-cuts.json")) as { dispatches: { n: number; cases: unknown[] }[] };
    for (const l of LAYERS) { mkdirSync(join(dir, "3", l), { recursive: true }); symlinkSync(resolve(BASE, l, "results.json"), join(dir, "3", l, "results.json")); }
    for (const n of [1, 2]) {
      mkdirSync(join(dir, String(n), "L3"), { recursive: true });
      writeFileSync(join(dir, String(n), "L3", "results.json"), JSON.stringify({ cases: cuts.dispatches.find((d) => d.n === n)!.cases }));
    }
    staged = dir;
    return dir;
  }
  /** `W1D_TRIAGE_OUT`: a directory holding out3/triage.json, the triage CLI's own file for the committed baseline. */
  function triageDir(): string {
    const dir = join(scratch, "triage-for-scripts");
    if (!existsSync(join(dir, "out3", "triage.json"))) {
      mkdirSync(join(dir, "out3"), { recursive: true });
      writeFileSync(join(dir, "out3", "triage.json"), readFileSync(join(triageOut(), "triage.json")));
    }
    return dir;
  }
  const py = (script: string, args: readonly string[], env: Record<string, string>): { status: number | null; stdout: string; stderr: string } => {
    const r = spawnSync("python3", [resolve(SCRIPTS, script), ...args], { cwd: REPO, encoding: "utf8", timeout: SPAWN_MS, env: { PATH: process.env.PATH ?? "", PYTHONDONTWRITEBYTECODE: "1", ...env } });
    return { status: r.status, stdout: r.stdout, stderr: r.stderr };
  };

  it("the cut is dispatch-cuts.json's: five cases per dispatch, three dispatches, the third equal to the committed L3's own", () => {
    const cuts = JSON.parse(text("dispatch-cuts.json")) as { ids: string[]; dispatches: { n: number; cases: Case[] }[] };
    expect(cuts.ids).toHaveLength(5);
    expect(cuts.dispatches.map((d) => d.cases.length)).toEqual([5, 5, 5]);
    expect(cuts.dispatches[2]!.cases.map((c) => c.caseId).sort()).toEqual([...cuts.ids].sort());
  });

  it("gen-shapes.py rebuilds tools/matrix/__tests__/fixtures/triage-shapes.json byte for byte from the committed baseline and the cut", () => {
    const out = join(scratch, "triage-shapes.json");
    const r = py("gen-shapes.py", [out], { W1D_DISPATCH: stage(), W1D_TRIAGE_OUT: triageDir() });
    expect(r.status, r.stderr).toBe(0);
    expect(r.stdout, "what the generator reports").toMatch(/58 shapes; 10 flips/);
    const made = readFileSync(out);
    expect(made.length, "not empty").toBeGreaterThan(10_000);
    expect(made.equals(readFileSync(resolve(REPO, "tools/matrix/__tests__/fixtures/triage-shapes.json"))), "triage-shapes.json differs from what gen-shapes.py writes (a hand edit needs the same edit in the script)").toBe(true);
  }, spawnBudget(3));

  it("classify.py over the committed baseline: every red of the three layers read a second way, none disagreeing (a cross-check, as its header says)", () => {
    const reds = LAYERS.reduce((n, l) => n + countOf(runs[l], "red"), 0);
    const r = py("classify.py", [], { W1D_DISPATCH: stage(), W1D_TRIAGE_OUT: triageDir(), W1D_RUNS: "3" });
    expect(r.status, r.stderr).toBe(0);
    expect(r.stdout).toContain(`reds compared: ${reds} disagreements: 0`);
    expect(reds).toBeGreaterThan(0);
  }, spawnBudget(2));

  it("dump.py over the committed L3: its groups add up to the layer's reds", () => {
    const r = py("dump.py", ["3", "L3"], { W1D_DISPATCH: stage() });
    expect(r.status, r.stderr).toBe(0);
    const counts = r.stdout.split("\n").filter((l) => /^\d+ \| /.test(l)).map((l) => Number(l.split(" | ")[0]));
    expect(counts.length, "groups printed").toBeGreaterThan(0);
    expect(counts.reduce((a, b) => a + b, 0)).toBe(countOf(runs.L3, "red"));
  }, spawnBudget(1));
});
