// ONE predicate for "this fixture row is a system-generated bye".
//
// Client-safe on purpose (pure, type-only engine import): the Swiss seating
// helpers, the stage rail and the server-only standings fold must all agree,
// and the 2026-09-20 review's C1 is exactly what happens when they don't —
// `swiss-shell.ts` called ANY `outcome.kind === "award"` a bye, so a real
// two-sided forfeit or retirement was classified as a sit-out and Unpair
// nulled the board's entrants, status and outcome. The correct test already
// existed 1000 lines away in `server/engine-db/competition.ts`; it lives here
// now so there is nothing left to drift.
//
// Every sport kernel emits `{ kind: "award", winner }` for a real two-sided
// walkover/retirement (generic.ts, setbased/kernel.ts, football.ts,
// nested/kernel.ts, cricket.ts, carrom.ts), so the OUTCOME SHAPE ALONE CAN
// NEVER DECIDE THIS. What separates a bye is the seats: a bye has exactly one
// entrant by construction (swissGen writes `away_entrant_id = null`, a
// knockout seeds the same shape), and the entrant sitting out always wins its
// own bye.

import type { MatchOutcome } from "@seazn/engine/core";

/**
 * True only for a genuine system-generated bye: an `award` outcome naming a
 * winner, EXACTLY one seat filled, and the seated side IS that winner.
 *
 * A two-sided award (forfeit / retirement) is a played match and returns
 * false — destroying it would erase the reason the opponent advanced
 * (`stages.ts` rebuild guard, same rule).
 */
export function isOneSidedAwardBye(f: {
  outcome: unknown;
  home_entrant_id: string | null;
  away_entrant_id: string | null;
}): boolean {
  if (!f.outcome || typeof f.outcome !== "object") return false;
  const o = f.outcome as MatchOutcome;
  if (o.kind !== "award" || !o.winner) return false;
  const home = f.home_entrant_id;
  const away = f.away_entrant_id;
  const oneSided = (home !== null && away === null) || (home === null && away !== null);
  if (!oneSided) return false;
  const seated = home ?? away;
  return seated === o.winner;
}

/**
 * Stage kinds whose generated bye is a REST ROUND, not a result.
 *
 * OWNER RULING (#850): a round-robin stage persists a real bye row per round
 * (`roundRobinGen`, usecases/stages.ts) so the organiser can see who sits out,
 * but that bye awards NO points and is not a played match — it is excluded
 * from the standings fold, the qualification view, player match counts, the
 * desk's played/total and the withdrawal policy's "played" count. A Swiss
 * sit-out and a bracket bye are unchanged: they still count as a win.
 *
 * Any kind NOT listed here keeps the pre-#850 behaviour (its bye scores), so a
 * new stage kind cannot silently start dropping points it used to award.
 */
export const REST_BYE_STAGE_KINDS: ReadonlySet<string> = new Set(["league", "group"]);

/**
 * THE MARKER of a round-robin rest-bye row (#850, owner ruling 2026-09-24,
 * fourth round): its generator key, `[p{pool}-]rr-r{n}-bye`.
 *
 * The row SHAPE cannot decide it. A progression-fed league whose qualifier
 * departed before the draw has that seat walked over to the opponent by
 * `awardSeededByes` (usecases/stages.ts): one seat filled, `forfeited`,
 * `{kind:"award", winner}` — exactly a rest bye's shape, in a league. The owner
 * ruled it is NOT a rest bye: it keeps scoring as a win and keeps its display,
 * as before #850. What tells the two apart is how the row was CREATED, so the
 * two writers of rest-bye rows — the generator (`roundRobinGen`) and the
 * reconciler (`reconcileRestByes`) — stamp this key through `restByeExtKey`,
 * and nothing else ever writes one: the walkover keeps its match key
 * (`rr-r{n}-c{k}`), an ad-hoc match is `adhoc-{n}`, a Swiss bye `sw-r{n}-bye`.
 * `ext_key` already rides every copy path a fixture row takes (the history
 * snapshots, the public view, the v1 API), which a new column would not.
 *
 * ONE string, read by BOTH JavaScript (`hasRestByeKey`) and Postgres
 * (`restByeSql`'s `~`, V417's `division_has_results`) — POSIX-bracket syntax
 * only, no escapes or lookarounds, so the two engines cannot read it
 * differently. V417 must spell it literally; its parity test pins that.
 */
export const REST_BYE_EXT_KEY_PATTERN = "(^|-)rr-r[0-9]+-bye$";
const REST_BYE_EXT_KEY = new RegExp(REST_BYE_EXT_KEY_PATTERN);

/** The rest-bye key of round `roundNo`, `prefix` being a group stage's pool
 *  prefix (`pA-`) or "". The ONE spelling the generator and the reconciler
 *  share, so a bye either writes is the same row to the other (the
 *  `(stage_id, ext_key)` unique index makes it so) — and the marker every
 *  reader keys off. */
export function restByeExtKey(prefix: string, roundNo: number): string {
  return `${prefix}rr-r${roundNo}-bye`;
}

/** True when `extKey` carries the rest-bye marker. A missing key (a row read
 *  without it) is no marker: such a row keeps the pre-#850 answer. */
export function hasRestByeKey(extKey: string | null | undefined): boolean {
  return typeof extKey === "string" && REST_BYE_EXT_KEY.test(extKey);
}

/** A fixture row as the bye predicates read it. `ext_key` is optional in the
 *  TYPE only because the wire rows declare it so; a caller that leaves it off
 *  gets "not a rest bye" for every row — so every reader must select it. */
type ByeRow = Parameters<typeof isOneSidedAwardBye>[0] & { ext_key?: string | null };

/**
 * A generated bye that COUNTS: a played win for its holder — a Swiss sit-out, a
 * bracket bye, and a fed league's walkover (`awardSeededByes`). Every one-sided
 * award bye that is NOT a rest bye. THE question every scoring reader asks;
 * never restate the kind or marker check beside it.
 */
export function isScoringBye(f: ByeRow, stageKind: string): boolean {
  return isOneSidedAwardBye(f) && !isRestBye(f, stageKind);
}

/**
 * A round-robin rest bye (#850): a persisted "X sits out round N" row that is
 * never a match — no points, no win, not played. ALL THREE of: the marker
 * (`hasRestByeKey` — how the row was created), the bye shape
 * (`isOneSidedAwardBye`), and a round-robin stage (`REST_BYE_STAGE_KINDS`).
 * The complement of `isScoringBye` over genuine byes; false for everything
 * that is not a bye.
 */
export function isRestBye(f: ByeRow, stageKind: string): boolean {
  return REST_BYE_STAGE_KINDS.has(stageKind) && hasRestByeKey(f.ext_key) && isOneSidedAwardBye(f);
}

/**
 * A bracket's DRAW bye (owner ruling 2026-09-24, fourth round, via the
 * orchestrator's ICS ruling): the seat the draw pads out and nobody ever
 * occupies. Same `bracket.slot.bye` key as every other bye seat — so every
 * renderer still reads "Bye" and `awardSeededByes` still settles the line off
 * the key — plus `params.bye = "draw"`, the EXPLICIT marker of a sit-out the
 * DRAW made. Written where the generator knows the line is its own bye
 * (`g.award`: the plain insert and the `timing: "setup"` label pass,
 * usecases/stages.ts), and by the cascade (`resolveBracketSeats`) on a seat
 * whose dead feeder the DRAW made — a draw bye's loser edge (a double-elim
 * losers'-bracket bye, a third-place bye), or a void fed only by such feeders
 * (#850 review round 3). A seat a PERSON vacated — a qualifier who departed
 * before the draw, or a feeder a withdrawal voided or walked over — is stamped
 * with the PLAIN label and is a walkover, not a sit-out: without this param
 * the two rows are identical (one seat, `forfeited`, an award to it, the bye
 * key, a positional ext_key).
 */
export const DRAW_BYE_SLOT_LABEL = { key: "bracket.slot.bye", params: { bye: "draw" } } as const;

/** A Swiss round's bye SHELL key (`planSwissShells`, lib/swiss-shell.ts): the
 *  one row per round a Swiss sit-out is seated on. */
const SWISS_BYE_EXT_KEY = /^sw-r[0-9]+-bye$/;

const isDrawByeLabel = (label: unknown): boolean => {
  if (!label || typeof label !== "object") return false;
  const l = label as { key?: unknown; params?: { bye?: unknown } | null };
  return l.key === DRAW_BYE_SLOT_LABEL.key && l.params?.bye === DRAW_BYE_SLOT_LABEL.params.bye;
};

type LabelledByeRow = ByeRow & { home_slot_label?: unknown; away_slot_label?: unknown };

/**
 * A bracket's DRAW bye, by its marker: a one-sided award bye whose empty seat
 * carries `DRAW_BYE_SLOT_LABEL`. The generator's first-round byes, and every
 * seat the cascade (`resolveBracketSeats`, usecases/stages.ts) finds the DRAW
 * left empty — a losers'-bracket or third-place seat that a draw bye can never
 * drop anyone into (#850 review round 3). A vacated seat's walkover carries
 * the plain label and is not one.
 */
export function isDrawBye(f: LabelledByeRow): boolean {
  return isOneSidedAwardBye(f) && isDrawByeLabel(f.home_entrant_id === null ? f.home_slot_label : f.away_slot_label);
}

/**
 * A SIT-OUT: a one-sided award bye the schedule itself made, and nobody plays
 * — exactly the three kinds, each by its OWN explicit marker, never by row
 * shape (orchestrator ruling 2026-09-24 on the ICS feed):
 *   - a round-robin REST bye — `isRestBye` (the `restByeExtKey` marker);
 *   - a SWISS sit-out — seated on its round's bye shell, `sw-r{n}-bye`;
 *   - a bracket's DRAW bye — its phantom seat carries `DRAW_BYE_SLOT_LABEL`.
 * A departed qualifier's walkover (`awardSeededByes` on a vacated seat) has
 * the same shape and none of the markers: it is not a sit-out, and keeps its
 * pre-#850 display wherever this is asked.
 */
export function isSitOutBye(f: LabelledByeRow, stageKind: string): boolean {
  if (!isOneSidedAwardBye(f)) return false;
  if (isRestBye(f, stageKind)) return true;
  if (stageKind === "swiss") return typeof f.ext_key === "string" && SWISS_BYE_EXT_KEY.test(f.ext_key);
  return isDrawBye(f);
}

/** The fields that say which ROUND a row belongs to: its stage, its pool (a
 *  group stage's pools share round numbers) and its round. */
export type RoundRow = { stage_id: string; pool_id?: string | null; round_no: number };

const roundOf = (f: RoundRow) => `${f.stage_id}|${f.pool_id ?? ""}|${f.round_no}`;

/**
 * Put each round-robin rest bye INSIDE ITS ROUND on a list-shaped surface
 * (#850 owner rulings: the organiser run sheet, 2026-09-23 — "inside its round
 * (and pool)"; public surfaces, 2026-09-24 — "a NOTE in its round").
 *
 * `lists` is the surface's rows in the order it renders them — its groups in
 * order, each group's rows in order — WITHOUT the byes. Each bye is inserted
 * right after the LAST row of its own round (same stage, pool and round) in
 * that order, so a round split across two groups closes with its bye in the
 * group where it finishes. `isMate` says which rows count as the round's
 * matches (a surface's other byes do not).
 *
 * `open` (the organiser run sheet, review round 2 R2-5): which rows are
 * matches NOT YET SETTLED. While the bye's round still has one, the bye goes
 * to the block (list) of the round's LAST such match — after the round's last
 * row in that block — never to a later block holding only its played matches.
 * A run sheet's settled tail ("Played, not scheduled") sorts after "Not yet
 * scheduled", so "after the last row" alone parked the bye under "Played"
 * while its round still had a match waiting for a time. LAST open, not first,
 * so a round still to play across two days keeps closing on the day it
 * finishes. With no open match left, the plain rule above applies.
 *
 * `nearest` (for a list filtered to one entrant, where the bye holder by
 * definition plays nobody that round): a bye with no row of its own round
 * goes after the last row of an EARLIER round of the same stage and pool, else
 * before the first row of a LATER one — the holder's own schedule, read in
 * round order.
 *
 * MUTATES `lists`; returns the byes it could not place anywhere (the caller
 * decides their fallback — never silently dropped here). Byes are placed in
 * (stage, round) order so two byes of one round keep a stable order.
 */
export function placeRestByesInRounds<T extends RoundRow>(
  lists: T[][],
  byes: readonly T[],
  isMate: (row: T) => boolean,
  opts: { nearest?: boolean; open?: (row: T) => boolean } = {},
): T[] {
  const unplaced: T[] = [];
  for (const bye of [...byes].sort((a, b) => a.round_no - b.round_no)) {
    const key = roundOf(bye);
    const mateOf = (row: T) => isMate(row) && roundOf(row) === key;
    // R2-5: the block of the round's last unsettled match, when there is one.
    // (A plain loop, not `findLast`: the smoke script loads this file under
    // an ES2022 lib.)
    let openList: T[] | undefined;
    if (opts.open) {
      for (const list of lists) if (list.some((row) => mateOf(row) && opts.open!(row))) openList = list;
    }
    let at: { list: T[]; index: number } | null = null;
    for (const list of openList ? [openList] : lists) {
      for (let index = 0; index < list.length; index++) {
        const row = list[index]!;
        if (mateOf(row)) at = { list, index: index + 1 };
      }
    }
    if (at === null && opts.nearest) {
      const samePool = (row: T) =>
        isMate(row) && row.stage_id === bye.stage_id && (row.pool_id ?? "") === (bye.pool_id ?? "");
      for (const list of lists) {
        for (let index = 0; index < list.length; index++) {
          const row = list[index]!;
          if (samePool(row) && row.round_no < bye.round_no) at = { list, index: index + 1 };
        }
      }
      if (at === null) {
        search: for (const list of lists) {
          for (let index = 0; index < list.length; index++) {
            const row = list[index]!;
            if (samePool(row) && row.round_no > bye.round_no) {
              at = { list, index };
              break search;
            }
          }
        }
      }
    }
    if (at === null) unplaced.push(bye);
    else at.list.splice(at.index, 0, bye);
  }
  return unplaced;
}
