// ONE predicate for "this fixture row is a system-generated bye".
//
// Client-safe on purpose (pure, type-only engine import): the Swiss seating
// helpers, the stage rail and the server-only standings fold must all agree,
// and the 2026-09-20 review's C1 is exactly what happens when they don't —
// `swiss-shell.ts` called ANY `outcome.kind === "award"` a bye, so a real
// two-sided forfeit or retirement was classified as a sit-out and Unpair
// nulled the board's entrants, status and outcome. The correct test already
// existed 1000 lines away in `server/engine-db/competition.ts`; it lives here
// now so there is nothing left to drift.
//
// Every sport kernel emits `{ kind: "award", winner }` for a real two-sided
// walkover/retirement (generic.ts, setbased/kernel.ts, football.ts,
// nested/kernel.ts, cricket.ts, carrom.ts), so the OUTCOME SHAPE ALONE CAN
// NEVER DECIDE THIS. What separates a bye is the seats: a bye has exactly one
// entrant by construction (swissGen writes `away_entrant_id = null`, a
// knockout seeds the same shape), and the entrant sitting out always wins its
// own bye.

import type { MatchOutcome } from "@seazn/engine/core";

/**
 * True only for a genuine system-generated bye: an `award` outcome naming a
 * winner, EXACTLY one seat filled, and the seated side IS that winner.
 *
 * A two-sided award (forfeit / retirement) is a played match and returns
 * false — destroying it would erase the reason the opponent advanced
 * (`stages.ts` rebuild guard, same rule).
 */
export function isOneSidedAwardBye(f: {
  outcome: unknown;
  home_entrant_id: string | null;
  away_entrant_id: string | null;
}): boolean {
  if (!f.outcome || typeof f.outcome !== "object") return false;
  const o = f.outcome as MatchOutcome;
  if (o.kind !== "award" || !o.winner) return false;
  const home = f.home_entrant_id;
  const away = f.away_entrant_id;
  const oneSided = (home !== null && away === null) || (home === null && away !== null);
  if (!oneSided) return false;
  const seated = home ?? away;
  return seated === o.winner;
}
